### ISSUE TITLE
Не отображает более 9999 файлов в папке.

### ISSUE THREAD

**Issue by commensal** [pozitronik/CloudMailRu#100]
При наличии более 9999 файлов регулярная синхронизация обречена на беспощадный и бесмысленный перезалив в облако.

**Comment by pozitronik** [comment]
[Меняй@Пересобирай](https://github.com/pozitronik/CloudMailRu/blob/master/CloudMailRu.pas#L27)

**Comment by commensal** [comment]
Шоб я умел :)
А зачем там вообще limit?
У облака вроде нет ограничений на кол-во файлов в папке.

**Comment by pozitronik** [comment]
Web-клиент запрашивает список файлов частями, по мере прокручивания. TC так не умеет, поэтому я просто поставил достаточно большую, на мой взгляд, величину для единоразового запроса. Цифру подкрутить несложно.

**Comment by Owyn** [comment]
всё ещё в коде:
> &limit=65535

А можно всё таки несколько раз (частей) запросить тоже из облака через таймаут при коннекте (в фоне может даже)?

У меня `файлов 326 914` например... это количество вообще в единоразовый запрос влезет? Если влезет, то "зачем там вообще limit" тогда? Если нет - почините очень пожалуйста 🙏
