### ISSUE TITLE
Webdav/FTP - интерфейс

### ISSUE THREAD

**Issue by pozitronik** [pozitronik/CloudMailRu#101]
Сделать эмуляцию, чтобы можно было монтировать облако как диск в проводнике. Можно будет слушать музыку в плеере без заморочек.

**Comment by pozitronik** [comment]
Готовой реализации webdav-сервера не нашлось, а пилить самому очень лениво.

**Comment by andreymukha** [comment]
А это не подойдёт? https://geektimes.ru/post/285520/

**Comment by pozitronik** [comment]
Видел, но это не о том. Там реализация на C#, что для меня бесполезно. Я надеялся, что либо в стандартных компонентах Delphi уже есть готовая реализация WebDAV-сервера, либо найдётся открытый компонент, но нашёл только проприетарные закрытые компоненты, что меня не устраивает.

Я хочу подойти более глобально: написать враппер для всех WFX/UWFX/WFX64-файлов, добавив к нему FTP и WebDAV-интерфейсы. Так что это будет отдельный проект, если вообще дойдут руки.

**Comment by pozitronik** [comment]
С учётом реализации #115 (теперь музыку без заморочек можно слушать по прямым ссылкам), это делать не стану.

**Comment by pozitronik** [comment]
C учётом того, что прямые ссылки, как оказалось, протухают, задача снова становится актуальна.

**Comment by pozitronik** [comment]
Эта задача - отдельный проект => [WFXWrapper](https://github.com/pozitronik/WFXWrapper).
