### ISSUE TITLE
Не обрабатывается превышение квоты как ошибка

### ISSUE THREAD

**Issue by areht** [pozitronik/CloudMailRu#102]
При удалённом переносе с ошибкой на каждом файле
"Can't parse server answer: {"email":"**@*******","body":"overquota","time":1487220298763,"status":507}"
удаляет исходный файл.

**Comment by pozitronik** [comment]
- Добавил корректную обработку 507 кода (до этого предполагалось, что overquota не имеет отдельного статуса ошибки).
- Добавил диалог запроса на остановку/продолжение операции при ошибке клонирования. Появление диалога зависит от настройки "Ask to stop downloads/uploads on any error".

Просьба потестировать.

**Comment by areht** [comment]
Если включить "Ask to stop downloads/uploads on any error" - похоже, что работает. 

Без неё исходный файл всё равно исчезал.

**Comment by pozitronik** [comment]
>Без неё исходный файл всё равно исчезал.

Поправил.
