### ISSUE TITLE
Хочется альтернативного разделения файлов по 2000М

### ISSUE THREAD

**Issue by areht** [pozitronik/CloudMailRu#103]
Например:
- видео прогонять через mkvmerge с --split size:2000M --link
- Делать многотомный rar-архив

В плагине сильно мудрить смысла нет, а вот добавить бы опцию с вызовом внешнего скрипта, который бы возвращал "разделённые" файлы...

**Comment by pozitronik** [comment]
Это можно делать и в самом TC, незачем плодить сущности.

**Comment by areht** [comment]
А где в TC это настраивается? Или имеется в виду "руками через TC запустить до копирования"?

**Comment by pozitronik** [comment]
>Или имеется в виду "руками через TC запустить до копирования"?
This

**Comment by areht** [comment]
Так это и с "простым" разделением можно было не плодить сущности...

**Comment by pozitronik** [comment]
>Так это и с "простым" разделением можно было не плодить сущности...

Потребность в базовом разбиении вытекала из ограничений облака, соответственно инструмент, которым является плагин, должен был уметь эти ограничения обходить.

**Comment by areht** [comment]
"У каждой сложной проблемы есть простое, всем понятное… неправильное решение."

Попробую развернуть мысль. Я вижу требования к инструменту "умеющему обходить" так:
1) Прозрачная работа при загрузке
2) (опционально) прозрачное восстановление исходного файла при скачке
3) Сохранение возможности восстановления исходного файла на любой конфигурации без головной боли (я догадываюсь, что на андроиде склеить файлы можно, но удовольствия мне это не доставит), то есть формат должен быть как можно более "ходовым"
4) Сохранение возможности использования файла "в облаке" (картинки смотрятся, музыка играется и т.п)

Из этого простое разрезание умеет 1 и, с большой натяжкой, 3 (проблема решаемая, хотя даже в TC это требует отдельных телодвижений). 

С многотомными архивами софт знаком, иногда даже работает прозрачно, т.е. 3 выполняется, 4 - возможно, 2 - может быть и не нужен.

С "разделёнными" .mkv софт работает прозрачно, 3 - скорее не нужно, следовательно 2 - тоже не нужно, 4 - выполняется.

Например, такой тест на user friendly: вы сможете объяснить бабушке по телефону, почему файлов больше одного и что именно ей надо сделать, если у неё нет заранее настроенного TC?

**Comment by pozitronik** [comment]
Возможно (но не обязательно) вызов внешних программ появится при реализации issue #5 (в зависимости от того, как это будет сделано, и будет ли сделано вообще).
Это обсуждение закрываю.
