### ISSUE TITLE
Неверно отображается скорость закачки

### ISSUE THREAD

**Issue by andreymukha** [pozitronik/CloudMailRu#104]
Total Commander 9.0a
Плагин - последний стабильный, скачал только что.

Скорость загрузки http://joxi.ru/ZrJqO03i9nOgeA
Интернет у меня 8 Мбит/с
Как понимаете такой скорости быть не может у меня))))

**Comment by pozitronik** [comment]
TC пытается высчитать скорость операции, исходя из известного размера файлов и объёма обработанных данных. Плагин никак на это не влияет.
