### ISSUE TITLE
Настройки по alt+enter не работают

### ISSUE THREAD

**Issue by andreymukha** [pozitronik/CloudMailRu#105]
Total Commander 9.0a
Плагин - последний стабильный, скачал только что.

Так и не смог добиться вызова настроек по alt+enterб ранее тоже было так с другими версиями, но как-то всё же выходило это сделать, а сейчас вообще никак.

**Comment by pozitronik** [comment]
Не подтверждаю, всё работает. Какая последовательность действий, начиная от запуска TC?

**Comment by andreymukha** [comment]
Перешёл в сеть, поставил курсор на строку с mail.ru, нажал на ctrl+enter

**Comment by pozitronik** [comment]
1. Плагин инсталлируется с именем CloudMailRu.
2. Настройки вызываются по Alt+Enter или по нажатию пункта "Свойства" в контекстном меню.

**Comment by andreymukha** [comment]
Может где-то в настройках есть запускать ли по Alt+Enter?

**Comment by pozitronik** [comment]
Ещё раз: проблемы в плагине нет. Alt+Enter (не Ctrl+Enter, ни какое-то другое сочетание) может не работать только в следующих случаях:
- Плагин установлен некорректно (на что косвенно намекает непонятное название в сетевом окружении ).
- В самом TC на Alt+Enter настроено другое действие или же клавиатурное сочетание глобально чем-то перехватывается.

Если настройки вызываются через контекстное меню - проблема во второй причине.

**Comment by andreymukha** [comment]
Не нашёл у себя вообще каких либо привязок к этому сочетанию клавиш... Не подскажете как именно называется команда, что бы я мог сам привязать?

**Comment by pozitronik** [comment]
Через меню настройки открываются?

**Comment by andreymukha** [comment]
Вы про это? http://joxi.ru/1A59Qajfnbj0lA
Так открывается, сочетаний клавиш не установлено на Alt + Enter http://joxi.ru/Y2LqpEni9E5waA

**Comment by pozitronik** [comment]
Команду легко можно найти поиском в диалоге "Список команд", она называется cm_properties.

**Comment by andreymukha** [comment]
Спасибо
