### ISSUE TITLE
Падение ТС

### ISSUE THREAD

**Issue by SchwarzKopf-M** [pozitronik/CloudMailRu#109]
Мало пользуюсь, но с недавнего времени стал замечать что ТС падает когда зайдя и выйдя из папки облака пытаешься зайти заново. ТС 9.0а Вин7-64.

**Comment by pozitronik** [comment]
Мало информации. Я пользуюсь плагином очень активно, и подобного поведения ни разу не замечал.

**Comment by SchwarzKopf-M** [comment]
Даже не знаю, но эффект стабильный, падает каждый раз. Какую дополнительно информацию можно предоставить? Проверял именно на выложенном здесь бинарнике.

**Comment by pozitronik** [comment]
Здесь выложено довольно много бинарников. Воспроизводится ли эффект [с этим](github.com/pozitronik/CloudMailRu/blob/master/MailRuCloud.wfx64) файлом?
Какие настройки у плагина (секция Global settings, можно скриншот или содержимое MailRuCloud.global.ini)?
Каков точный сценарий воспроизведения ошибки? Буквально по шагам, начиная от запуска TC. Если есть возможность сделать скринкаст - можно его.

**Comment by pozitronik** [comment]
Падает только x64-версия? x32 нормально?

**Comment by SchwarzKopf-M** [comment]
Бинарник от CloudMailRu-19022017 рабочий, а Master уже нет. Воспроизвести можно находясь в папке с файлами облака нажать "Отключение". Если выйти из папки до самой панели ТС, то копка "Отключение" ещё есть, если её нажать то панель успешно скрывается, но при входе с панели ТС уже падение.
Содержимое файла настроек:
[Main]
LoadSSLDLLOnlyFromPluginDir=1
PreserveFileTime=0
DescriptionEnabled=0
OperationsViaPublicLinkEnabled=0
AskOnErrors=0
SocketTimeout=-1
ProxyType=0
ProxyServer=
ProxyPort=0
ProxyUser=
ProxyPassword=
ProxyTCPwdMngr=0
ChunkOverwriteMode=0
DeleteFailOnUploadMode=0
OverwriteLocalMode=0
DisableMultiThreading=0
LogUserSpace=0
IconsMode=0
OperationErrorMode=0
RetryAttempts=1
AttemptWait=1000

Выложенный тобой файл для теста недоступен. ТС у меня 64-битный, чтобы запустить 32-биный придётся повозиться. Если не удастся найти причину падения, проверю на 32-битке.

**Comment by pozitronik** [comment]
>Выложенный тобой файл для теста недоступен.

Это прямая ссылка на блоб из мастера. Нужные файлы можно тупо брать отсюда: https://github.com/pozitronik/CloudMailRu

>чтобы запустить 32-биный придётся повозиться
Достаточно скачать x32-инсталлятор и установить рядом. Проблемы могут быть только в случае, если используется какая-то хитровымудренная сборка, где всё перекопано донельзя.

**Comment by pozitronik** [comment]
>Воспроизвести можно находясь в папке с файлами облака нажать "Отключение".

Всё, воспроизводится. Это последствия вчерашних изменений, исправлю.

**Comment by SchwarzKopf-M** [comment]
Так именно скаченная с "Master" скачивал, она и падает. Сборками ТС не пользуюсь. Запустил 32-битный ТС, выдаётся сообщение об ошибке.
![default](https://cloud.githubusercontent.com/assets/1192230/23330721/f4b0a54e-fb6e-11e6-8203-3febb10321b9.png)
Пишет что проблема с функцией FindFirst, возможно что в 32-битке эта ошибка, а в 64- что-то другое.

**Comment by SchwarzKopf-M** [comment]
Ага... Уже воспроизвёл, это хорошо. :)

**Comment by pozitronik** [comment]
Разобрался: TC при нажатии кнопки disconnect закрывает не плагин, а соединение (это сделано специально для поддержки многих соединений в одном плагине), переходя, при этом в корневой каталог плагина. При этом происходит обращение к словарям, уничтоженным ранее.
Поскольку словари нужны по всему существованию плагина, а момент отключения гарантированно поймать нельзя, то я просто не буду уничтожать эти словари. Это немного увеличит занимаемую память, но другого варианта нет.
Можно проверить на свежей сборке.

**Comment by SchwarzKopf-M** [comment]
Щас перепроверю на своём варианте. :)

**Comment by SchwarzKopf-M** [comment]
Ага... Просто не уничтожаешь пять созданных ранее потока... Тоже вариант. Может со временем найдётся лучший вариант. Как-бы всё работает без падений.

**Comment by pozitronik** [comment]
Потоки не причём, речь о структурах TDictionary, используемых для хранения потокозависимых флагов операций.
