### ISSUE TITLE
Поддержка прокси

### ISSUE THREAD

**Issue by pozitronik** [pozitronik/CloudMailRu#11]
Subj

**Comment by Dreamer-4pda** [comment]
При попытке подключения получаю такой ответ:
```
CONNECT Denny-SKA@mail.ru
Login to Denny-SKA@mail.ru
Cloud login error: Socket Error # 10013
Access denied.
```
Выход в интернет через прокси.

**Comment by pozitronik** [comment]
Ну так прокси ещё не запилено =)

**Comment by Dreamer-4pda** [comment]
Ну так я для статистики кинул ;)

**Comment by pozitronik** [comment]
Implemented at 23413a13b7536bdd0c7dc7ee95b77c7f924cbab8

**Comment by pozitronik** [comment]
Просят ещё и http-прокси добавить.

**Comment by pozitronik** [comment]
Done at commit 2061103c24c8ce51a0bee66da4627c0ba5eb435b
