### ISSUE TITLE
Ошибка копирования файла более 2Гб

### ISSUE THREAD

**Issue by shustry** [pozitronik/CloudMailRu#110]
Не происходит разбиения файла на части при копировании в облако.

**Comment by pozitronik** [comment]
Нужно больше информации (см. readme.md).

**Comment by PavelQuash** [comment]
При разбиении файла во временной директории создаются файлы, которые будут заливаться в облако. На диске, где расположена эта директория, должно быть достаточно места.

**Comment by pozitronik** [comment]
>На диске, где расположена эта директория, должно быть достаточно места.

Это трудно назвать ошибкой.
В этом случае копирование должно остановиться, в лог должна упасть соответствующая запись. Что тут не соответствует ожидаемому поведению?

**Comment by pozitronik** [comment]
Я немного изменил поведение при ошибке: теперь при нехватке места запись будет падать в протокол (до этого разбиение останавливалось с неопознанной ошибкой).
