### ISSUE TITLE
Вечная рекурсия при копировании/переносе родительской директории в ее внутренние на облаке (один аккаунт).

### ISSUE THREAD

**Issue by Corak667** [pozitronik/CloudMailRu#113]
Только что случайно попытался перенести из папку на облаке в эту же папку (вместе с другими папками), естественно в пределах одного акка и с разрешенным копированием-переносом через публичные линки. 
Результат смешной, но адовый - оно начало переносить остальные папки в эту, а дальше когда дошло до нее - по циклу снова создало внутри папку с тем же названием и начало переносить уже перенесенные папки все глубже и глубже.
сперва в
Touhou Collection\
потом...
Touhou Collection\Touhou Collection\
и так далее
http://picsee.net/upload/2017-03-10/8a7e059fe132.png
Ну не суть, просто думаю - как возможно этого избежать... Может создавать предварительно лист всех файлов, чтобы оно исключало все НОВЫЕ внутренние вложения. Или как-то сделать исключение, чтобы не пыталось переместить-скопировать одну из родительских директорий...

**Comment by pozitronik** [comment]
Ок, посмотрю, можно ли ограничить. Если нет, то внесу описание в документацию.

**Comment by Corak667** [comment]
И еще, остановить этот процесс невозможно - кнопка "отмена" - ничего не дает. Так что стоит наверное еще как-то придумать, чтобы можно было остановить.

**Comment by pozitronik** [comment]
К сожалению, предотвратить такое поведение оказалось невозможно. Я обошёлся тем, что перекрываю диалог прогресса в случаях копирования внутри облака, и, таким образом, даю пользователю возможность отменить процесс.

**Comment by Corak667** [comment]
Ну хотя бы отменить возможность, уже лучше чем ничего.
 С другой стороны, есть и некоторый плюс если бы скорость была слишком шустрая, поскольку ситуация была бы полностью адовая - например, если создавало бы более 1000 папок в секунду и перекидывало внутрь них файлы.. можно сказать файлы были бы тогда потеряны, поскольку чтобы переходить по данной структуре директорий - потребуются нечеловеческие усилия, либо поиск по имени.
