### ISSUE TITLE
Доступ до "корзины" временного хранения (15 дней) для восстановления файлов.

### ISSUE THREAD

**Issue by Corak667** [pozitronik/CloudMailRu#114]
Заметил еще, что они уже годик или более назад реализовали теоретически неограниченную корзину временного хранения (на 15 дней вроде), куда переносятся все удаленные с облака файлы. 

Возможно ли будет как-то реализовать доступ до нее (например виртуальной папкой/алиасом (с кастомным пользовательским названием) внутри облака или каким-то еще методом. Проблема конечно же ожидаема - нужно будет ее как-то наименовать, чтобы не было конфликтов с потенциально существующими папками), желательно это конечно, чтобы не использовать браузер или ведроид/айось приложение для этого дела. Или в доступном API совершенно пока не найдена эта фишка?

**Comment by pozitronik** [comment]
В API функции есть, но я решил не делать к "Корзине" доступ - частично, из-за проблем с её "виртуальностью", частично потому, что мне сама идея "Корзины" не нравится.
Может быть интереса ради сделаю как-нибудь опциональное включение "Корзины". Без обещаний.

**Comment by Corak667** [comment]
Спасибо, понимаю, конечно!) Ну вообще идея была в том чтобы реализовать к ней доступ опционально по алисам - аналогично линкам шары, но в данном случае использовать просто авторизацию аккаунт, но с галочкой что "доступ до корзины аккаунта".

**Comment by pozitronik** [comment]
Это один из вариантов - вместе с аккаунтом показывать каталог %account.trash%.

**Comment by Corak667** [comment]
Тоже хороший вариант. То есть при включенной опции (для некоторых акков) - просто рядом с алиасом аккаунта создавать - %accountname.trash%, так? И чтобы потом можно было их легко отрубать..

**Comment by pozitronik** [comment]
Что-то вроде этого, да.

**Comment by pozitronik** [comment]
Базовая реализация в master, есть ещё что полировать, но в целом работает. Внутри корзины работают только Enter/Alt+Enter (одинаково) + Alt+Enter на самой корзине. Других вариантов, к сожалению, нет.

**Comment by Corak667** [comment]
Проверил! Все работает как надо, спасибо! Теперь не нужно лазять на сайт, если случайно удалить важный бекап) (такое бывает редко, но пару раз уже бывало)
