### ISSUE TITLE
Получение ссылки на скачивания

### ISSUE THREAD

**Issue by Vismmax** [pozitronik/CloudMailRu#115]
Возможно сделать получение ссылки для скачивания аналогично веб версии?
Варианты использования:
- скачивание больших файлов альтернативным загрузчиком;
- просмотр видео файлов без скачивания;
- прослушивание аудиокниг без скачивания.

**Comment by pozitronik** [comment]
В API таких методов по-моему нет, нужно парсить страницу на предмет ссылок. При наличии свободного времени посмотрю, что можно сделать.

**Comment by Vismmax** [comment]
Post запрос отправляется на https://cloud.mail.ru/api/v2/tokens/download. Ответ в json формате.
Может добавили в API?

**Comment by pozitronik** [comment]
Надо смотреть что и как, с лёту не скажу.

**Comment by pozitronik** [comment]
Посмотрел - для публичных аккаунтов это будет работать, т.е. можно получать прямые ссылки на файлы. Появилась задумка, как это можно использовать, теперь реализация - вопрос свободного времени.

**Comment by pozitronik** [comment]
Сделано следующее: при вызове свойств файла в публичном каталоге будет показана публичная ссылка (для открытия в облаке) и прямая ссылка на скачивание (которую можно вставить в любую программу, умеющую работать по https. При вызове свойств каталога будут показаны ссылки на все файлы в этом каталоге, в т.ч. - в подкаталогах. Сканирование больших каталогов может занять время, прогресс логируется в протокол (пока мне не удалось сделать как-то иначе).
В ближайшее время постараюсь улучшить фичу - добавлю кнопку для сохранения списка в файл/буфер обмена, и т.п.

**Comment by pozitronik** [comment]
Реализовано, описание в readme.

**Comment by Vismmax** [comment]
Спасибо.
Это даже больше чем я ожидал. Теперь, по сути, можно получить плейлист из файлов в каталоге.

**Comment by pozitronik** [comment]
>Теперь, по сути, можно получить плейлист из файлов в каталоге.

Ну я собственно, об этом и думал, когда делал, для [МДС](https://cloud.mail.ru/public/LbEn/AmzghuRDH), например.

**Comment by pozitronik** [comment]
Выяснилось, что прямые ссылки через какое-то время протухают. Сделать с этим нельзя ничего - это серверное ограничение.

**Comment by Vismmax** [comment]
Да, я об этом знал. Так, по моему, во всех облаках. Но не вижу в этом большой проблемы. Если не хранить, к примеру, тонны музыки, и постоянно ее всю слушать. А получить ссылки на книгу, автора, подборку видео можно при необходимости, а не хранить их постоянно.

**Comment by Corak667** [comment]
Пока практика показала, что единственные прямые публичные ссылки, которые вроде как не протухают - ссылки на zip архивацию файлов, но конечно этот вариант не сильно так плеерами, поскольку: 
1. Требуется выбрать несколько треков или целую директорию сразу для архивации в ZIP.
2. Будет играться только первый по списку.
3. В плеере кроме метода стриминга по https должна быть реализована поддержка zip распаковки или плагином
4. Попробовал с VLC - стримит все mp3 как один поток типа радио, после завершения первого трека идет последующий и так далее, можно прокручивать по всему общуму потоку, хотя общее время не определяет.

**Comment by pozitronik** [comment]
За инфу спасибо. В принципе, winamp с zip-архивами примерно также работает.

**Comment by Corak667** [comment]
Сейчас проверил с более 2мя файлами - VLC плеер не хочет их прослушивать. А вот 2 нормально. Изврат, но, что поделать.
