### ISSUE TITLE
Ошибка при копировании или перенос файлов между аккаунтами.

### ISSUE THREAD

**Issue by Corak667** [pozitronik/CloudMailRu#116]
Ошибка при копировании или переносе файлов (если выбирать файлы отдельно) между аккаунтами. При этом перенос и копирование выбранных папок нормально, без ошибок.
Если файл уже существует:

Билд 19 февраля: нормально определяет, если файл с таким же именем уже существует и выдает запрос на замену файла: 
https://github.com/pozitronik/CloudMailRu/commit/00f72221b7cc8c1c7f38411c012fe6c90af040b0

Билд 24 февраля уже выдает ошибку, если файл уже существует и невозможно заменить файл, но копирует в пустую папку нормально: 
https://github.com/pozitronik/CloudMailRu/commit/a517d1786239a12f1ab0142b24bdce18e432689c

Билд 25 февраля (и новее) вообще всегда выдает ошибку при каждом копировании файла и переносе между акками, но тем не менее копирует в пустую папку (хоть и уже с ошибками):
https://github.com/pozitronik/CloudMailRu/commit/edc14ad26d347746bd3db22e70be97237447d09f

Также если файл уже существует и попытка копировать поверх него, вызывает ошибку: 
File publish error: Неизвестная ошибка (6):
http://picsee.net/upload/2017-03-24/63fec6b0b064.png
В логах как
"File publish error: Ошибка запроса к серверу. Status: 400"

Где-то между ними каким-то коммитом поломал эту функцию

**Comment by pozitronik** [comment]
Поправлено. Проблема появилась из-за нескольких изменений:
- При разборе ответов облака 400 ошибка [стала считаться](https://github.com/pozitronik/CloudMailRu/commit/559c20871f9e533b509949a34af904caabb04c75#diff-0d7a7a5edd6f1291e52dabef4e5795edR717) неопознанной всегда, хотя в некоторых случаях можно было определить причину ошибки более конкретно. Я уже не помню, почему так было сделано, видимо какой-то метод возвращал HTTP 400 без подробностей. Я пофиксил так, чтобы во всех случаях ошибк определялась.
- Копирование/перемещение через публичные ссылки не учитывало возможность существования файла с исходным именем в каталоге-приёмнике. До какого-то времени метод мог просто вернуть CLOUD_ERROR_EXISTS, который отдавался в TC как FS_FILE_EXISTS, но после добавления [OperationErrorMode](https://github.com/pozitronik/CloudMailRu/commit/325ff1e0cfc50b6cdf557553ed86bea9f9d3165a) любой ответ кроме CLOUD_OPERATION_OK стал считаться ошибкой.

**Comment by Corak667** [comment]
Да, теперь  все Отлично Работает! Спасибо!

**Comment by g8tguy** [comment]
еще бы дата скопированного файла в облако оставалась такая же как на локальной машине - что бы можно было папки синхронизировать - вообще замечательно бы было

**Comment by Corak667** [comment]
@g8tguy https://github.com/pozitronik/CloudMailRu/issues/60
https://github.com/pozitronik/CloudMailRu/issues/45
