### ISSUE TITLE
Ошибка при подключении к аккаунту

### ISSUE THREAD

**Issue by wormen** [pozitronik/CloudMailRu#118]
Установил текущий стабильный релиз в ТС 9.0 x64, сборка ТС чистая
после того как забил в настройки аккаунт и попытался подключиться, получил ошибку

```
CONNECT \wormen
Login to wormen@bk.ru
EIdSocketError ошибка сети: Socket Error # 10054
Connection reset by peer. при отправке данных на адрес https://auth.mail.ru/cgi-bin/auth?lang=ru_RU&from=authpopup
error: login to wormen@bk.ru
```

в какую сторону копать, не понятно

**Comment by pozitronik** [comment]
Копать в сторону настроек сети. Вероятно, для соединения используется прокси, или соединение блокируется фаерволлом.

**Comment by wormen** [comment]
проверил это предположение ....
прокси не использую
антивир и фаервол отключил
ничего не изменилось, все та же ошибка

**Comment by pozitronik** [comment]
Такая ошибка может возникнуть только в случае проблем с доступом к серверу авторизации mail.ru. Проверьте работу через браузер, если работает - значит что-то блокирует доступ самого плагина, если не работает - значит заблокирован доступ в общем.
