### ISSUE TITLE
Доработка проекта

### ISSUE THREAD

**Issue by Epexa** [pozitronik/CloudMailRu#119]
Привет!

Спасибо за хороший плагин!

Как Вы считаете, не было бы лучше объединить ваш плагин с [официальным (от Гислера) плагином Cloud](https://ghisler.ch/board/viewtopic.php?t=41512) ?
Он поддерживает на данный момент:
- Dropbox
- Box
- OneDrive
- Google Drive
- Yandex Drive

**Comment by pozitronik** [comment]
Не только не лучше, но и невозможно очень по многим причинам (частично описанным [тут](http://forum.wincmd.ru/viewtopic.php?p=119602#119602).
