### ISSUE TITLE
Отключается со второго раза

### ISSUE THREAD

**Issue by Baton34** [pozitronik/CloudMailRu#12]
После соединения с облаком, при попытке отключиться, нажав на кнопку "Отключение", в панели TC переходит в папку которая была открыта до выбора "Сеть/FS плагины", после нажатия на кнопку "Отключение" ещё раз происходит отключение плагина от облака.

**Comment by pozitronik** [comment]
Это [подтверждённое](http://forum.wincmd.ru/viewpost.php?p=117416) (хотя и непонятное) поведение Total Commander в некоторых случаях, плагин тут не при чём.
