### ISSUE TITLE
EIdOSSLCouldNotLoadSSLLibrary ошибка с сообщением: Could not load SSL library. при отправке данных на адрес https://auth.mail.ru/cgi-bin/auth

### ISSUE THREAD

**Issue by siabr** [pozitronik/CloudMailRu#122]
Установил плагин буквально 11-12 апреля 2017 и на удивление все заработало на раз-два.
Быстро, шустро, показывало размеры папок.
Думаю прелесть какая, можно зайти в любой момент скопировать/удалить и все без браузера.
На выходные оставил работать Cloud.Mail.Ru агента для синхронизации папок.
И вот сегодня 17.04.2017, вижу переименованные дубликаты файлов в каталоге синхронизации, думаю посмотрю через плагин, что старое, что свежее, подчищу, а плагин не работает.
При попытке установить соединение пишет: "EIdOSSLCouldNotLoadSSLLibrary ошибка с сообщением: Could not load SSL library. при отправке данных на адрес https://auth.mail.ru/cgi-bin/auth"
На прошлой неделе все работало. Я просто создал вручную папку, закинул плагины , вручную вписал  их в Конфигурация-Настройки-Плагины.

**Comment by pozitronik** [comment]
Прочтите пожалуйста документацию.

**Comment by s-belichenko-sold** [comment]
@pozitronik У меня аналогичная проблема, при том, что я установил необходимые, на мой взгляд, библиотеки. Не могли бы вы более точно указать, какие именно из них требуются? Мой список на текущий момент такой, другой софт на отсутствие упомянутую в документации msvcr110.dll не жалуется (после установки пакетов из списка ниже).

![image](https://user-images.githubusercontent.com/9050851/26977660-50a12c02-4d31-11e7-9e0f-f0729f94db41.png)

**Comment by pozitronik** [comment]
Аналогичная проблема также решается аналогично, в документации всё описано. На скриншоте же вообще наборы библиотек MS VC++, которые к SSL-библиотекам имеют весьма опосредованное отношение.

**Comment by s-belichenko-sold** [comment]
@pozitronik ну я просто поискал информацию про упомянутую в документации MVCR110.dll - и весь интернет хором говорит, что она содержится в упомянутых пакетах. Я ведь верно понимаю, что упомянутая автором выше ошибка связана именно с отсутствием или неверной версией этой dll-ки?

**Comment by pozitronik** [comment]
Так, начнём с начала.
Начальный тикет сообщает о проблеме с подгрузкой SSL-библиотек. Эта проблема достаточно подробно разобрана в документации. Вы пишете об аналогичной проблеме, но, почему-то, ссылаетесь на библиотеки MS VC++. Выходит, проблема не аналогична.
Я могу предположить, что плагин при загрузке сообщает об отсутствии библиотеки msvcr*.dll. Такое возможно, поскольку включённые в дистрибутив плагина SSL-библиотеки собраны с зависимостью от этого пакета. Но пока проблема не описана корректно и ясно, я на этом предположении основываться не буду.
Поэтому комментирование тут закрываю. Пожалуйста опишите проблему в отдельном тикете, с заполнением его формы. Это поможет мне правильно понять проблему и дать рабочее решение.
