### ISSUE TITLE
Не сохраняет пароли

### ISSUE THREAD

**Issue by Vill3m** [pozitronik/CloudMailRu#123]
Не сохраняются пароли. Портативная версия ТС может быть тому причиной? Спасибо.

**Comment by pozitronik** [comment]
1. Какое сохранение имеется в виду? В менеджере паролей или в Ini-файле?
2. Приведите пожалуйста информацию, как это описано [здесь](https://github.com/pozitronik/CloudMailRu#Как-и-куда-правильно-жаловаться-на-проблемы).

**Comment by Vill3m** [comment]
Благодарю за быстрый ответ. Версия последняя, Windows 7 x64, TC 8.51a x64. Используется сохранение в менеджере паролей.  А в каких настройках можно посмотреть этот менеджер паролей? Спасибо.
P.S. Щас в ручную добавил пароль в MailRuCloud.ini заработало, но ТС все рано предлагает ввести главный пароль, я его отменяю и продолжается авторизация

**Comment by pozitronik** [comment]
Последняя версия - 9.0a.
Вы так и не описали порядок действий, ожидаемый и полученный результат.

**Comment by Vill3m** [comment]
запуск ТС, запуск плагина ввод пасс\логина, галочка сохранения в менеджере паролей, авторизация, перезапуск ТС. Ожидаемый результат: не требуется ввода пароля, полученный результат: требуется ввода

**Comment by pozitronik** [comment]
В менеджер паролей надо вводить не пароль от учётных записей, а глобальный пароль самого менеджера. Менеджер выступает только хранилищем. После перезапуска (и при некоторых других условиях) менеджер спросит свой пароль, и дальше сохранённые в нём пароли будут доступны прозрачно.

**Comment by Vill3m** [comment]
аа, теперь все стало понятно.  А где можно посмотреть настройки менеджера паролей?

**Comment by pozitronik** [comment]
Насколько я помню, отдельных настроек у него нет, он работает прозрачно. Подробнее можно разобраться, самостоятельно поискав по [форуму](http://forum.wincmd.ru).
Поскольку тема к плагину отношения не имеет, закрываю её.
