### ISSUE TITLE
Проблема Cloud Mail и Gdrive

### ISSUE THREAD

**Issue by MerDenchik** [pozitronik/CloudMailRu#124]
У меня работает либо ваш плагин, либо этот http://wincmd.ru/plugring/gdplugin.html (Гугл драйв). При чём, если я закидываю в корень тотала ваши библиотеки, работает ваш, но не работает гугл, а если гугла, то ваш не работает, а гугл работает... Можете подсказать решение какое-нибудь? Нужно, чтобы оба работали, а то не комильфо.

**Comment by pozitronik** [comment]
Я проверил у себя, и никаких проблем не смог обнаружить. Вероятнее всего, оба плагина используют   ssl-библиотеки, которые могут конфликтовать между собой. Варианты решения здесь могут быть следующие:
1. Включить в CloudMailRu галку Load SSL lilbraries only from plugin directory.
2. Удалить в каталоге GDrive файлы ssleay32.dll/libeay32.dll, либо попробовать заменить их файлами из каталога CloudMailRu.

Возможно, один из вариантов (или их комбинация) решит проблему.

**Comment by MerDenchik** [comment]
Да, помогло, спасибо большое! Видимо, твои библиотеки - лучшие :) 🥇
