### ISSUE TITLE
Leak memory/object BodyVal

### ISSUE THREAD

**Issue by pult** [pozitronik/CloudMailRu#125]
Method in "CloudMailRu.pas": 
function TCloudMailRu.fromJSON_OperationResult(JSON: WideString; var OperationStatus: integer): integer;

Potential leak for BodyVal.  Look/analyze "exit" "except".

Proposal:

```
BodyVal := nil;
try
...
fianlly
  BodyVal.Free;
end;
```

**Comment by pozitronik** [comment]
Thank you, fixed @f1660fc6438cd64ccd5e0b9b79d43743b29203e9
There no need to initialize BodyVal by nil, because TJsonObject make it anyway.

**Comment by pult** [comment]
And if TJsonObject.Create creates an exception (bad json)?
Plus the compiler can issue warning ...

**Comment by pozitronik** [comment]
Yes, you are right, I inattentively checked the TJSONObject.ParseJSONValue method. I'll rewrite this.
