### ISSUE TITLE
tor local proxy - EIdSocketError # 10060 Connection timed out

### ISSUE THREAD

**Issue by pult** [pozitronik/CloudMailRu#126]
EIdSocketError # 10060 Connection timed out

**MailRuCloud.global.ini** 

[Main] 
LoadSSLDLLOnlyFromPluginDir=**1**
PreserveFileTime=0
DescriptionEnabled=0
OperationsViaPublicLinkEnabled=1
AskOnErrors=1
ChunkOverwriteMode=0
DeleteFailOnUploadMode=0
OverwriteLocalMode=0
DisableMultiThreading=0
SocketTimeout=**-1**
ProxyType=**1**
ProxyServer=**127.0.0.1**
ProxyPort=**9150**
ProxyUser=
ProxyPassword=
ProxyTCPwdMngr=0
OperationErrorMode=0
RetryAttempts=1
AttemptWait=1000
LogUserSpace=1
IconsMode=0
DownloadLinksEncode=1
AutoUpdateDownloadListing=1
ShowTrashFolders=1
ShowSharedFolders=1
ShowInvitesFolders=1

**Comment by pozitronik** [comment]
Seems like not a plugin problem. I tried to open my account via tor proxy, and all work as expected.
Is https://cloud.mail.ru page can be accessed via tor connected browser?

Also you must consider, that any network settings change wil be applied only after TC restart.

**Comment by pult** [comment]
Acces success to cloud from tor browser or other browser over tor-proxy. TC restarted after proxy changes. Direct access to cloud is blocked. Maybe on your PC direct access is not blocked. For this test does not issue an error.
The same problem with https proxy:
HTTPS proxy.antizapret.prostovpn.org
https://github.com/anticensorship-russia/generated-pac-scripts/blob/master/anticensority.pac

**Comment by pozitronik** [comment]
>Maybe on your PC direct access is not blocked.

No, i checked that my connection establishes via tor. HTTPS proxy access also work fine, so i can't confirm this issue.
