### ISSUE TITLE
Ограничение в 2Гб

### ISSUE THREAD

**Issue by pozitronik** [pozitronik/CloudMailRu#13]
Нужно проверить, есть ли ограничение на размер одного файла в 2Гб, и можно ли от него избавиться.

**Comment by Tw0l4nd** [comment]
Такое ограничение есть: [скриншот](https://yadi.sk/i/2WfkMPYotvfi4)
Неплохо было бы иметь возможность на лету разбивать на части и на лету собирать воедино при загрузке...

**Comment by codestudioua** [comment]
Даже в официальной программе Cloud Mail.ru на free-аккаунтах такое ограничение есть :(
Очень полезная и нужная функция, но боюсь, что не доступна.
Как вариант — на лету разбивать файлы по 2GB, а в облаке обратно собирать.

**Comment by pozitronik** [comment]
Проверка показала, что ограничение есть, более того - оно было захардкожено ещё при реализации API. Начиная с коммита b3b8f8408bd4fef5715caa2aa91da3a8da1b1f31 клиентская проверка может быть отключена, но проверка на сервере останется.
Нужно ли делать разбитие файлов на лету - не знаю, возможно лучше заранее сделать это в Total Commander.

**Comment by codestudioua** [comment]
Вопрос не в том, что это возможно сделать на клиенте, а в том, чтоб можно было собрать на сервере в единый файл и не задумываться при этом о размере. Также, насколько мне известно с сервера нет возможности скачать больше 2GB. А имея 1ТБ и учитывая, что размеры файлов все время «растут» - опция разбить/собрать была бы очень актуальна.

**Comment by pozitronik** [comment]
Я прекрасно понимаю, о чём меня просят, это ещё обдумывается. Речь шла о других немного вещах.

**Comment by pozitronik** [comment]
Просто идея по алгоритму работы с большими файлами.
- При закачке файлы большого размера разбивать ровно по тому же принципу, как в Total Commander: файлы частей будут иметь имя filename.part_number, рядом с ними будет filename.crc, содержащий оригинальное имя файла, размер, и контрольную сумму. Это позволит добиться совместимости, в случае, если последующая загрузка будет проводиться другим клиентом.
- При работе с ФС облака представлять разбитые файлы as-is (как сейчас), или "виртуализированно" - вместо файловых частей на уровне пользователя будет отображаться исходный файл. При этом придётся писать всю обвязку виртуализации и кучу проверок.
Не знаю, насколько это востребовано.

**Comment by pozitronik** [comment]
Окончательно поправлена заливка больших файлов в коммите commit 4b9a2c5edc1e57d9da9b95190ef75e42d09017c1

**Comment by pozitronik** [comment]
Во время исследований выяснилось, что граница лимита установлена не в двоичных, а в десятичных единицах, т.е. составляет 2000000000 байт, а не 2147483648.

**Comment by pozitronik** [comment]
Done at commit 94783d983ef17a4f57236704f3bde0a5a73964c7

При закачке файлы больше чем 2000000000 байт разбиваются на части ровно по тому же алгоритму, что в Total Commander: файлы частей имеют имя filename.part_number, рядом с ними генерируется filename.crc, содержащий оригинальное имя файла, размер, и контрольную сумму.

Разбитие файла происходит непосредственно перед копированием в подкаталог %temp%, прогресс никак не отображается.
Отмена операции или ошибка в её процессе останавливает заливку, но не удаляет уже залитые части файлов.
