### ISSUE TITLE
[feature request] - Сканирование хеша и моментальное добавление дубликатов 

### ISSUE THREAD

**Issue by Corak667** [pozitronik/CloudMailRu#135]
Привет, в свое время, когда я начал пользоваться официальным клиентом "Облака Mail.Ru" - я заметил одну интересную вещь - у меня был медленный интернет, поэтому хотя скорость загрузки файлов у меня была очень мизерная (около 500кбс), но файлы в 14 гигов загрузились очень быстро (около 15 минут). Я был крайне удивлен, но потом быстро понял "в чем цимез". Подозреваю, что они используют продвинутое хеширование файлов, чтобы случайно не наткнуться на коллизии и сверяют хеши с базой своих уже загруженных кем-то ранее файлов, чтобы не забивать место дубликатами лишний раз и добавляют на твое облако по сути алиас на этот файл, что уже давно залит, вместо того, чтобы загружать его полностью... Также делают многие продвинутые организации типа virustotal.
Есть ли такая функция в открытом api или она реализована исключительно в оф. клиенте? Если есть, возможно ли как-то врубить опцию, чтобы оно сверяло хеши перед загрузкой и добавляло алиасы, чтобы серьезно ускорить загрузку уже давно загруженного и сэкономить время и траффик)

**Comment by pozitronik** [comment]
>Есть ли такая функция в открытом api

Нет.

**Comment by pozitronik** [comment]
Подумалось: добавление файла в облако происходит в два этапа: сначала загрузка на сервер, потом публикация (по хешу, полученному после загрузки). Возможно, сработает попытка публикации именно по хешу - если удастся определить, как этот хеш считается.

**Comment by Corak667** [comment]
Вообще есть нехорошая мысль, что если получится, то это лучше сделать отдельной опцией "сверять хеши дублей перед загрузкой"/"compare duplicate hashes before uploading" и реализовать только для файлов более 1мб, поскольку мелкие файлы в большинстве случаев и так быстро загружаются, а сверка хешей создаст только дополнительную задержку на пару секунд или более...

**Comment by pozitronik** [comment]
Это достаточно очевидно, как и то, что порог проверки тоже надо делать конфигурируемым.

**Comment by pozitronik** [comment]
Попробовал выяснить, какой алгоритм хеширования используется в Облаке для идентификации файлов. Посмотреть хеш достаточно легко - нужно включить контентную колонку hash, значение в ней будет такое же, как у хеша, передаваемого при загрузке. Видно что а) хеши (очевидно, но проверить было нужно) одинаковые для файлов с одинаковым контентом б) длина их - 40 байт. Похоже на SHA-1/MySQL => (SHA-1(SHA-1())). Но простейшие эксперименты это не подтверждают.
Поюс, если hex-представление файла умещается в 40 байт, то оно и будет выступать в роли хеша (с дополнением нулями до 40 байт).
![unicode](https://user-images.githubusercontent.com/2357892/31054386-4498cffe-a6ba-11e7-9f6e-68a2c8f227e9.PNG)
Ни один известный мне алгоритм (впрочем, я не являюсь специалистом в этой области) так не работает. Вероятнее всего, используется какое-то условное ветвление, вроде:

$hash = (HEX(data)<40)?HEX(data):HASH(data)

Некоторые ковыряния в сторону определения алгоритма у меня успехом не увенчались (повторюсь - я не специалист в этой области). Без этого знания, увы, фичу реализовать не получится, хотя она и очень привлекательна.

Хотя можно сделать, например, функцию добавления себе файла по хешу, достаточно бессмысленную, но весёлую. Например, заставить плагин перебирать хеши по порядку, запрашивая у Облака соответствующие файлы, этакая рандомная рыбалка =)

**Comment by pozitronik** [comment]
Если падает последняя сборка - м.б. я что-то напартачил с последними изменениями, релизный бинарник падать не должен, а функционал там по этой части аналогичный.

>Во-первых, мне кажется там 20 байт, а не 40.

Там это где? Хеш у облака - 40, SHA-1 - пять восьмибайтовых последовательностей.

>Во-вторых, для идентификации файлов используются более другие алгоритмы

Вполне допускаю, но это вообще не моя область компетенции, увы. Эти три алгоритма гляну, конечно.

**Comment by areht** [comment]
https://user-images.githubusercontent.com/2357892/31054386-4498cffe-a6ba-11e7-9f6e-68a2c8f227e9.PNG - внизу, 40 символов, 20 байт

**Comment by pozitronik** [comment]
40 ASCII символов = 40 байт.

Или я чего-то недопонял?

**Comment by areht** [comment]
Если там только [0-9A-F], то это не ascii, а hex

**Comment by pozitronik** [comment]
Это строка с hex-представлением, не hex as is.

**Comment by areht** [comment]
Ну ок. Мне показалось, что сопоставление SHA-1, из 160 бит и 40 байт - опечатка. Не знаю что такое hex as is, но не буду спорить.

**Comment by pozitronik** [comment]
Вот тут уже я начал сомневаться =)
При первой возможности проверю на свежую голову, что и как.

**Comment by pozitronik** [comment]
>Мне показалось, что сопоставление SHA-1, из 160 бит и 40 байт - опечатка.

160 бит, только для читаемости записывается результат в виде шестнадцатеричного представления (like **9c32f7d823caab54969997ae0ff59a8dd3744108**), а оно получается вдвое большим.

**Comment by yar229** [comment]
Держите -  [код на C#](https://github.com/yar229/WebDavMailRuCloud/commit/9c9a1f825dfdf9529f791f1e8dc1a511cf61f041)

**Comment by pozitronik** [comment]
Спасибо.
Я не знаком с C#, и могу ошибаться, но разве этот код не отдаёт просто SHA-1 от файла? А по результатам экспериментов, которые я описал выше, SHA-1 не совпадает с тем хешем, что возвращает облако.

**Comment by yar229** [comment]
Нет, если взглянуть внимательнее, то к содержимому файла добавляются префикс и суффикс.
Минимальные эксперименты провёл, таки совпадает

**Comment by pozitronik** [comment]
А можно алгоритм "на пальцах"?

**Comment by yar229** [comment]
Берем хэш от  байты(строка_из("mrCloud")) + содержимое_файла + байты(строка_из(длина_файла))

**Comment by pozitronik** [comment]
Сейчас не могу проверить, как следует, но вот так, на глазок, не должно совпадать. Например, если залить в облако файл, содержащий три символа пробела, то их хеш в облаке будет

> 2020200000000000000000000000000000000000

что явно не совпадёт с тем, что будет в приведённом алгоритме.

**Comment by yar229** [comment]
Да, там выше у вас правильное предположение

@pozitronik 
> Плюс, если hex-представление файла умещается в 40 байт, то оно и будет выступать в роли хеша (с дополнением нулями до 40 байт).

@areht
> там 20 байт, а не 40.

**Comment by yar229** [comment]
Я у вас потырил идею о рыбалке, так, в качестве безумной пасхалки :)

**Comment by pozitronik** [comment]
Базовая реализация в мастере.
В настройках появилось две опции.
**Try to find files by hash in cloud before uploading** отвечает за подсчёт хеша перед закачкой (соответственно, если в облаке есть файл с таким хешем, то он будет добавлен без закачки).
**Check downloads CRC** отвечает за проверку хеша у скачанных файлов, что предотвращает получение битых данных.

Фичи ещё не до конца протестированы, но вроде работают.

**Comment by areht** [comment]
> Check downloads CRC 

А что на счёт uploads?

**Comment by pozitronik** [comment]
> А что насчёт uploads?

Хорошая идея, добавил - включается той же галочкой. Потестируйте, плз, на сообщения об ошибках при включённой проверке можно не обращать внимания, это поправлю потом.

**Comment by Corak667** [comment]
Супер, спасибо огромное! Проверил, файл на 280мб залился 5 секунд :D То ради чего собствнно эта фишка и была задумана)

**Comment by Corak667** [comment]
И да,  еще момент, наверное не стоит лишний раз сверять хеш когда копируешь с облака на локальный диск, поскольку тут не может быть обратной связи... Просто заметил небольшую задержу.. Или оно не связано?

**Comment by pozitronik** [comment]
> И да, еще момент, наверное не стоит лишний раз сверять хеш когда копируешь с облака на локальный диск

За это отвечает галка **Check uploads\downloads CRC** в настройках. Обратная связь там есть: мы знаем хеш в облаке, и можем посчитать хеш скопированного файла, если они не совпадают - значит файл побился при передаче (на плохом вайфае такое у меня регулярно случается).

**Comment by pozitronik** [comment]
+ При поиске файлов по хешу ошибки игнорируются.
+ Если файл найден по хешу, выводится сообщение в лог.

**Comment by areht** [comment]
А при синхронизации средствами TC проверка CRC используется? В обе стороны?

**Comment by Corak667** [comment]
>Хотя можно сделать, например, функцию добавления себе файла по хешу, достаточно бессмысленную, но весёлую. >Например, заставить плагин перебирать хеши по порядку, запрашивая у Облака соответствующие файлы, этакая рандомная рыбалка =)

У меня возникла безумная идея - может таки реализовать безумную рыбалку и все удачные экземпляры сливать в каталог. 
Для чего - да чтобы вернуть удаленный или похеренный файл. Понятное дело там могут лежать открыто личные данные чьи-то, но это пофиг, главное что сама идея реализуема. 
И потом для такого  можно будет добавить команду "кастовать", чтобы призвать какой-то файл по хешу
cast 9c32f7d823caab54969997ae0ff59a8dd3744108
Или для той же Экономии места на диске. Всеравно все хешированное никуда не удалится, а сохранится на их серваках и будет пылится веками. Например создать файл-лист где файлы по 1-2 гига.  слить туда список файлов и хешей, потом командой 
cast filelist.txt - вернуть их на место по хешу. Норм?

**Comment by pozitronik** [comment]
Функция выдачи файла требует не только хеш, вычисляемый по содержимому, но и размер файла. Эти величины никак не связаны. Поэтому ни последовательный перебор, ни случайный подбор тут не применимы, функция бессмысленна.

**Comment by Corak667** [comment]
Так, ок, значит "безумную рыбалку" придется отменить, а жаль. Ну ладно
НО остается идея использовать метод выдачи файла для экономии. Можно сгенерить лист файлов с размерами и хешами и выдавать по нему. Значит примерно так, нормально? 
cast filename.dat 9c32f7d823caab54969997ae0ff59a8dd3744108 1053003
cast @filelist.txt

(И конечно надо проверить сколько времени они хранят данные после полного удаления, если недолго, то и это лишено смысла).

**Comment by Corak667** [comment]
re: все-таки мысль про "безумную рыбалку" снова возникла. может запилить клиент, который аналогично всяким криптовалютам и майнерам - брутфорсил по КАЖДОМУ размеру. Авто-создать например директорию с названием 1 - и долбать все возможные хеши и варианты и так до вменяемых размеров перебором устраивать рыбалку :D
