### ISSUE TITLE
Freshly cloned project build failure in Delphi 10 Seattle

### ISSUE THREAD

**Issue by ashumkin** [pozitronik/CloudMailRu#138]
- [x] I was not able to find an [open](https://github.com/pozitronik/CloudMailRu/issues?q=is%3Aopen) or [closed](https://github.com/pozitronik/CloudMailRu/issues?q=is%3Aclosed) issue matching what I'm seeing/Я не нашёл [открытых](https://github.com/pozitronik/CloudMailRu/issues?q=is%3Aopen) или [закрытых](https://github.com/pozitronik/CloudMailRu/issues?q=is%3Aclosed) тикетов, описывающих мой запрос.
- [x] I have read project [documentation](https://github.com/pozitronik/CloudMailRu/blob/master/README.MD), including the Frequently Asked Questions section/Я прочёл [документацию](https://github.com/pozitronik/CloudMailRu/blob/master/README.MD), включая раздел FAQ.

### Configuration

- Which version of Windows are you running? XP, Vista, 7, 8, 10? Is it 32-bit or 64-bit?

Windows 7 32 bit 

- Which version of Total Commander are you using? Is it 32-bit or 64-bit?

Not applicable

- Which plugin version are you using? Stable release, last master build, other?

**master** branch
```
commit 32e655983f5bf155f568f10addb4219cdb652bfd
Author: Pavel Dubrovsky <antikillerxxl@gmail.com>
Date:   Tue Oct 3 19:40:58 2017 +0300

    unused

```

- Any other interesting things about your environment that might be related to the issue you're seeing?

Delphi 10 Seattle Architect edition

### Problem details

- Describe actions sequence leading to the problem.

1. Clone project (fresh copy)
2. Open MailRuCloud.dpr in Delphi 10 Seattle IDE.
3. Build project (Ctrl+F9)

- What did you expect to occur after running these actions?
 
Project compilation succeeds.

- What actually happened instead?

Build fails with the "_[dcc32 Error] E1026 File not found: 'MailRuCloud.dres'_" error

The reason is that there is no **MailRuCloud.dproj** file in the repository. **MailRuCloud.dproj** is actually the MSBuild script to build the project which Delphi "internally" uses.

**Comment by pozitronik** [comment]
Спасибо. Я привык со времён D7, что всё, что генерируется при сборке для распространения не нужно.
Странно, что эту проблему я как-то пропустил, хотя собирал код из репы минимум на двух машинах.

**Comment by ashumkin** [comment]
ну, .dproj как раз не генерируется **при сборке**, он создаётся раз, если его не было, при открытии .dpr-файла.
И это основной файл, который использует сама Delphi (по сути, запуская MSBuild) для сборки. В нём описаны сценарии сборки: какие ресурсы в каком порядке компилировать, какие файлы класть в APK (для Android-приложений), etc.

**Comment by pozitronik** [comment]
>ну, .dproj как раз не генерируется при сборке, он создаётся раз, если его не было, при открытии .dpr-файла.

Да, и к файлам генерируемым при открытии я относился примерно так же - "какая-то служебная хрень". Почему-то даже мысли не появлялось о том, чтобы вникнуть.
Спасибо за информацию, плюсанул на хабре за помощь.
