### ISSUE TITLE
Покрытие тестами

### ISSUE THREAD

**Issue by pozitronik** [pozitronik/CloudMailRu#140]
Я не умею писать тесты. Надо научиться, разобраться, можно ли и нужно ли в принципе этот код ими покрывать, или оно не стоит того.

**Comment by ashumkin** [comment]
[тут](https://github.com/TurboPack-Seattle/LockBox3) (каталог test - dUnit-тесты) можно посмотреть (правда, для неопытного глаза - непонятно)
 (кстати, это "_TurboPower LockBox 3 is a FOSS Delphi Cryptographic Library, providing efficient private key encryption, public key encryption and hashing functions._" AES там тоже есть. К слову о AES - есть ещё - в самом OpenSSL (https://stackoverflow.com/questions/9723963/delphi-pascal-example-for-calling-openssl-evp-functions) (https://github.com/lminuti/Delphi-OpenSSL)

**Comment by ashumkin** [comment]
+ http://docwiki.embarcadero.com/RADStudio/Tokyo/en/DUnit_Overview

**Comment by pozitronik** [comment]
Оно того не стоит.
