### ISSUE TITLE
Please, consider following Object Pascal style guide

### ISSUE THREAD

**Issue by ashumkin** [pozitronik/CloudMailRu#141]
It is difficult to read, debug and makes it _impossible_ to contribute to the code which style is custom.
I'm not about naming conventions but [code formatting](http://docwiki.embarcadero.com/RADStudio/Tokyo/en/Formatting_Source_Code) at least.
E.g.
`if CheckFlag(FS_COPYFLAGS_MOVE, CopyFlags) then Result := DeleteLocalFile(LocalName);`

Such a code is difficult to debug when you want set a breakbpoint to the `Result := DeleteLocalFile(LocalName)` statement only. You set a breakpoint on a whole line but not a _true_ statement. So, debugger will stop every time on this line but not when a condition is true.

Also, this code is hard to read as a reader usually "reads a line beginning but not to an ending".

Also, long lines does not fit the screen when one looks `git diff` output.

Nota bene. Delphi IDE has Ctrl+D shortcut and the [Formatter command line tool](http://docwiki.embarcadero.com/RADStudio/Tokyo/en/Formatter.EXE,_the_Command_Line_Formatter) to simplify developer's life.

P.S. [Object Pascal style guide](https://edn.embarcadero.com/article/10280)

**Comment by pozitronik** [comment]
Это привычка со времён работы на VGA-дисплее - форматировать код так, чтобы как можно больше строк логики отображалось на экране. Я вполне понимаю, что привычка сейчас себя исчерпала, и посмотрю, что с этим можно сделать.
Ctrl+D знаю и использую.

**Comment by pozitronik** [comment]
Изменил форматирование для подобных случаев, однако полностью стайлгайд применять я не хочу. Мне, например, крайне не нравится "корректный" вариант, в котором end else begin разносятся на три строки.
