### ISSUE TITLE
Шифрование файлов

### ISSUE THREAD

**Issue by SchwarzKopf-M** [pozitronik/CloudMailRu#142]
Скачал последнюю версию плагина с шифрованием файлов. Вещь полезная, но... Файлы в облако копируются и шифруются, но вот обратно не копируются.
Вынь7х64, ТС9.0ах64

Дополнительно.
Заметил что из корзины нельзя удалить файлы, пишет "Нет доступа или файл уже используется", это нормально?

**Comment by pozitronik** [comment]
Обсуждение шифрования в issue #5. Вероятнее всего, проблема с шифрованием имён файлов, там обнаружились значительные недоработки. Выключите эту опцию, попробуйте работать только с шифрованием файлов, если будет проблемы - пишите в вышеуказанном тикете.

>Дополнительно.

На одну проблему по одному тикету, если проблемы, конечно, не связаны. В любом случае, информации недостаточно, как минимум приведите (в новом тикете) данные, которые предлагается указать при создании issue.
