### ISSUE TITLE
Прозрачное разбиение файлов на части по 2G

### ISSUE THREAD

**Issue by vasyutin** [pozitronik/CloudMailRu#143]
Хорошо бы сделать прозрачное для пользователя разбиение больших файлов на части. Чтобы при записи в облако файл разбивался на части автоматически (что уже есть), но в списке файлов в панели TC эти части показывались как один файл с оригинальным размером. Соответственно при чтении этого файла из облака все части автоматически сливались обратно в один файл оригинального размера.

В реализации у файла можно сохранять расширение, а к номеру части можно добавлять префикс, зарезервированный за подобными разбитыми на части файлами. Например,

Оригинал: 
some-file.mkv

Разбитые файлы:
some-file.mkv.pozit001
some-file.mkv.pozit002
some-file.mkv.pozit003

**Comment by pozitronik** [comment]
Это есть больше года как: Issue #13.
