### ISSUE TITLE
Удаление файла из корзины

### ISSUE THREAD

**Issue by SchwarzKopf-M** [pozitronik/CloudMailRu#144]
В корзине имеющиеся там файлы можно удалить при помощи очистки всей корзины, но отдельно один файл нельзя удалить по нажатию F8. Пишет "Нет доступа или файл уже используется", это нормально? Если не нормально, то хорошо-бы сделать чтобы можно было удалить файлы по отдельности.
ТС последний как х86 так и х64, плагин последний, ОС 7х64.

**Comment by pozitronik** [comment]
Это корректное поведение. WebAPI не умеет удалять один файл из корзины. Можете проверить в браузере - там всё аналогично.
