### ISSUE TITLE
Проблема с шифрованием

### ISSUE THREAD

**Issue by zagnuteg** [pozitronik/CloudMailRu#147]
Windows 10 64-bit
TC 64-bit
Last Master

Установил плагин, добавил аккаунт (шифрование выключено), загрузил файлы, попытался просмотреть, не читаются. У файлов сохранился прежний объем и имена. Однако, похоже, они зашифрованы. Такое происходит со всеми типами файлов. 

Прикрепляю два изображения. Одно - до загрузки через плагин, второе - после скачки. Подчеркиваю, шифрование в настройках плагина выключено.

![plugin_uploaded](https://user-images.githubusercontent.com/33620425/32717440-b0f0c9f0-c86a-11e7-9354-49f548841be5.png)
![plugin](https://user-images.githubusercontent.com/33620425/32717441-b10be276-c86a-11e7-8711-0dc74383094a.png)

**Comment by pozitronik** [comment]
В первой ссылке пустая картинка, вторая картинка - вообще мой скриншот.
Мастер в разработке, там встречаются баги. Вы, скорее всего, попали [вот на это](https://github.com/pozitronik/CloudMailRu/commit/f22add096b213f127544fb907f46702f0b42067d) (настройка шифрования инвертировалась).

**Comment by zagnuteg** [comment]
[CloudMailRu-master.zip](https://github.com/pozitronik/CloudMailRu/files/1466186/CloudMailRu-master.zip)
В том то и дело, что это не пустая картинка. Повторно прикрепил архивом. Взял вашу картинку, ибо была под руками.

**Comment by pozitronik** [comment]
Я ждал скриншот. Но, в общем, разницы нет. Шифруется из-за бага в сборке, откатитесь на последний релиз, а бинарники я сейчас обновлю (по крайней мере этого бага там уже не будет).

**Comment by zagnuteg** [comment]
Проверил CloudMailRu.pas там всё корректно. Версия актуальная, скачал 10 минут назад. В итоге, файлы, которые были залиты с помощью этой версии - безвозвратно утеряны?

**Comment by pozitronik** [comment]
> Проверил CloudMailRu.pas там всё корректно. Версия актуальная, скачал 10 минут назад.

Бинарники собираются не на каждый коммит, поэтому в текущем коде всё корректно, а в сборке ещё нет.

> В итоге, файлы, которые были залиты с помощью этой версии - безвозвратно утеряны?

Какой-то пароль устанавливали? Если да - то нужно:
1. Взять текущие бинарники (только что обновил).
2. Поставить галку шифрования (но не ставить галку для имён).
3. Попробовать скачать файлы. Если спросит пароль - ввести прежний, если нет - значит пароль сохранялся в TC, и плагин его подхватит.

А вот если никакого пароля никогда не ставилось - тогда вопрос (по идее, шифрование тогда вообще не должно было работать).

**Comment by zagnuteg** [comment]
В том то и дело, что пароль на шифрование не устанавливался. Попробую обновленный.

**Comment by zagnuteg** [comment]
На последней версии TC всё запустилось и загрузка работает, но файлы, которые были загружены предыдущей версией БЕЗ шифрования  - не читаются никак.

**Comment by pozitronik** [comment]
Я проверил на сбойной версии, судя по всему файлы шифровались пустым паролем (это допускалось). Соответственно, рашифровалось тоже пустым паролем.
Текущая версия плагина такого фокуса уже не допускает, но если надо восстановить данные - дайте ссылку на них, я расшифрую. Или могу прислать сборку плагина, в которой это можно сделать.

**Comment by zagnuteg** [comment]
Если можно, сборку. Файлов достаточно много. Спасибо

**Comment by pozitronik** [comment]
1. Берёте нужный бинарник [здесь](https://github.com/pozitronik/CloudMailRu/tree/restore)
2. Меняете им текущий установленный бинарник.
3. В настройках аккаунта выключаете шифрование файлов (если было включено).
4. Перезапускаете TC.
5. Скачиваете файлы.

Лучше, конечно, проверить сначала на одном файле.

**Comment by zagnuteg** [comment]
Отлично. Проверил. Сработало. Спасибо огромное!

**Comment by pozitronik** [comment]
Вот и отлично.

**Comment by pozitronik** [comment]
Не забудьте потом откатиться на последний стабильный релиз, на всякий случай.
