### ISSUE TITLE
Ошибка "Exception in MailRuCloud.wfx:FsPutFileW!" (External exception EEDFADE) во время загрузки файла

### ISSUE THREAD

**Issue by Corak667** [pozitronik/CloudMailRu#148]
Вообщем разок сейчас столкнулся с ошибкой во время загрузки файла, выдало такое окно:
http://picsee.net/upload/2017-11-17/9e9eb893b828.png
![9e9eb893b828](https://user-images.githubusercontent.com/7928889/32947092-46d63264-cbab-11e7-8ad2-ccce35e9237d.png)

```
---------------------------
Total Commander 9.10RC2
---------------------------
Exception in MailRuCloud.wfx:FsPutFileW!
External exception EEDFADE
Windows XP SP3 5.1 (Build 2600), base: 00400000

Please report this error to the Author, with a description
of what you were doing when this error occurred!

Windows exception: 0EEDFADE
Stack trace:
027E659F

Raw:
00560068  00560068  00402249  00403414  004021C8  00402249
00403414  004021C8  >0041CA05  00402249  00403414  004021C8
0041803C  00417CC9  0041809C  004194C4  00403670  

```

**Comment by Corak667** [comment]
Ах да, дубликат, пардон
https://github.com/pozitronik/CloudMailRu/issues/61#issue-187528636

**Comment by pozitronik** [comment]
> Please report this error to the Author, with a description
> of what you were doing when this error occurred!

![image](https://user-images.githubusercontent.com/2357892/32947189-ae1895a2-cbab-11e7-9386-16406a4f4277.png)
