### ISSUE TITLE
Снять блокирование нажатия на кнопку ESC на окне свойств ссылки

### ISSUE THREAD

**Issue by Corak667** [pozitronik/CloudMailRu#149]
Привет, год назад я писал насчет того, кнопка ESC срабатывала глобально в любом случае - при нажатии, когда я просматривал текстовик с паролями и копипастил в менеджер аккаунтов, а потом закрывал текстовик по ESC - закрывалось и само окно ввода пароля в аккаунт - это очень бесило... Ты тогда реализовал ГЛОБАЛЬНОЕ блокирование ESC кнопки, когда открыт менеджер аккаунтов (так что кнопка ESC вообще блокировалась на других прилогах тоже) :D 
Теперь другая проблема - судя по всему ты решил проблему глобального нажатия и все работает как надо в менеджере акков, но аналогичное "решение проблемы" осталось еще при открытии окна свойств ссылок (где можно генерить ссыли). Там до сих пор ESC блокируется и невозможно закрыть его по esc - а закрывать это было бы очень кстати) Или у тебя были какие-то свои интерфейсные предпочтения по этому поводу?
http://picsee.net/upload/2017-11-20/2d7eb78cb611.png

**Comment by Corak667** [comment]
Пардон, В последнем билде нормально

**Comment by pozitronik** [comment]
Хорошо, что зарепортил, в других диалогах тоже нужно поправить.

**Comment by Corak667** [comment]
Проверил сейчас раз - на XP еще блокируется ESC в окнах свойств ссылок. В аккаунт менеджере нормально. А 7рке работает ESC в обоих случаях.
Возможно это починить?

**Comment by pozitronik** [comment]
Не могу воспроизвести. На XP, Win7 и Win 10 - нажатие Esc в окне свойств ссылок работает одинаково.

**Comment by Corak667** [comment]
Хм, у меня на XP не работает. Как продебажить? Ставить какую-нибудь IDE? Могу дать доступ по TeamViewer в любой момент.

**Comment by pozitronik** [comment]
XP какая (32/64), какой TC и какая версия плагина?

**Comment by Corak667** [comment]
32
версия плагина текущая (1.0.6086.0): https://i.imgur.com/a4psdmE.png

**Comment by pozitronik** [comment]
Текущая - это из мастера? Цифры версии берутся хз, откуда, я не помню, чтобы что-то тут настраивал.
Дебажить нечего, [тут всё чётко](https://github.com/pozitronik/CloudMailRu/blob/master/RemoteProperty.pas#L438): если окно в фокусе, и нажата Esc - окно закрывается. Тот же самый код [используется](https://github.com/pozitronik/CloudMailRu/blob/master/Accounts.pas#L439) в окне свойств.

**Comment by Corak667** [comment]
Да, из мастера. Сегодняшний билд

**Comment by pozitronik** [comment]
Проверил на XP32 (до этого проверял на 64), проблема воспроизводится, что довольно странно.

**Comment by pozitronik** [comment]
Fixed (issue #154).

**Comment by Corak667** [comment]
Проверил, подтверждаю, все работает!)

**Comment by Corak667** [comment]
+ есть еще пару нюансов насчет работы окон свойств, не критичны, но конечно же напрягают:
1. Они принудительно поверх всех окон (включая другие процессы). Хотелось бы снять этот параметр. 
Например, в случае если нужно сохранить список временных прямых линков - окно сохранения - тоже ниже приоритетом и нельзя толком его увидеть.
2. При открытом окне свойств (аккаунты или ссылки) - ESC блокируется на всех других приложениях кроме Total Commander.

**Comment by pozitronik** [comment]
В новый тикет, плз, посмотрю по возможности.
