### ISSUE TITLE
получение одноразовой прямой сылки

### ISSUE THREAD

**Issue by beqabeqa473** [pozitronik/CloudMailRu#15]
здравствуйте.

сделайте пожалуйста опцию получения одноразовой прямой сылки. для этого есть api вызов.

**Comment by pozitronik** [comment]
А подскажите, какой это вызов? Я только file/publish знаю, но он не одноразовый.

**Comment by beqabeqa473** [comment]
здравствуйте.

есть библиотека, в которой этот метод реализован, называется getDirectLink

вот сам код этой библиотеки

https://github.com/erastmorgan/Mail.Ru-.net-cloud-client

**Comment by stayathome** [comment]
@pozitronik гляньте, там пишут еще и про отсутсвие ограничения:

> Upload and Download operations supports progress change event and can work with large file more than 2Gb.

**Comment by pozitronik** [comment]
Да, на гиктаймсе тоже про это упоминали, буду разбираться.

**Comment by beqabeqa473** [comment]
да, там файл разбивается или чтото типа того

On 8/2/16, Pavel Dubrovsky <notifications@github.com> wrote:
> Да, на гиктаймсе тоже про это упоминали, буду разбираться.
>
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/pozitronik/CloudMailRu/issues/15#issuecomment-236848336


-- 
with best regards beqa

**Comment by pozitronik** [comment]
В api нет (или я не нашёл) метода получения именно одноразовой ссылки. В [Mail.Ru-.net-cloud-client](https://github.com/erastmorgan/Mail.Ru-.net-cloud-client) нет метода getDirectLink, есть только получение обычной ссылки в GetPublishDirectLink.
Что касается "отсутсвия ограничения" - в [Mail.Ru-.net-cloud-client](https://github.com/erastmorgan/Mail.Ru-.net-cloud-client) оно сделано разбивкой на части, это уже в issue #13
