### ISSUE TITLE
Ошибка при попытка загрузить файл на облако, если файл где-то используется.

### ISSUE THREAD

**Issue by Corak667** [pozitronik/CloudMailRu#150]
Ситуация такая - если файл линкован, например загружается в каком-то браузере на какой-то сайт, то при попытке одновременно еще загрузить его на облако через плагин, вылезает ошибка "Ошибка при закачке"
http://picsee.net/upload/2017-11-20/bb4a2e3da4d6.png
![bb4a2e3da4d6](https://user-images.githubusercontent.com/7928889/33000901-bcb0d068-cdbb-11e7-8edf-e20c36ca3d83.png)

**Comment by pozitronik** [comment]
Не ошибка плагина. Загружаемый файл открывается в режиме [fmOpenRead or fmShareDenyWrite](https://github.com/pozitronik/CloudMailRu/blob/master/CloudMailRu.pas#L1092), соответственно ошибка будет в сучае, если файл недоступен на чение. Если его заблокировало другое приложение - плагин ничего с этим сделать не может и не должен.

**Comment by Corak667** [comment]
Странно, файл доступен как раз на чтение (просмотр текстовый), по крайней мере его можно было просмотреть спокойно и копировать его на любой другой локальный диск...  А вот почему-то копирование на Облако - не удается. Кстати та ошибка (https://github.com/pozitronik/CloudMailRu/issues/148)
Именно тогда и возникает.

**Comment by pozitronik** [comment]
Пошаговый порядок действий, приводящий к ситуации?

**Comment by Corak667** [comment]
1. Взять какой-нибудь 7z архив весом до 200мб например
2. Попытаться залить его в доксы vk (https://vk.com/docs), чтобы браузер присвоил ему системные статсы ReadOnly
3. В то же время попытаться этот же файл на свое облако в майлру через плагин.

**Comment by pozitronik** [comment]
Каким браузером идёт закачка?

**Comment by Corak667** [comment]
Opera (blink/chromium)

**Comment by pozitronik** [comment]
Исправлено. Проблема воспроизводилась при включении проверки CRC: процедура подсчёта хеша открывала файл без fmShareDenyWrite.
Просьба проверить на последней сборке.

**Comment by Corak667** [comment]
Проверил, исправлено, все качается теперь одновременно)
Спасибо огромное!)

**Comment by Corak667** [comment]
+ Обнаружилась еще одна ситуация. где проявляется данный баг.
Вообщем если пытаться копировать группу файлов с проверкой на хеш. Затем переименовать/переместить один из файлов (который отмечен в очереди на копирование) - он файл естественно не найдет и выдаст еще вот этот краш:
https://i.imgur.com/QC747fd.png
