### ISSUE TITLE
Не могу подлючится через Proxy

### ISSUE THREAD

**Issue by DesignStudio** [pozitronik/CloudMailRu#152]
[Ошибка](http://take.ms/OoglW). Win 10 x64, TC 8.52a х32 х64 (обе пробовал поочередно, разрядность плагина менял), плагин 14052017 х32 х64. Использовал прокси (без него сейчас с Украины не зайти), возможно ошибка из за него. Хотя отдельно чекал — работал.

**Comment by pozitronik** [comment]
Прописать тот же прокси в браузере, проверить соединение. Если работает - проверить идентичность настроек прокси в плагине.
После изменения настроек желательно перезапускать TC.
