### ISSUE TITLE
Ошибка "Exception in MailRuCloud.wfx:FsPutFileW!" (External exception EEDFADE), если переместить/переименовать один из файлов в очереди на загрузку на облако (в режиме проверки хешей).

### ISSUE THREAD

**Issue by Corak667** [pozitronik/CloudMailRu#153]
Обнаружилась еще одна ситуация. где проявляется данный баг.
Вообщем если пытаться копировать группу файлов с проверкой на хеш. Затем переименовать/переместить один из файлов (который отмечен в очереди на копирование) - он файл естественно не найдет и выдаст еще вот этот краш:
https://i.imgur.com/QC747fd.png
![qc747fd 1](https://user-images.githubusercontent.com/7928889/33350181-85b817de-d4ae-11e7-83b7-efd65b48d06e.png)

**Comment by Corak667** [comment]
re: https://github.com/pozitronik/CloudMailRu/issues/150
re: https://github.com/pozitronik/CloudMailRu/issues/148

**Comment by pozitronik** [comment]
Исправлено.
К тикетам 148 и 150 это не имеет отношения. Баг выглядит идентично, но источник у него иной.
