### ISSUE TITLE
Лимит скорости

### ISSUE THREAD

**Issue by Lisabon** [pozitronik/CloudMailRu#155]
Хотелось бы добавить в плагин, функцию "Лимит скорости".

**Comment by Lisabon** [comment]
Если возможно, то хотелось бы, чтобы плагине опция лимита скорости измерялась в процентном соотношении от 0% до 100%. Плагин перед заливкой файла и во время заливки (можно сделать опцию, как часто производить тестирование канала на скорость. Допустим, через сколько секунд производить тест скорости. Например, 0-постоянно, 30-каждые 30 секунд и т.д.), тестировал канал на скорость и в зависимости от выставленного лимита, плагин ограничивал скорость заливки файла. Предположим, что лимит скорости выставлен 50% и соответственно, если скорость канала изменяется в промежутке времени, то и скорость заливки будет меняться(подстраиваться) под лимит скорости 50%.

**Comment by pozitronik** [comment]
Нет, так не получится.
Я попробую сделать потолочные ограничения, но не более того.

**Comment by pozitronik** [comment]
Сделано, проверьте. Лимиты выставляются в BPS, отдельно для **каждой** скачки/закачки (не суммарно на плагин).

**Comment by Lisabon** [comment]
Погонял плагин с лимитами... Проблем не обнаружил, лимит работает, как заданно в настройках. Спасибо.
