### ISSUE TITLE
Игнорирование промежуточного сертификата

### ISSUE THREAD

**Issue by BorisNA** [pozitronik/CloudMailRu#157]
- Plugin 
   a) старая версия, номер восстановить не могу (размер 3172864 от 29.08.2016, md5 6f6bb4823fd7b64ddf09c228f57ea163)
   b) новая версия 14052017
- Конфигурация. Win7Pro/32bit. TC 8.51a. Сеть за прозрачным proxy Checkpoint c инспекцией https (переписывание сертификатов). Сертификат установлен в доверенные в системе.
- Браузеры работают, cloud plugin от ghisler работает (1.10), webdav плагин работает.

При попытке загрузить или скачать выдаёт ошибку 10054.
Да, подобное сообщение видел. Но. Старая версия авторизуется (см. ниже), новая - уже нет. Другие плагины ТС работают. Т.е. дело не совсем (или не только) в блокировании соединения на уровне системы.

Симптомы
   а) Старая версия. Авторизуется корректно, заходит в облако. Можно ходить по папкам и т.п. При попытке скачать или загрузить файл выдаёт
```
CONNECT []@mail.ru
Login to []@mail.ru
Requesting auth token for []@mail.ru
Connected to []@mail.ru
Total space: 1Tb, used: []Gb, free: []Gb.
Current shard is undefined, trying to get one
Current shard: https://cloclo4.datacloudmail.ru/get/
EIdSocketError ошибка с сообщением: Socket Error # 10054
Connection reset by peer. при копировании файла с адреса EIdSocketError ошибка с сообщением: Socket Error # 10054
Connection reset by peer. при копировании файла с адреса https://cloclo4.datacloudmail.ru/get/%D0%91%D0%B5%D1%80%D0%B5%D0%B3.jpg
```
   б) Новая версия. Уже не может даже авторизоваться 
```
CONNECT \[]
Login to []@mail.ru
Requesting auth token for []@mail.ru
EIdSocketError ошибка с сообщением: Socket Error # 10054
Connection reset by peer. при отправке данных на адрес https://auth.mail.ru/cgi-bin/auth?from=splash
error: getting auth token for []@mail.ru


```

UPD. У меня есть предположение, что где-то во флагах SSL стоит строгая проверка сертификата. Если как-то можно получить отладочную информацию, я мог бы посмотреть, что и где возвращается. VS и т.п. установить не смогу скорее всего, но, может быть, какая-нибудь сборка с расширенным логгингом?

Или вообще какие-то опции, типа sslvSSLv2/sslvSSLv23 и т.п.

**Comment by BorisNA** [comment]
Что-то явно поменялось в механизме авторизации. Если понять что, то будет понятно, что и на каком уровне блокирует соединение в плагине.

**Comment by BorisNA** [comment]
Когда пытаешься загрузить файл в TC procmon вот что показывает
```
0	14:05:11,1689180	TOTALCMD.EXE	10024	TCP Connect	[***].com:62633 -> cloclo42-2.i.mail.ru:https	SUCCESS	Length: 0, mss: 1460, sackopt: 1, tsopt: 0, wsopt: 1, rcvwin: 65700, rcvwinscale: 8, sndwinscale: 3, seqnum: 0, connid: 0
1	14:05:11,1700270	TOTALCMD.EXE	10024	TCP Send	[***].com:62633 -> cloclo42-2.i.mail.ru:https	SUCCESS	Length: 215, startime: 14663181, endtime: 14663182, seqnum: 0, connid: 0
2	14:05:11,1761521	TOTALCMD.EXE	10024	TCP Receive	[***].com:62633 -> cloclo42-2.i.mail.ru:https	SUCCESS	Length: 0, seqnum: 0, connid: 0
3	14:05:11,1763353	TOTALCMD.EXE	10024	TCP Disconnect	[***].com:62633 -> cloclo42-2.i.mail.ru:https	SUCCESS	Length: 0, seqnum: 0, connid: 0

```

Из браузера же по-другому. Другой размер пакета и другой сервер. Не знаю, насколько это важно

Сначала происходит соединение на просто cloud.mail.ru (повторный запрос токена?)
```
0	14:10:56,6556032	chrome.exe	7236	TCP Connect	[***].com:62719 -> cloud.mail.ru:https	SUCCESS	Length: 0, mss: 1460, sackopt: 1, tsopt: 0, wsopt: 1, rcvwin: 65700, rcvwinscale: 8, sndwinscale: 3, seqnum: 0, connid: 0
1	14:10:56,6598624	chrome.exe	7236	TCP Send	[***].com:62719 -> cloud.mail.ru:https	SUCCESS	Length: 517, startime: 14666636, endtime: 14666636, seqnum: 0, connid: 0
2	14:10:56,6673263	chrome.exe	7236	TCP Receive	[***].com:62719 -> cloud.mail.ru:https	SUCCESS	Length: 1460, seqnum: 0, connid: 0
3	14:10:56,6674610	chrome.exe	7236	TCP Receive	[***].com:62719 -> cloud.mail.ru:https	SUCCESS	Length: 1460, seqnum: 0, connid: 0
4	14:10:56,6675276	chrome.exe	7236	TCP Receive	[***].com:62719 -> cloud.mail.ru:https	SUCCESS	Length: 264, seqnum: 0, connid: 0
5	14:10:56,6773567	chrome.exe	7236	TCP Send	[***].com:62719 -> cloud.mail.ru:https	SUCCESS	Length: 126, startime: 14666636, endtime: 14666636, seqnum: 0, connid: 0
6	14:10:56,6831033	chrome.exe	7236	TCP Receive	[***].com:62719 -> cloud.mail.ru:https	SUCCESS	Length: 258, seqnum: 0, connid: 0
7	14:10:56,7016875	chrome.exe	7236	TCP Send	[***].com:62719 -> cloud.mail.ru:https	SUCCESS	Length: 1529, startime: 14666637, endtime: 14666637, seqnum: 0, connid: 0
8	14:10:56,7303949	chrome.exe	7236	TCP Receive	[***].com:62719 -> cloud.mail.ru:https	SUCCESS	Length: 1460, seqnum: 0, connid: 0
9	14:10:56,7304480	chrome.exe	7236	TCP Receive	[***].com:62719 -> cloud.mail.ru:https	SUCCESS	Length: 743, seqnum: 0, connid: 0

```

А потом уже запрос на cloclo со сдвоенным коннектом и другим размером пакета (517 против 215).
```
10	14:10:56,9858217	chrome.exe	7236	TCP Connect	[***].com:62721 -> cloclo39.i.mail.ru:https	SUCCESS	Length: 0, mss: 1460, sackopt: 1, tsopt: 0, wsopt: 1, rcvwin: 65700, rcvwinscale: 8, sndwinscale: 3, seqnum: 0, connid: 0
11	14:10:56,9861085	chrome.exe	7236	TCP Connect	[***].com:62722 -> cloclo39.i.mail.ru:https	SUCCESS	Length: 0, mss: 1460, sackopt: 1, tsopt: 0, wsopt: 1, rcvwin: 65700, rcvwinscale: 8, sndwinscale: 3, seqnum: 0, connid: 0
12	14:10:56,9867745	chrome.exe	7236	TCP Send	[***].com:62721 -> cloclo39.i.mail.ru:https	SUCCESS	Length: 517, startime: 14666639, endtime: 14666639, seqnum: 0, connid: 0
13	14:10:56,9872214	chrome.exe	7236	TCP Send	[***].com:62722 -> cloclo39.i.mail.ru:https	SUCCESS	Length: 517, startime: 14666639, endtime: 14666639, seqnum: 0, connid: 0
14	14:10:56,9929850	chrome.exe	7236	TCP Receive	[***].com:62722 -> cloclo39.i.mail.ru:https	SUCCESS	Length: 1460, seqnum: 0, connid: 0
15	14:10:56,9931228	chrome.exe	7236	TCP Receive	[***]..com:62722 -> cloclo39.i.mail.ru:https	SUCCESS	Length: 1460, seqnum: 0, connid: 0

```

**Comment by pozitronik** [comment]
В версии от 29.08.16 при авторизации использовался [HTTP](https://github.com/pozitronik/CloudMailRu/blob/69d85121e64e5a9265d86b5a404d0057049c82a4/CloudMailRu.pas#L225), позже стал использоваться HTTPS.
Indy не умеет работать с хранилищем сертификатов Windows, соответственно подмененный сертификат воспринимается, как недоверенный.
С этим мне ещё нужно разобраться. Попробуйте билд [отсюда](https://github.com/pozitronik/CloudMailRu/tree/issue_157), там я попытался напрямую отключить проверку сертификатов. Если заработает - значит копаю в правильном направлении.

**Comment by BorisNA** [comment]
Попробовал. Симптомы, к сожалению, те же самые. Может быть, версия TLS/SSL, или что там? (b5cc4f6dae092e7470a69241262fad54 *MailRuCloud.wfx)

Можно чем-то разобрать https пакеты, чтобы понять, что происходит? Wireshark, насколько я помню, просто покажет соединение, но не более того.

**Comment by pozitronik** [comment]
>Попробовал. Симптомы, к сожалению, те же самые. Может быть, версия TLS/SSL, или что там? 

Там есть ещё что копать. На выходных сделаю ещё одну тестовую версию.

> Можно чем-то разобрать https пакеты, чтобы понять, что происходит?

Можно, через mitm-проксирование, но это громоздко и пока не нужно - стоит сначала отсечь наиболее очевидные варианты.

**Comment by pozitronik** [comment]
Попробуйте ещё раз сборку из той же ветки.

**Comment by BorisNA** [comment]
К сожалению, всё ещё нет - та же самая ошибка.

Не знаю, насколько это важно (или это так очевидно) - после ввода пароля он думает немного (в логе вверху проскакивает ошибка, которую я приводил), потом вытаскивает ещё раз окно ввода пароля, и вот на второй раз уже отказывается дальше что-либо делать. В логе сдвоенная ошибка, как я писал в первом сообщении, одна за другой. Так было изначально, так и сейчас.

**Comment by pozitronik** [comment]
Ещё раз оттуда же. В логе должна появиться строчка SSL verify peer... - вот по ней будем гадать дальше.

**Comment by BorisNA** [comment]
А вот не появилась...
Файл 3df36a67775e19e83c3c7cb8651ab032 *MailRuCloud.wfx

`CONNECT \[]
Login to []
Requesting auth token for []
EIdSocketError ошибка сети: Socket Error # 10054
Connection reset by peer. при отправке данных на адрес https://auth.mail.ru/cgi-bin/auth?from=splash
error: getting auth token for []
`

В настройках стоит вот что
LogLevel=63

**Comment by pozitronik** [comment]
Чтобы копать дальше, мне нужно в точности воспроизвести ситуацию с прокси и подменой сертификата - чего я сделать не могу, к сожалению. Пока что это выглядит, будто HTTPS-соединение для плагина вообще режется, и ни до каких проверок сертификатов не доходит - иначе ошибки были бы другими.

**Comment by BorisNA** [comment]
Поставил обновление v28032018-pre - всё работает (может и до этого заработало, не знаю, не обновлялся на работе). В настройках сети ничего не менялось, более того стало иногда такое поведеине и в браузере проявляться, что соединение с веб-сайтом каким-то сбрасывается, загружается на 3-4 раз (потом работает Ок - видимо, DPI или ещё что).

Так что

1) Можно, наверное, закрыть issue
2) Чисто теоретически с моей проблемой помогла бы опция "при сбросе SSL соединения попробовать ещё N раз с задержкой между попытками в M секунд". Но не критично

**Comment by pozitronik** [comment]
В части работы с сетью в плагине ничего не менялось, так что по прежнему неизвестность. Над реализацией переподключения подумаю, благо схожий функционал уже есть.
Этот тикет закрываю.
