### ISSUE TITLE
Could not load SSL library.

### ISSUE THREAD

**Issue by areht** [pozitronik/CloudMailRu#158]
### Configuration

- Which version of Windows are you running? XP, Vista, 7, 8, 10? Is it 32-bit or 64-bit?
- Какую версию Windows вы используете? XP, Vista, 7, 8, 10? Это 32- или 64-разрядная ОС? 

10 home x32

- Which plugin version are you using? Stable release, last master build, other?
- Какую версию плагина вы используете? Релиз, последнюю master-сборку, другое?

051217 

комп новый, настраиваю ТС/плагин на нем впервые.

- What actually happened instead?
- Что случилось вместо этого?

EIdOSSLCouldNotLoadSSLLibrary ошибка с сообщением: Could not load SSL library. при отправке данных на адрес https://auth.mail.ru/cgi-bin/auth?from=splash
error: getting auth token for 

галочку про LoadSSLDLLOnlyFromPluginDir потыкал, не помогает. 

process monitor говорит ТС в подпапке x32 плагина либу нашел, ошибок не видно.

**Comment by pozitronik** [comment]
После перетыкивания галочки TC перегружался? Что будет, если перегрузить?

**Comment by areht** [comment]
да, несколько раз. И комп перезагружал.

**Comment by pozitronik** [comment]
Погонял по всякому на доступных мне конфигурациях, воспроизвести не удалось. Мыслей, почему не работает, у меня нет: библиотека грузится [где-то в indy](https://github.com/pozitronik/CloudMailRu/blob/master/MailRuCloud.dpr#L1748), если библиотека есть в памяти - значит она загрузилась и должна работать.

Что можно попробовать сделать: подсунуть плагину другие сборки библиотек [отсюда](https://wiki.openssl.org/index.php/Binaries).

**Comment by pozitronik** [comment]
Удалось проверить с другими библиотеками?

**Comment by areht** [comment]
У меня того компа сейчас под руками нет, на праздниках, наверное, доберусь

**Comment by areht** [comment]
распаковал в x32 содержимое https://indy.fulgan.com/SSL/openssl-1.0.2n-i386-win32.zip  и заработало

**Comment by pozitronik** [comment]
Вот и прекрасно.
