### ISSUE TITLE
Ошибки "EEDFADE" когда входишь в директорую на облаке, в которую еще фоном заливаешь файлы и директории.

### ISSUE THREAD

**Issue by Corak667** [pozitronik/CloudMailRu#159]
Ошибки когда входишь в директорую на облаке, в которую еще в фоне заливаешь файлы и директории.
Если идет обычная загрузка в директорию
http://picsee.net/upload/2017-12-10/72a148aec4ba.png
Если в директории уже есть эти файлы и идет просто пропуск повторяющихся имен
http://picsee.net/upload/2017-12-10/e244368270d6.png
Повторить легко - начинаешь загрузку в облако, ставишь "в фоне", заходишь в папку куда идет залив.

**Comment by pozitronik** [comment]
Именно в таком варианте у меня не воспроизвелось - исключение происходит, но всегда отлавливается, его видно только в логе.
Баг происходит при включении поддержки удалённых комментариев, тогда при обновлении каталога происходит запрос descript.ion. На уровне плагина это не должно вести к конфликтам - копирование данных и descript.ion происходят в разных потоках. Вероятно, глюк происходит при попытке вывести статус в диалоге прогресса, но надо разбираться.

**Comment by Corak667** [comment]
У меня оно воспроизводилось частенько - связано еще видимо со сканированием хеша, когда копируешь какой-то файл - он загрузился якобы, а ты шаришься в других папках (на других облаках например). Но конкретно этот краш обычно если шаришся в подпапках куда идет загрузка и они еще в это время обновляются-загружаются

**Comment by pozitronik** [comment]
Если снять галки про hash и CRC - воспроизводится?

**Comment by Corak667** [comment]
Только что проверил - воспроизводится в любом случае. Щас даже видео запишу

**Comment by Corak667** [comment]
https://youtu.be/I83c0xUFOww

**Comment by pozitronik** [comment]
Да я верю и без видео, но мне надо понимать, как воспроизвести.

**Comment by pozitronik** [comment]
Увидел на видео ошибку Control deleted from background thread, это интересная бага, существовавшая в старых версиях TC. О ней давно никто не слышал, тем интереснее будет разобраться.
В общем:
1. Проверь повторяемость на последней релизной версии TC (это 9.12).
2. Если будет воспроизводиться - кинь сюда MailRuCloud.global.ini

**Comment by Corak667** [comment]
1. Повторяется.
2. http://coraksoft1.narod.ru/temp/cloudmailru/MailRuCloud.global.ini

**Comment by pozitronik** [comment]
Приведи путь каталога в облаке, в который пытаешься копировать. На видео этого не видно.

**Comment by Corak667** [comment]
Только что проверял - путь не имеет значения. Пытался щас загрузить например в \\\CloudMailRu\Corak\temp\

Ошибка в логе:
```
EInvalidPointer ошибка с сообщением: Invalid pointer operation при отправке данных на адрес https://cloclo4-upload.cloud.mail.ru/upload/?cloud_domain=1&x-email=corakdoom%40mail.ru&fileapi15134243240246
error: uploading to cloud: EInvalidPointer with message: Invalid pointer operation

```

**Comment by Corak667** [comment]
Только что проверил и сравнил - ошибка не проявляется на билде v06122017-pre (который в релизах), а только в последнем ночном билде v08122017

**Comment by Corak667** [comment]
https://github.com/pozitronik/CloudMailRu/compare/06122017...master

**Comment by pozitronik** [comment]
> error: uploading to cloud: EInvalidPointer with message: Invalid pointer operation

Эту ошибку я воспроизвёл, но это несколько другое. Появления окон с исключением я добиться так и не смог.

**Comment by pozitronik** [comment]
Пробуй мастер-сборку.

**Comment by Corak667** [comment]
Вроде починено, спасибо!

**Comment by pozitronik** [comment]
Fixed at af2b4ac41f7a075fd2451a1699a2e54c42f4fd7a
