### ISSUE TITLE
Как  можно экспортировать/импортировать список учетных записей для облаков при переустановке TC и плагина? 

### ISSUE THREAD

**Issue by Impg** [pozitronik/CloudMailRu#160]
Здравствуйте! 
Хотел бы в первую  очередь сказать огромнейшее спасибо за Ваш труд. Плагин очень помог
Если можно 1 вопрос: когда понадобиться переустанавливать систему, как можно перенести списки  используемых облаков т.е. учетных записей ?

**Comment by pozitronik** [comment]
Настройки учётных записей хранятся в файле MailRuCloud.ini. Он может находиться либо в каталоге плагина, либо, [в некоторых случаях](https://github.com/pozitronik/CloudMailRu/issues/49), в каталоге %APPDATA%.
Не забудьте, что сохранённые в TC пароли переноситься не будут - TC имеет свои механизмы хранения, о которых мне неизвестно.
