### ISSUE TITLE
Не работает отмена операции копирования-переноса между облаками, при попытке отмены переноса и ошибке "Can't get temporary public link on" - файлы теряются

### ISSUE THREAD

**Issue by Corak667** [pozitronik/CloudMailRu#161]
Не работает отмена операции копирования-переноса между разными облаками, а при попытке отмены во время переноса:
при ошибке "Can't get temporary public link on" - файлы теряются вообще. То есть он удаляет файлы на источнике, даже не получив подтверждение об успешном переносе файла.
при ошибке "Can't delete" - переносятся нормально.
Пауза вроде как работает нормально.
Пока проще всего запаузить и наглухо принудительно вырубить TC. 
Возможно ли добавить копирование-перенос между облаками в фоне, ну как обычно чтобы диалоговое окно переноса-копирования не блокировало работу в TC? Или это к Гислеру?

**Comment by pozitronik** [comment]
По изначальной задумке при таком способе взаимодействия возможности отмены вообще не должно было быть (ссылочные операции практически моментальны). Но не учтено, что можно отменить глобальную операцию. Буду смотреть.

**Comment by Corak667** [comment]
Не, у меня ссылочные операции имеют большую задержку (около 1-3 секунды), например если куча файлов в папке - то очень долго. Даже 20 уже много времени

**Comment by pozitronik** [comment]
Нет, не в этом дело.
Сами операции создания/клонирования публичной ссылки - это атомарные вызовы, они очень быстрые. Относительную задержку создаёт перечитывание каталога,  плюс отрисовка прогресса на каждый чих. Плюс, в диалоге прогресса можно нажать отмену, что не всегда корректно обрабатывалось.
Я убрал возможность отменить создание ссылки, так что теперь отмена обрабатывается только на клонировании. Это должно решить проблему, просьба проверить на текущем мастер-билде.

**Comment by Corak667** [comment]
>Сами операции создания/клонирования публичной ссылки - это атомарные вызовы, они очень быстрые. Относительную задержку создаёт перечитывание каталога, плюс отрисовка прогресса на каждый чих. 
Возникает очевидный вопрос, можно ли как-то подавить перечитывание каталога, отрисовку прогресса, пока не завершен активный процесс обработки массива ссылок или до нажатия отмены?

**Comment by pozitronik** [comment]
Нет. TC всегда обновляет листинги каталогов в таких случаях. Никакого массива ссылок нет, процесс идёт последовательно по списку файлов, на каждый создаётся ссылка, ссылка клонируется и уничтожается.

**Comment by Corak667** [comment]
Жаль..

Проверил, кажется теперь все нормально и максимум ошибка "Can't delete", но процесс уже легко отменяется.
Также он оставляет последний файл, на котором была отмена. При попытке перенести обратно - встречает файл с тем же названием и невозможно его преписать при клонировании.
http://picsee.net/upload/2017-12-22/ea8f44330b7b.png
Выдает ошибку "File publish error: Невозможно создать. Доступ только для просмотра. Contine operation?"
и в логе
```
EIdHTTPProtocolException ошибка с сообщением: HTTP/1.1 400 Bad Request при отправке данных на адрес https://cloud.mail.ru/api/v2/clone?folder=pub/test/scr&weblink=GMuq/B6a7tP9co&conflict=strict&api=2&build=release_CLOUDWEB-7811_53.201712191723&x-page-id=pqO3f2kBos&email=TARGET%40mail.ru&x-email=SOURCE-MAIL%40mail.ru&token=7kjzftoHvFua9oR5Afu3NYT4xcTZbSey&_=1513948260810, ответ сервера: {"email":"TARGET-MAIL@mail.ru","body":{"home":{"value":"/ADDRESS/FILENAME","error":"exists"}},"time":1513937917779,"status":400}
Public link clone error: got 0 status

```

**Comment by pozitronik** [comment]
Так и должно быть.
