### ISSUE TITLE
Оптимизация загрузки больших файлов

### ISSUE THREAD

**Issue by areht** [pozitronik/CloudMailRu#163]
Если я правильно понимаю, то сейчас при загрузке большого файла:
1) он разрезается на части (2 прохода, чтение + запись в %tmp%)
2) Считается CRC по частям, для "моментальной" загрузки (+проход)
3) Считывается и загружается части (+проход)
4) Считается .crc по исходному файлу и загружается (+проход)

Т.е. по одному файлу происходит 5x обращений к диску. И всё это синхронно, т.е. это только прибавляет время к загрузке. 

Если у TC нет ограничений, то это всё можно делать за один-два прохода.

**Comment by areht** [comment]
Кстати, подумалось, что есть шанс, что исходный (неразрезанный) файл может быть целиком в облаке у платника. Его можно загрузить? Тогда есть смысл п.4 перенести в начало

**Comment by pozitronik** [comment]
>Если я правильно понимаю

В целом всё так. Можно оптимизировать, кидая порезанные части сразу в облако.

>Его можно "моментально" загрузить?

Мне приходил в голову этот вопрос, но у меня нет платного аккаунта для проверки.

**Comment by areht** [comment]
> Мне приходил в голову этот вопрос, но у меня нет платного аккаунта для проверки.

У меня со старых времен есть большие файлы в облаке, могу проверить. Тут надо подумать как это элегантно сделать, что бы не тормозить загрузку частей, дожидаясь лишний (ну, скорее всего большого файла то не окажется) подсчёт CRC, а то в целом оно того может и не стоить. Ну, или галочку сделать, отключенную по умолчанию.

**Comment by pozitronik** [comment]
>У меня со старых времен есть большие файлы в облаке, могу проверить.

Да, было бы неплохо.

>Тут надо подумать как это элегантно сделать, что бы не тормозить загрузку частей

На первый взгляд - никак. Посчитать CRC в фоне заранее - не получится, у плагина нет известного списка закачек, там всё синхронно. Начать заливку с одновременным подсчётом - ну, так себе идея. Имхо, это уже несёт больше геммороя, чем пользы.

**Comment by areht** [comment]
Поставил галку, что типа платник - залился большой файл на урезанный акк. 

> Имхо, это уже несёт больше геммороя, чем пользы.

Ну, наверное, да. Тут есть смысл только если до загрузки части всё же будет какой-то проход.

**Comment by pozitronik** [comment]
По результатам экспериментов:
1. Облако не поддерживает Content-Range, поэтому частичная загрузка файла не прокатывает.
2. TIdMultiPartFormDataStream не умеет частичную загрузку данных из файла/потока (в общем-то, это и не его задача). Т.е. нужно отдавать файл/поток с уже приготовленным куском данных.
3. Для подготовки таких кусковых объектов файл всё равно требуется считать. Можно использовать буфер в памяти, но при этом на x32-системах упираемся в 2Гб, доступных процессу. Городить костыли поведения в зависимости от доступной памяти будет неправильно.

Т.о. я не нашёл способа отправлять указанный кусок файла без сохранения этого куска на диск, увы. Единственное, что смогу оптимизировать - это делать подсчёт хеша для неразрезанного файла.

**Comment by areht** [comment]
А что значит "подготовки"? Посчитать CRC куска?

**Comment by pozitronik** [comment]
То, что этот кусок надо из файла вырезать, и сохранить в другой файл/память. "Считать" - не "считать CRC" а "прочитать".

**Comment by areht** [comment]
> То, что этот кусок надо из файла вырезать, и сохранить в другой файл/память.

Если нужен TStream с фрагментом - можно не копировать, а сделать TStream с фрагментом (ну, https://ru.wikipedia.org/wiki/Отображение_файла_в_память).

**Comment by pozitronik** [comment]
TMemoryStream ограничен 2ГБ, доступными процессу под x32.
Как заставить TFileStream работать так, я не знаю.

**Comment by areht** [comment]
Делаем свой стрим (наследованием/wrapper), перекрываем нужные методы(чтение, размер - смотря что клиент дергает). 

На просторах интернета есть примеры (не делфи,  но думаю суть не сильно отличается) https://stackoverflow.com/questions/6041117/calculating-md5-hash-of-a-partial-stream

class PartialFileStream : FileStream
{
public PartialFileStream(string path, FileMode mode, long
startPosition, long endPosition)
: base(path, mode)
{
base.Seek(startPosition, SeekOrigin.Begin);
ReadTillPosition = endPosition;
}

public long ReadTillPosition { get; set; }

public override int Read(byte[] array, int offset, int count)
{
if (base.Position >= this.ReadTillPosition)
return 0;

if (base.Position + count > this.ReadTillPosition)
count = (int)(this.ReadTillPosition - base.Position);

return base.Read(array, offset, count);
}
}

**Comment by pozitronik** [comment]
[Реализовано.](https://github.com/pozitronik/CloudMailRu/blob/master/ChunkedFileStream.pas)
