### ISSUE TITLE
Окно свойств: принудительно поверх всех окон, блокировка ESC других приложений

### ISSUE THREAD

**Issue by Corak667** [pozitronik/CloudMailRu#164]
Еще пару нюансов насчет работы окон свойств (аккаунты и ссылки), не критичны, но конечно же напрягают:
1. Они принудительно поверх всех окон (включая другие процессы). Хотелось бы снять этот параметр.
Например, в случае если нужно сохранить список временных прямых линков - окно сохранения - тоже ниже приоритетом и нельзя толком его увидеть или управлять.
2. При открытом окне свойств - ESC блокируется на всех других приложениях кроме Total Commander.

**Comment by pozitronik** [comment]
Исправлено в мастер-сборке.

**Comment by Corak667** [comment]
Подтверждаю, почти все исправлено.
Единственный нюанс, который остался - ESC не работает в диалоговом окне менеджере аккаунтов.

**Comment by pozitronik** [comment]
Обновил, теперь работает.

**Comment by DenisAnisimov** [comment]
А для чего нужна эта магия с RegisterHotKey в AskPassword? При открытии диалога ввода пароля я не могу нажать Enter и Esc ни в одном другом приложении, поскольку все нажатия этих клавиш перехватываются этим диалогом. Это очень не userfriendly. Если у меня, например, пароль записан в текстовом файлике, то мне сложно при появлении диалога открыть этот файлик без мыши.

Для обработки нажатия Enter и Esc вполне можно использовать обработчик CM_DIALOGKEY, в который приходят нажатия всех клавиш всех контролов формы.

**Comment by pozitronik** [comment]
Ни для чего не нужна, и если она там осталась, её нужно будет убрать.
