### ISSUE TITLE
Перезапись удаленным локальным файлом удаляет файл на облаке.

### ISSUE THREAD

**Issue by Corak667** [pozitronik/CloudMailRu#166]
Сейчас столкнулся с такой ситуацией - отметил группу файлов, чтобы копировать ее на облако, попутно решил удалить локальный файл, который уже был туда загружен с тем же названием. Через некоторое время выдало предупреждение с ошибкой, что такой файл уже есть и спрашивало перезаписать ли (размер исходного файла выдало как "-1").. Я по привычке подтвердил - оно удалило файл на облаке и снова выдает ошибку..  И далее не отрабатывает список и застревает.
Вот тут чтобы вернуть удаленный файл мне корзина и пришла на помощь.
Я к чему - возможно ли как-то отработать эту ошибку чтобы: 
скипало вообще попытку скопировать удаленный файл и переходило к следующему. 
и естественно не затирало файл на облаке в случае если локальный уже удален и его размер -1.

**Comment by pozitronik** [comment]
Да, можно, и, наверное, нужно поставить проверку на существование копируемого файла.

**Comment by Corak667** [comment]
Да, я как раз это и имел ввиду, это самое оптимальное)

**Comment by pozitronik** [comment]
Нужно проверить на текущем билде.

**Comment by Corak667** [comment]
Проверил, проблему с удалением решило, но ошибку вызывает
"Ошибка при закачке файла"
http://picsee.net/upload/2018-02-27/63b31776f8e9.png

**Comment by pozitronik** [comment]
Документация к API предлагает решать именно так проблему - жаловаться, что файл недоступен, а дальше пусть юзер смотрит. Думаю, это правильно, такая ситуация - исключение, которое плагин разруливать не должен.

**Comment by Corak667** [comment]
Нуок, главное не удаляет теперь, спасибо)
