### ISSUE TITLE
[Feature request] Упрощенная регистрация аккаунта

### ISSUE THREAD

**Issue by Corak667** [pozitronik/CloudMailRu#167]
Моя подруга @seiya-git написала в свое время замечательный JS под nodejs для быстрой и упрощенной регистрации на mail.ru (все на базе их api), чтобы легко и быстро создать новое облако без лишних веб-интерфейсных телодвижений. Решение с формой регистрации довольно простое, даже продуман конфиг с суффиксом и автоматическим именем и паролем, а также отработка возможных ошибок (превышено количество попыток, нужен телефон или неверная капча), а также вьювер капчи. Я конечно собрал все наработки в портабельный пак с нужными nodejs модулями и батник для зацикливания регистрации: http://coraksoft1.narod.ru/soft/network/mailru/Mailru-acc_registrator.7z
Сперва она написала версию скрипта (scripts\mailacc-v1.js) под обычную форму регистрации https://e.mail.ru/signup
Но она работает не так быстро (с задержкой в пару секунд). Чуть позже найдена более скоростная упрощенная форма: https://account.mail.ru/signup/simple
и под нее она написала новый скрипт (scripts\mailacc-v2.js), еще более упрощенный и намного более шустрый по отклику. Так что зарегистрировать акк можно за долю секунды, введя капчу.
Собственно пишу с подачи непосредственно @seiya-git, чтобы подробней описать ситуацию, она активно пользуется MailRu плагином. 
Думаю можно было бы привязать регистрацию по нажатию F7 (создание папки), это было бы вполне логично и гармонично как альтернатива медленной веб регистрации+сразу добавление облака в список, а там уже поля ввода (возможно с пресетами (префикс, пароль, имя-фамилия), чтобы не вбивать-копипастить те же самые данные повторно)...

**Comment by pozitronik** [comment]
Я подумаю, но реализация, если и будет, то не в ближайшее время.

**Comment by pozitronik** [comment]
Я попытался реализовать эту задачу, но столкнулся с обескураживающей ситуацией.
Первый шаг регистрации - постинг регистрационных данных на адрес https://account.mail.ru/api/v1/user/signup, ответом придёт JSON с данными для дальнейшего шага, либо кодом ошибки.

Когда я делаю постинг кодом - сервер всегда отвечает ошибкой о необходимости указания телефона.
>'{"body":{"phones":{"value":null,"error":"required"}},"email":null,"status":400,"htmlencoded":true}'

Когда я делаю постинг в curl - ответ чаще всего ожидаемый, но иногда - с той же ошибкой. Никакой зависимости не вижу, запросы одинаковые.
> curl -d 'name={"first":"Name","last":"lastname"}&login=Qwerty123EdE&domain=mail.ru&password=er1ed3ftfW' -H "Referer: pofig_chto" -X POST https://account.mail.ru/api/v1/user/signup

Запросы курлом и приложением выглядят абсолютно идентично, в Wireshark пакеты несколько различаются, но само содержимое запросов (а только это имеет значение) одинаково.

Постинг каким-нибудь третьим REST-клиентом не вызывает ошибки.

Я не понимаю, почему это происходит, и не вижу зацепки, за которую мог бы ухватиться.

**Comment by pozitronik** [comment]
В порядке экспериментов выяснено следующее:
- Чем отправлять запрос (curl/indy/rest-tester) - значения не имеет. Ответ сервиса не идемпотентен: на один и тот же запрос может вернуться как успешный код, так и требование указания поля phones.
- Похоже, что сервис проверяет User-Agent: на все запросы с отсутствующим/некорректным UA всегда приходит запрос телефона. Некорректным UA считается, видимо, не попадающий под формат "App/version".
- Также похоже, что есть какой-то лимит на указанные имя/фамилию: в какой-то момент на их комбинацию начинает приходить всё тот же ответ, но если их поменять - может начать работать (а может не начать).
Логика происходящего от меня ускользает, но, по крайней мере, я смог добиться, что иногда оно работает.

Вариант с указанием "phones" не хочу рассматривать.

**Comment by pozitronik** [comment]
Готово, в dev-ветке.
Кнопка в настройках + F7 в списке аккаунтов.
Разбора ошибок при регистрации делать не стал, лениво - просто показываю сообщение с возвращаемой ошибкой, из него должно быть понятно, что к чему.

**Comment by Corak667** [comment]
Проверил, все круто работает! Благодарю! 
Насчет ошибок - все вполне понятно, разбор не нужен

**Comment by Corak667** [comment]
Единственное что в будущем хотелось бы добавить автозаполнение формы по пресетам, чтобы создавать группу аккаунтов по 8 гиг с последовательной нумерацией серии.

**Comment by pozitronik** [comment]
Я думал над этим, но, мне кажется, это уже мультоводство, которое может быть легко отслежено и перебанено вместе с инструментом. Морально-этически это уж точно так.
Потому - нет.
