### ISSUE TITLE
Файлы с одинаковыми названиями удаляются, если перемещать из папки в папку (отмечая именно директорию) с одинаковыми названиями)

### ISSUE THREAD

**Issue by Corak667** [pozitronik/CloudMailRu#168]
Заметил тут еще одно неприятное - проверял - проявляется и в пределах одного облака и между несколькими облаками.
Допустим у нас две папки с одинаковыми именами и я хочу просто обновить одну из них переместив (move), но пропустив (то есть сохранить в обоих сторонах) все файлы с одинаковыми названиями (вдруг они отличаются)..  Перемещаю из одной в другую (не входя в нее и не отмечая файлы), а просто отметив эту папку или группу таких папок - если есть целевая папка (или несколько папок) с таким же названием.  Как только встречает внутри файлы с таким же названием - оно их непременно удалит их из источника, даже если я выбираю "пропустить все".
По сути: ошибка клонирования или переноса папок с одинаковыми именами и встреченными файлами внутри с одинаковыми именами .

**Comment by pozitronik** [comment]
Пожалуйста все действия пошагово, чтобы я всё правильно понял.

**Comment by Corak667** [comment]
Ок. По пунктам:
1. У нас есть две версии какой-то папки с одинаковым названием. Допустим две версии какой-то программы или сборки. В них определенно будут одинаковые файлы.
http://picsee.net/upload/2018-03-22/ca9297db21c9.png
http://picsee.net/upload/2018-03-22/92eabc891fa1.png
2. Я отмечаю в одной панели такую папку одной из версий - и делаю комманду на перемещение (MOVE)  в другую панель.
3. При перемещении оно задаст вопрос о замене встреченного файла с идентичным названием:
http://picsee.net/upload/2018-03-22/d77c09fd443c.png
Я нажимаю - пропустить все - чтобы сохранить файлы по обе стороны.
Но даже в таком случае - удаляется файл который я перемещаю.
http://picsee.net/upload/2018-03-22/d4ee5b09d340.png

**Comment by pozitronik** [comment]
Это поведение заложено в TC (не уверен, ошибка ли это, или так и должно быть). При перемещении структуры каталогов TC учитывает игнор файлов, но всё равно пытается рекурсивно удалить все каталоги. Возможно предполагается, что непустые каталоги в этом случае должны пропускаться, но это никак не документировано.
Попытаюсь обойти это поведение.

**Comment by pozitronik** [comment]
Мне удалось обойти такое поведение, реализовав что-то наподобие "чёрного списка": все пропущенные файлы вносятся в него, процедура удаления каталога проверяет, имеется ли в этом списке хотя бы один файл по удаляемому пути.

Нужно протестировать.

**Comment by Corak667** [comment]
Протестировал - работает отлично, спасибо!

**Comment by Corak667** [comment]
Кстати, а при клонировании между разными облаками, возможно ли как-то заменить файлы с одинаковыми именами по запросу (то есть чтобы был запрос на замену или пропуск? Просто сейчас выдает ошибку File Publish Error и ни одна из опций ничего не дает, кроме отмены операции, а также спотыкается на каждом файле, что приходится несколько раз пропускать его.
http://picsee.net/upload/2018-03-28/57ce061c4606.png

```
EIdHTTPProtocolException ошибка с сообщением: HTTP/1.1 400 Bad Request при отправке данных на адрес https://cloud.mail.ru/api/v2/clone?folder=Brigador%20-%20Up-Armored%20Edition&weblink=Cr6u/VznNe77LD&conflict=strict&api=2&build=CLOUDWEB-7907-54_5.201803271828&x-page-id=OL8pf56OaE&email=corakmusic-brigador-1%40mail.ru&x-email=corakmusic-brigador-1%40mail.ru&token=7TaZbaT3So34uWwbMdrGEUrR4nSghfsf&_=1522278052810, ответ сервера: {"email":"corakmusic-brigador-1@mail.ru","body":{"weblink":{"value":"Cr6u/VznNe77LD","error":"not_exists"}},"time":1522268425614,"status":400}
Public link clone error: got 0 status
EIdHTTPProtocolException ошибка с сообщением: HTTP/1.1 404 Not Found при отправке данных на адрес https://cloud.mail.ru/api/v2/file/unpublish, ответ сервера: {"email":"inferanaloos@mail.ru","body":{"weblink":{"value":"Cr6u/VznNe77LD","error":"not_exists"}},"time":1522268425934,"status":404}
Can't remove temporary public link on /exua_backup5_music_games/Music/Games/Brigador - Up-Armored Edition/Brigador-UpArmored-Edition_cover2.JPG
EIdHTTPProtocolException ошибка с сообщением: HTTP/1.1 400 Bad Request при отправке данных на адрес https://cloud.mail.ru/api/v2/clone?folder=Brigador%20-%20Up-Armored%20Edition&weblink=Cr6u/VznNe77LD&conflict=strict&api=2&build=CLOUDWEB-7907-54_5.201803271828&x-page-id=OL8pf56OaE&email=corakmusic-brigador-1%40mail.ru&x-email=corakmusic-brigador-1%40mail.ru&token=7TaZbaT3So34uWwbMdrGEUrR4nSghfsf&_=1522278052810, ответ сервера: {"email":"corakmusic-brigador-1@mail.ru","body":{"weblink":{"value":"Cr6u/VznNe77LD","error":"not_exists"}},"time":1522268426782,"status":400}
Public link clone error: got 0 status
EIdHTTPProtocolException ошибка с сообщением: HTTP/1.1 404 Not Found при отправке данных на адрес https://cloud.mail.ru/api/v2/file/unpublish, ответ сервера: {"email":"inferanaloos@mail.ru","body":{"weblink":{"value":"Cr6u/VznNe77LD","error":"not_exists"}},"time":1522268427090,"status":404}
Can't remove temporary public link on /exua_backup5_music_games/Music/Games/Brigador - Up-Armored Edition/Brigador-UpArmored-Edition_cover2.JPG

```

**Comment by pozitronik** [comment]
Скорее всего, это связано с #175
