### ISSUE TITLE
[Feature request] генерировать прямые линки для некоторых заданных расширений (видео-аудио), чтобы открывать их стримингом во внешнем плеере.

### ISSUE THREAD

**Issue by Corak667** [pozitronik/CloudMailRu#169]
Я тут вспомнил прошлое обсуждение насчет вопроса по прямым линкам и проигрыванию видео-аудио стримингу и возникла очередная и очевидная идея, запишу ее сюда, чтобы было (понятное дело, что не скоро и возможно сложный вопрос, но как бы было бы круто в будущем):

Вообщем суть - возможность настроить группу расширений (и вероятно какой-то плеер и его параметр открытия по http ссылке) - которые будут назначены для открытия стримингом. И по нажатию enter на этом файле - он не будет скачиваться целиком в temp (как сейчас) - а будет генерироваться временная прямая ссылка на него (как в свойствах при открытой шаре) - эта ссылка будет передаваться как параметр в назначенный плеер (vlc,potplayer или еще какой), который умеет http стримить... Вот собственно вся суть. 
Для чего - чтобы упростить возможность проигрывания крупных файлов (например весом в 2 гига, не скачивая их) - не тыкать свойства, расшаривать файл, получать его временный линк вручную или лазять через браузер и перехватывать там.. А сразу проиграть ассоциированным плеером.

**Comment by pozitronik** [comment]
Я думал об этом достаточно давно, но решил, что это будет неоправданным усложнением плагина. Если будет большая востребованность фичи - можно впилить.

**Comment by Corak667** [comment]
Ну скажем так - тут вопрос востребованности практически всегда будет минимален и нужен узкому кругу, плагином пользуются не так уж много людей (а тут вообще пишут единицы), поскольку решает вопрос - у человека есть крупные акки на террабайты (которые он успел провести по акции 2012) или он пользуется платным акком и при этом активно использует Total Commander... так что фильтр слишком большой, это расчитано на гиков или админов.
 
Согласен, выглядит действительно усложнением... Но я думаю как это попроще совместить с детектом расширения при открытии файла и отсылать параметром к указанному плееру...

**Comment by pozitronik** [comment]
>плагином пользуются не так уж много людей

Гитхаб не даёт подробной статистики, но я вижу ~100 уникальных скачиваний за последнюю  неделю. Это в разы меньше, чем раньше, что связано с отсутствием обновлений. У меня есть основания считать, что активных пользователей вполне достаточно.

Насчёт фичи я ещё буду думать. В очереди более приоритетные штуки, а времени нет пока даже на них.

**Comment by Corak667** [comment]
Скорее всего активные пользователи явно есть, просто они видимо не заходят на гит/форум и просто пользуются без особых инициатив...

Ладно, фишка просто упростила бы жизнь... Естественно если есть более приоритетное, то лучше решить.

Тут подруга подсказала альтернативную идею про генерацию ссылки на m3u8 для стрима 
"Домен + линк + имя файла в бейз64 + дабл энкод". И достаточно просто запроса shared." 
Не знаю насколько оно поможет, пожалуй единственное что - сделает вопрос любого плеера ассоциированного на m3u8+ts - более универсальным до уровня просто открытия плейлиста, а также просто не нужно получать прямой линк, достаточно просто расшарить.
например: если линк: на видео - https://cloud.mail.ru/public/8ee3/WSvbtTL7X
то: 
1. Через https://cloud.mail.ru/api/v2/dispatcher?api=2 получаем субдомен шары.
2. Конвертим линка в base64: 8ee3/WSvbtTL7X => base64 = OGVlMy9XU3ZidFRMN1g=
3. Получаем.
"https://cloclo29.cloud.mail.ru/videowl/" + "0p/" + "OGVlMy9XU3ZidFRMN1g=" + ".m3u8?double_encode=1"
=>
https://cloclo29.cloud.mail.ru/videowl/0p/OGVlMy9XU3ZidFRMN1g=.m3u8?double_encode=1

**Comment by yar229** [comment]
Вроде как есть возможность показать колонку с прямой ссылкой?

Если это так, то 
* ставим AutoHotkey
* делаем файл со скриптом
```
_ColumnNo := 1				; номер колонки
_ExePath := "Notepad.exe"	; приложение для запуска

ClipBoard := "" 
PostMessage, 0x433, 2037, 0,, A
ClipWait 

lines := StrSplit(ClipBoard, "`t")
data := lines[_ColumnNo]

;MsgBox, Data: `n------`n%data%`n------
Run, %_ExePath% "%data%"
```
* на кнопку или сочетание клавиш в ТС делаем команду
```
C:\Program Files\AutoHotkey\AutoHotkey.exe "<disk>:\[path]\<script_name>.ahk"
```

**Comment by Corak667** [comment]
@yar229 неплохой вариант, спасибо! Но там среди полей можно показать только линк шары, но не прямой линк и нужно еще несколько дополнительных манипуляций, которые по сути отменяют все удобства) 
http://picsee.net/upload/2018-03-28/ae853f6c5e68.png
Этот линк только шары (не прямой на файл), как я уже упомянул - нужно 
1. Сперва расшарить файл.
2. Кодить хеш линка в base64. 
3. Получать имя домена сервера. 
4. Совмещать в "https://%серв%.cloud.mail.ru/videowl/" + "0p/" + "%base64%" + ".m3u8?double_encode=1"

**Comment by yar229** [comment]
Ясно, сорри, был невнимателен :)

**Comment by pozitronik** [comment]
Добавлено, посмотреть и потестить можно в билде мастер-ветки. В настройках появилась вкладка Streaming, там всё достаточно очевидно. До документирования пока не добрался.

Вообще фичу, судя по логу, я реализовал ещё весной, сейчас я только прикрутил настройки.

**Comment by Corak667** [comment]
Проверил, все круто работает! То что надо! Спасибо огромное!
