### ISSUE TITLE
Отображение занятого/свободного места

### ISSUE THREAD

**Issue by pozitronik** [pozitronik/CloudMailRu#17]
Отображать subj в поле "Размер" "каталога" аккаунта.

**Comment by pozitronik** [comment]
Added at commit 232417053f39f5416bf46c2835d33294bfaa7250

**Comment by pozitronik** [comment]
Доработка: показывать эти же данные при завершении файловых операций.

**Comment by Laex** [comment]
Для разработчиков - перенесите getUserSpace в public

**Comment by pozitronik** [comment]
Зачем?

**Comment by pozitronik** [comment]
> Доработка: показывать эти же данные при завершении файловых операций.
Done at c0cd8bc32b46fd1b008b1f9f3182a9c7e99e9b8d
