### ISSUE TITLE
Критическая ошибка 403 Forbidden при входе в любое облако

### ISSUE THREAD

**Issue by Corak667** [pozitronik/CloudMailRu#170]
Вообщем теперь не входит ни в одно из облак через плагин:
```
EIdHTTPProtocolException ошибка с сообщением: HTTP/1.1 403 Forbidden при отправке данных на адрес https://cloud.mail.ru/api/v2/user/space?home=/&api=2&build=&x-page-id="76JAlvb18&email=corak%40mail.ru&x-email=corak%40mail.ru&token="TOKEN&_=1522181001810, ответ сервера: {"email":"@mail.ru","body":"token","time":1522170152801,"status":403}
EIdHTTPProtocolException ошибка с сообщением: HTTP/1.1 403 Forbidden при отправке данных на адрес https://cloud.mail.ru/api/v2/folder?sort={%22type%22%3A%22name%22%2C%22order%22%3A%22asc%22}&offset=0&limit=65535&home=/&api=2&build=&x-page-id="76JAlvb18&email=corak%40mail.ru&x-email=corak%40mail.ru&token="TOKEN&_=1522181001810, ответ сервера: {"email":"corak@mail.ru","body":"token","time":1522170153042,"status":403}
```
Через веб нормально
Пробовал с обоих компов, обоих систем (xp/win7). Менял ip (у меня динамический) - также.

**Comment by pozitronik** [comment]
Подтверждаю. Буду разбираться по возможности.

**Comment by VecH** [comment]
И вправду проблема присутствует
`CONNECT \vech2k@mail.ru
Login to vech2k@mail.ru
Requesting first step auth token for vech2k@mail.ru
Parsing authorization data...
Awaiting for security key... 
Performing second step auth...
Connected to vech2k@mail.ru
EIdHTTPProtocolException ошибка с сообщением: HTTP/1.1 403 Forbidden при отправке данных на адрес https://cloud.mail.ru/api/v2/user/space?home=/&api=2&build=&x-page-id="0lKA7Vjdk&email=vech2k%40mail.ru&x-email=vech2k%40mail.ru&token="9HfTCzaEa3mdRvKDqK5ZWQTf5rBD4DW&_=1522242160810, ответ сервера: {"email":"vech2k@mail.ru","body":"token","time":1522209759648,"status":403}
error: getting user space information for vech2k@mail.ru
Current shard is undefined, trying to get one
EIdHTTPProtocolException ошибка с сообщением: HTTP/1.1 403 Forbidden при отправке данных на адрес https://cloud.mail.ru/api/v2/dispatcher/
Sorry, downloading impossible
EIdHTTPProtocolException ошибка с сообщением: HTTP/1.1 403 Forbidden при отправке данных на адрес https://cloud.mail.ru/api/v2/folder?sort={%22type%22%3A%22name%22%2C%22order%22%3A%22asc%22}&offset=0&limit=65535&home=/&api=2&build=&x-page-id="0lKA7Vjdk&email=vech2k%40mail.ru&x-email=vech2k%40mail.ru&token="9HfTCzaEa3mdRvKDqK5ZWQTf5rBD4DW&_=1522242160810, ответ сервера: {"email":"vech2k@mail.ru","body":"token","time":1522209760587,"status":403}
Current shard is undefined, trying to get one
EIdHTTPProtocolException ошибка с сообщением: HTTP/1.1 403 Forbidden при отправке данных на адрес https://cloud.mail.ru/api/v2/dispatcher/
Sorry, downloading impossible
EIdHTTPProtocolException ошибка с сообщением: HTTP/1.1 403 Forbidden при отправке данных на адрес https://cloud.mail.ru/api/v2/folder?sort={%22type%22%3A%22name%22%2C%22order%22%3A%22asc%22}&offset=0&limit=65535&home=/&api=2&build=&x-page-id="0lKA7Vjdk&email=vech2k%40mail.ru&x-email=vech2k%40mail.ru&token="9HfTCzaEa3mdRvKDqK5ZWQTf5rBD4DW&_=1522242160810, ответ сервера: {"email":"vech2k@mail.ru","body":"token","time":1522209764374,"status":403}`

**Comment by pozitronik** [comment]
Причина найдена, сегодня будет патч.

**Comment by pozitronik** [comment]
Исправлено.
Поменялось содержимое страницы, из которой парсился токен (изменилось форматирование включённых на страницу скриптов). Я переписал парсер, чтобы учитывал подобные изменения в будущем.

**Comment by VecH** [comment]
А где релиз?

**Comment by pozitronik** [comment]
Чуть позже, пока можно взять бинарники из ветки.

**Comment by Corak667** [comment]
Проверил, Отлично работает! Спасибо!

**Comment by Rahashan** [comment]
Та же самая ошибка. Пробовал с нескольких компьютеров, устанавливал и удалял плагин, TC - ошибка повторяется. До этого все нормально работало и был очень доволен. Плагин обновил до релиза v010142018-pre.

**Comment by pozitronik** [comment]
Нужны подробная информация, как описано в документации.

**Comment by aiperonster** [comment]
Эта же ошибка, после того как скачал последнюю версию отсюда. Шо делать?

**Comment by pozitronik** [comment]
Не подтверждаю. Приведено очень мало информации. Опишите пожалуйст так, как указано в документации, иначе мне не за что зацепиться.

**Comment by scratcher28** [comment]
Аналогичная проблема при копировании файлов в облако, ошибка HTTP/1.1 403 Forbidden от nginx,

**Comment by pozitronik** [comment]
Вывод в логе похож на проблему #254?
