### ISSUE TITLE
Login to ***@mail.ru error: parsing auth token for ***@mail.ru

### ISSUE THREAD

**Issue by Harpmaker** [pozitronik/CloudMailRu#171]
Здравствуйте!
С новейшей версией всё равно не распознаётся токен 
Login to ***@mail.ru error: parsing auth token for ***@mail.ru
При установке двухфакторной авторизации прислал мне три пароля подряд и вылетел с таймаутом 7131 сек.

![image](https://user-images.githubusercontent.com/37863600/38016275-37751f8c-3277-11e8-9cdd-d77217c9179e.png)

**Comment by pozitronik** [comment]
Не подтверждаю.
Я успешно авторизовался под двухфакторкой как по SMS-коду, так и по коду из приложения.

Подобное поведение я замечал при тестах, например, если несколько раз подряд "постучаться" на авторизацию и ввести не те коды (каждая новая попытка будет инвалидировать предыдущие высланные коды). Подобное вполне могло случиться, пока вы пытались войти с предыдущей версией плагина (но это не точно).

Что можно сделать: в настройках двухфакторной авторизации аккаунта подключить мобильное приложение для генерации кодов, и входить уже с ними (там нет таймаута).

Тикет пока не закрываю, возможно кто-то ещё сообщит о похожей проблеме.

**Comment by Harpmaker** [comment]
Возможно, это какой-то сбой mail.ru - коды приходили пачкой по три штуки, вводил последний, после этого было не войти даже отключив двухфакторную авторизацию. Сейчас заходит, если двухфакторную авторизацию отключить и в плагине и в настройках аккаунта. Позже попробую включить снова, возможно выставился какой-то очень длительный таймаут

**Comment by Harpmaker** [comment]
Проверил, несколько раз отключая/включая двухфакторную авторизацию. Иногда выходит ошибка
EIdHTTPProtocolException ошибка с сообщением: HTTP/1.1 403 Forbidden при отправке данных на адрес https://cloud.mail.ru/api/v2/folder?sort={%22type%22%3A%22name%22%2C%22order%22%3A%22asc%22}&offset=0&limit=65535&home=/&api=2&build=CLOUDWEB-7907-54_5.201803271828&x-page-id=Y5NumApLEk&email=*****%40mail.ru&x-email=*****%40mail.ru&token=aq49ooD4j2a5DP48BFm93oWsU5m9ADKq&_=1522244619810, ответ сервера: {"body":"user","time":1522237599662,"status":403}

В основном работает нормально

**Comment by pozitronik** [comment]
Судя по другим жалобам на похожие симптомы, есть какая-то проблема, не связанная ни с авторизацией, ни с двухфакторкой. Буду пытаться воспроизвести, пока что это не получается.

**Comment by pozitronik** [comment]
fixed at #177

**Comment by nktnsrg** [comment]
Здравствуйте!
Начинает логиниться и процесс прерывается ошибкой:
Login to ***@mail.ru
Current upload shard is undefined, trying to get one
error: parsing auth token for ***@mail.ru
Mail-проблема?

**Comment by pozitronik** [comment]
=> #235

**Comment by midi-creator** [comment]
с Двухфакторной попробовал включить - нет
попробовал выключить - нет (((

**Comment by maxim7137** [comment]
Не понимаю почему но на одном аккаунте работает и заходит без проблем на на другом error: parsing auth token for *@mail.ru
