### ISSUE TITLE
TC не проверяет перемещение каталога в себя самого

### ISSUE THREAD

**Issue by pozitronik** [pozitronik/CloudMailRu#172]
Что приводит к зацикливанию операции и последующему удалению перемещаемого каталога.

**Comment by pozitronik** [comment]
Нет способа отловить такую ситуацию. TC сообщает о начале перемещения из родительского каталога перемещаемого каталога (но не сообщает о имени этого каталога), затем пытается воссоздать путь, что приводит к итеративному зацикливанию (создаётся подкаталог, перечитывается - опа, подкаталог, создаётся подкаталог).

**Comment by Corak667** [comment]
Давно отметил и писал об этом. 
С другой стороны это интересная и простая фишка множественно циклического создания копий файлов для проверки предела.

**Comment by Corak667** [comment]
ref:
https://github.com/pozitronik/CloudMailRu/issues/113
