### ISSUE TITLE
Функция открыть каталог в левой/правой панели (ctrl+left или ctrl+right) - открывает файл как папку облака и там конечно ошибки 404

### ISSUE THREAD

**Issue by Corak667** [pozitronik/CloudMailRu#174]
Еще давно заметил такое интересное поведение.... Понятное дело, что оно не критично...  так и задумано. но все-же для файлов стоит видимо сделать исключение, дабы не было потенциальных ошибок и неудобств с этой функцией.
Если открыть каталог облака (синхронизировать открытую папку/файл в обоих панелях) в левой/правой панели (ctrl+left или ctrl+right) - оно открывает файл как папку облака (якобы архив). Там видны все файлы в каталоге рядом с этим файлом, но вот при попытке что-то сделать там - выдает ошибку 404 not found.
http://picsee.net/upload/2018-03-28/53c4172bd711.png
 Единственное решение чтобы не было ошибки - выйти из файла ".." в нормальный путь облака...
Лог ошибок при копировании:
```
EIdHTTPProtocolException ошибка с сообщением: HTTP/1.1 400 Bad Request при отправке данных на адрес https://cloud.mail.ru/api/v2/folder?sort={%22type%22%3A%22name%22%2C%22order%22%3A%22asc%22}&offset=0&limit=65535&home=test/1/test/MailRuCloud.wfx/MailRuCloud.wfx&api=2&build=CLOUDWEB-7907-54_5.201803271828&x-page-id=yjKW7WXfwO&email=ruwimlvovich%40mail.ru&x-email=ruwimlvovich%40mail.ru&token=6uARPUEnzePsrMm3rj6vBajhHNhdEogL&_=1522267679810, ответ сервера: {"email":"ruwimlvovich@mail.ru","body":{"home":{"value":"/test/1/test/MailRuCloud.wfx/MailRuCloud.wfx","error":"not_dir"}},"time":1522257251848,"status":400}
EIdHTTPProtocolException ошибка с сообщением: HTTP/1.1 404 Not Found при отправке данных на адрес https://cloud.mail.ru/api/v2/file/copy, ответ сервера: {"email":"ruwimlvovich@mail.ru","body":{"home":{"value":"/test/1/test/MailRuCloud.wfx/MailRuCloud.wfx","error":"not_exists"}},"time":1522257283933,"status":404}

```

**Comment by pozitronik** [comment]
Функционал работы с архивами тут не при чём. Такое поведение происходит потому, что облако, в ответ на запрос листинга для пути к файлу возвращает листинг для содержащего его каталога, никак не сообщая об ошибке. 
Железобетонного прямого способа определить, является ли объект под курсором каталогом нет. Есть косвенные (например, каждый раз запрашивать у облака какую-нибудь операцию, недопустимую для файла, и анализировать ответ), но это сильно ухудшит отзывчивость. Оно того не стоит.

**Comment by Corak667** [comment]
Понял, ладно, спасибо)
Не столь критично, ибо проблема редкая, мизерная и мало кто ее воспроизведет, нужна только чтобы не тыкаться на файловые линки для быстрой смены, просто буду осторожней и буду линкать только папки)

**Comment by pozitronik** [comment]
Теперь плагин пробует найти открываемый объект в текущем листинге каталога и проверить, является ли он каталогом. Если нет, то операция будет заблокирована.
Это определённо решает текущую проблему, но, возможно, вызовет какие-то другие неочевидные эффекты, нужно проверять.

**Comment by Corak667** [comment]
Проверил - все работает, блокирует операцию листинга, если ссылаемся на файл.
Спасибо)

**Comment by Corak667** [comment]
upd:
Работает только для СВОИХ акков. (Отправляет в последний в прошлом открытый локальный диск)
А вот если работаем со шарой по ссылке, то проблема остается и файлы еще листит.

**Comment by Corak667** [comment]
как видишь:
http://picsee.net/upload/2018-04-04/b3b56facd8a7.png

**Comment by pozitronik** [comment]
Облако не возвращает для расшаренных каталогов пути, только имена файлов, подумаю, как выкрутиться.

**Comment by pozitronik** [comment]
Облако не возвращает для расшаренных каталогов пути, только имена файлов, подумаю, как выкрутиться.

**Comment by pozitronik** [comment]
Проверяй

**Comment by Corak667** [comment]
Проверил - сейчас работает и на публичных шарах.
Спасибо!

**Comment by pozitronik** [comment]
В папке публичных ссылок (.shares) такое поведение **для каталогов** сохранится: все каталоги там являются ссылками на переход к соответствующему пути в облаке. TC не умеет обрабатывать такую ситуацию, пытаясь открыть каталог по тому пути, который "видит" в панели.
Для файлов в .shares поведение исправлено - для них достаточно проверки на то, что это "не каталог".
