### ISSUE TITLE
Сломалась работа с публичными ссылками

### ISSUE THREAD

**Issue by pozitronik** [pozitronik/CloudMailRu#175]
Что-то поменяли на сервере, теперь публичные ссылки содержат символ /, который плагин трактует как часть URL. В результате весь связанный функционал поломан.

**Comment by Walkerru** [comment]
Плагин работал с публичными шарами до прошлой недели. Теперь снова: Can't get public share download token

**Comment by pozitronik** [comment]
#234 #235 
На серверной стороне что-то меняют опять.
