### ISSUE TITLE
EIdHTTPProtocolException ошибка с сообщением: HTTP/1.1 403 Forbidden при отправке данных на адрес https://cloud.mail.ru/api/

### ISSUE THREAD

**Issue by Impg** [pozitronik/CloudMailRu#176]
Здравствуйте
У меня вопрос. В прежней версии плагине начала выскакивать ошибка  что есть ошибка с токеном 
Обновил плагин и теперь  [есть новая ошибка](https://image.ibb.co/heqYpn/image.png) : 
После чего открывается пустая папка, вроде как есть вход но в облаке просто файлов нет...
Что делать? Помогите, пожалуйста

**Comment by pozitronik** [comment]
Прочтите пожалуйста [этот раздел документации](https://github.com/pozitronik/CloudMailRu#%D0%9A%D0%B0%D0%BA-%D0%B8-%D0%BA%D1%83%D0%B4%D0%B0-%D0%BF%D1%80%D0%B0%D0%B2%D0%B8%D0%BB%D1%8C%D0%BD%D0%BE-%D0%B6%D0%B0%D0%BB%D0%BE%D0%B2%D0%B0%D1%82%D1%8C%D1%81%D1%8F-%D0%BD%D0%B0-%D0%BF%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D1%8B) и предоставьте нужную информацию - только тогда я смогу начать разбираться.
