### ISSUE TITLE
wcftplog.txt

### ISSUE THREAD

**Issue by Impg** [pozitronik/CloudMailRu#177]
Отчет касается проблемы ранее описанной [в этой теме](https://github.com/pozitronik/CloudMailRu/issues/176)
Отчет прилагается
[wcftplog.txt](https://github.com/pozitronik/CloudMailRu/files/1864547/wcftplog.txt)
Спасибо за помощь

**Comment by pozitronik** [comment]
[RTFM](https://github.com/pozitronik/CloudMailRu#%D0%AF-%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%B8%D0%BB-%D0%BF%D0%BB%D0%B0%D0%B3%D0%B8%D0%BD-%D0%BD%D0%BE-%D0%B2%D0%BE%D0%B7%D0%BD%D0%B8%D0%BA%D0%B0%D0%B5%D1%82-%D0%BE%D1%88%D0%B8%D0%B1%D0%BA%D0%B0-could-not-load-ssl-library)

**Comment by pozitronik** [comment]
Проблема **указанная в логе** исправлена.
Про первоначальную проблему мне по прежнему ничего не сообщено. Могу сказать только, что версия плагина **14052017** упомянутая в приложенном файле, неактуальна, и работать не будет.

**Comment by Impg** [comment]
Здравствуйте
Скачал  и установил  версию v010142018-pre
Последовательность такая: 

- Захожу в учетную запись 
- Идет вход в учетную запись ... так как ошибки об не достающей ssl уже нет Потому что эта библиотека устанавливается вместе с плагиноми,  нужно в настройках отметить чтобы их загрузка производилась именно из каталога плагина, чтобы избежать конфликтов 
- В самый последний момент выскакивает ошибка, лог будет приложен
- Сервер отдает пустую страницу т.е. как будто файлов в облаке нет 
Буде рад любой помощи. 
[wcftplog.txt](https://github.com/pozitronik/CloudMailRu/files/1868082/wcftplog.txt)

**Comment by pozitronik** [comment]
Проблема по логу действительно похожа на уже исправленную - некорректно парсилась страница, и токен вырезался кривой. Текущий парсер такого допускать не должен.
Я, конечно, перепроверю, но и вы тоже перепроверьте - действительно ли используется самая новая версия плагина. Сравните, например, размеры wfx/wfx64-файлов с теми, что лежат в архиве - может они просто не перезаписались?

**Comment by Impg** [comment]
Сравнение wfx файла показало полную идентичность: между установленным файлом и скачанным архивом
 
![default](https://user-images.githubusercontent.com/1159765/38197493-14b9f04e-3691-11e8-92cc-ad870779f33f.png)
Ошибок при скачивании - нет: перепроверил повторную загрузку архива 
![-](https://user-images.githubusercontent.com/1159765/38197511-32cecf46-3691-11e8-8420-daf024cc3849.png)

**Comment by pozitronik** [comment]
Пробуйте на последней [мастер-сборке](https://github.com/pozitronik/CloudMailRu/commit/8cfc3b3594d682dd25ba7b78024fe89c2e80b2bc).

**Comment by Impg** [comment]
На 100% работает!! 
Огромнейшее спасибо!! 
Больше того. Я только что попробовал стабильную версию  установить 
 v14052017 (без  приставки pre) и поменял  файл MailRuCloud.wfx -  только и всего !
Похоже что и правда дело было в парсере, как вы говорили.

ps 
А можно вопрос немного не по теме: есть ли возможность русифицировать плагин. Я знаю что этот вопрос уже поднимался, но ничего не понял: там ссылка на ссылку ссылается и не больше :)  
Заранее спасибо.

**Comment by pozitronik** [comment]
>v14052017 (без приставки pre) и поменял файл MailRuCloud.wfx - только и всего !

Ну это не совсем то, что ожидалось, но работать будет.

>Похоже что и правда дело было в парсере

По логу я предположил, что майловский сервер может отдавать слегка по разному отформатированое содержимое. Я доработал парсер, чтобы он игнорировал форматирование в принципе, хорошо, что это помогло.

>есть ли возможность русифицировать плагин
Есть тикет #63.
Он, пожалуй, наиболее низкоприоритетный. Интернационализация - это неинтересная и нудная задача, а поддерживать её - задача ещё более скучная. У меня нет мотивации это делать, и я не представляю, что меня могло бы мотивировать.

**Comment by Impg** [comment]
> По логу я предположил, что майловский сервер может отдавать слегка по разному отформатированое содержимое.
За ютубом - схожая уловка замечена :)

>  Я доработал парсер, чтобы он игнорировал форматирование в принципе, хорошо, что это помогло
Нам всем очень повезло, что задача вами решена. Еще раз  - огромное спасибо
Ура - мои облака снова со мной !! :)

**Comment by Impg** [comment]
> Интернационализация - это неинтересная и нудная задача, а поддерживать её - задача ещё более скучная. 

Я не уверен, могу только предполагать, что если изначально не планировалось подписи всего что  в GUI хранить в отдельном файле ini, то потом , все переделывать .... бррр, ой как хлопотно видимо. Я кажется вас  понимаю . Но  - всегда лучше спросить, как говорил Меровинген :)
Удачи вам!
