### ISSUE TITLE
Зависание при попытке удалить папку (или переименовать файл), после копирования внутри аккаунта (с 28 и более символов в названии акка и при включенной опции "Copying/moving between accounts via public link")

### ISSUE THREAD

**Issue by Corak667** [pozitronik/CloudMailRu#179]
Заметил сегодня очень неприятный момент. Зашел в один из акков где огромное количество файлов и папок. Зашел в одну папку, удалил оттуда файл, удалился.. Попытался удалить эту папку - зависание. И так через раз при каждой попытке. Приходится принудительно вырубать TC. Суть в том что на акке огромная коллекция. 
Это похоже как-то влияет на парсинг для фунции рекурсивного (моментального) удаления папкой? Возможно какое-то переполнение переменной? Как это дебажить или хотя бы получить более подробные дебаг данные ибо никаких ошибок в логе не выдает?
Такое зависание исключительно с удалением папкой (обычно при удалении 2й папки за сессию, с файлами или без) - копирование-перенос и удаление пофайлово - нормально.
Видео пруф например:
https://youtu.be/leYZoVDZrXM
Проявляется на каждом крупном акке где много файлов - после операции удаления, копирования или переноса файла на нем.
После операций только на мелких акках не проявляется.
Также зависает если попытаться удалить папку на другом акке (после удаления хотя бы одного файла с большого акка)
А да, также если попытаться переименовать любой файл (на любом облаке). после удаления какого-то файла с большого акка:
Выдает таки ошибку:
http://picsee.net/upload/2018-04-01/73cf3e3878b5.png
```
---------------------------
Total Commander 9.12RC4
---------------------------
Access violation at address 04B29CE9. Read of address 00000058.
Access violation at address 04B29CE9. Read of address 00000058
Windows 7 SP1 6.1 (Build 7601), base: 00400000

Please report this error to the Author, with a description
of what you were doing when this error occurred!

Windows exception: C0000005
Stack trace:
04B29CE9
00449D16  0044A6AA  0042728E  00449C4C  0042728E  0042140C
0042141C  005804EB  00436576  00449BA2  0042728E  00436576
00449C4C  0042728E  00402249  004023EF  0046D100  004486A9
0044A6AA  >0042728E  00449C4C  0042728E  0042C8E4  0042CAA8

Raw:
0044AA23  004486A9  0044A979  004394D2  00449C9E  00449D16
0044A6AA  0044A6CD  0042728E  00449C4C  0042728E  0042140C
0042141C  005804EB  00436576  004486A9  0044A979  00449D16
0044A6AA  0044A6CD  00449BA2  0042728E  0044AA23  00436576
004486A9  0044A979  00449D16  0044A6AA  0044A6CD  0042728E
00449C4C  0042728E  004023EF  004026B8  00403707  0046CE8C
00449BA2  0044AA23  00436576  004486A9  0044A979  00449D16
004485DF  0042A0A8  0042B290  00429E1E  0044C216  0057F8FD
0057F934  0057F981  00449BA2  0042728E  00449C4C  0042728E
00402E8E  004486A9  0044A979  004291D5  00449D16  0044A6AA

```
(файл потом успешно переименовывается после перезапуска TC)

**Comment by pozitronik** [comment]
>Попытался удалить эту папку - зависание.

[rmdir dirname](https://github.com/pozitronik/CloudMailRu#%D0%9A%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D1%8B-%D0%BF%D0%BB%D0%B0%D0%B3%D0%B8%D0%BD%D0%B0)

Только так, иначе TC будет пытаться удалять файловую структуру рекурсивно.

Насчёт других ошибок - мне нужно более подробное описание, как минимум - какова структура удаляемого каталога? Сколько файлов, какова вложенность, etc. Идеально бы было получить архив со структурой, на которой ошибка воспроизведётся.

**Comment by Corak667** [comment]
Оно проявляется при попытки удаления любой папки или переименования на любом аккаунте после действия на файлах в крупном аккаунте...

Как оптимально сделать каталог? Через поиск?

**Comment by pozitronik** [comment]
Можешь расшарить и мне линк кинуть.

**Comment by Corak667** [comment]
@pozitronik 
Вот например. Коллекция софта, доков из прошлого... очень много файлов, не успел все разгрести.
https://cloud.mail.ru/public/JfQj/6L1KLakjp

**Comment by pozitronik** [comment]
Ок, этого достаточно, завтра посмотрю.

**Comment by Corak667** [comment]
вот список файлов и диров скопировал через поиск.
http://coraksoft1.narod.ru/temp/cloudmailru/Corak-pub-cloud-index-20180402.7z
_

**Comment by pozitronik** [comment]
Я описанного поведения не могу воспроизвести.
Удаление любого объёма данных очень быстрое и беспроблемное, во всех проверенных мной комбинациях.
Так что давай прямо по пунктам, пошагово, что нужно сделать внутри расшаренного каталога pub, для воспроизведения.

**Comment by Corak667** [comment]
1. Заходишь в любую папку pub-а, 
2. Копируешь или переносишь какой-то один файл в другую папку (на самом диске).
3. Удаляешь какую-нибудь папку
(есть подозрение что спотыкается о какую-то ошибку с вирусом, то есть может дело не только в количестве, но и статусе файла... хотя не факт)

**Comment by Corak667** [comment]
Понятно, оно зависает из-за функции "Copying/moving between accounts via public link"
Если ее отрубить то зависания при удалении не будет.

**Comment by Corak667** [comment]
Связано, но не полностью:
https://github.com/pozitronik/CloudMailRu/issues/175

**Comment by pozitronik** [comment]
Даже на самом свежем билде воспроизводится?

**Comment by Corak667** [comment]
Да, даже на самом свежем. Щас перепроверил же

**Comment by pozitronik** [comment]
Не воспроизводится. Делаю пошагово ровно по написанному, всё отрабатывает чётко, без зависаний и ошибок, независимо от состояния опции переноса по публичным ссылкам.
Мне трудно понять, что происходит на скринкасте, возможно ты пытаешься скопировать или переместить каталог внутрь собственного подкаталога, тогда TC действительно зависнет из-за рекурсии. Это никак не чинится.

**Comment by Corak667** [comment]
Нет, я просто пытаюсь удалить папку при врубленной опции переноса по публичным линкам, после того как скопировал файл внутри облака куда-нибудь:
https://youtu.be/9sxVuAJFQmg
Воспроизводится отлично на обоих компах, как на WinXP так и на 7рке... Может дело в еще каких настройках. Щас попробую обнулить настройки и проверить..

**Comment by Corak667** [comment]
Так, обнулил - работает.
Выяснил - дело таки в названии аккаунта, верней даже количестве символов для имени аккаунта (виртуальной папки)
Если в имени твоего акка - 27 символов и менее - прокатит. Если 28 и более - повиснет

**Comment by Corak667** [comment]
Пруф
https://youtu.be/K5EA4842xNQ

**Comment by pozitronik** [comment]
Зависание не воспроизводится. Возможно я что-то не могу понять по скринкасту - качество довольно шакальное, и там не всегда очевидна последовательность действий. 
Однако у меня получается стабильно воспроизвести исключение, причём не отлавливаемое отладчиком, хотя и при несколько иной последовательности действий.
Пока буду копать в эту сторону.

**Comment by Corak667** [comment]
Исключение при имени более 28 символов?

**Comment by pozitronik** [comment]
Нет. Вообще при любом, причину нашёл, фикс будет.
Зависание тоже, кстати, получилось, но с ним пока разбираюсь.

**Comment by pozitronik** [comment]
Проверяй на мастер-сборке, у меня больше не воспроизводится.

**Comment by Corak667** [comment]
Проверил, починено) Реально теперь не повторяется!
Спасибо!)
