### ISSUE TITLE
"error: parsing auth token" ошибка при попытке входа в одно из моих облаков

### ISSUE THREAD

**Issue by Corak667** [pozitronik/CloudMailRu#182]
"error: parsing auth token" ошибка при попытке входа в одно из моих облаков
http://picsee.net/upload/2018-04-08/4fb65117ca4f.png

Login to mrakoook@list.ru
error: parsing auth token for mrakoook@list.ru

```
---------------------------
Total Commander 9.12
---------------------------
Exception in MailRuCloud.wfx:FsFindFirstW!
Access violation at address 02A967A7. Read of address 00000020
Windows XP SP3 5.1 (Build 2600), base: 00400000

Windows exception: C0000005
Stack trace:
02A967A7
>0055942B  005594C2  005595AD  0044A6AA  0042728E  00449C4C
0042728E  004498B7  0044958B  0045DC92  0044965A  004496BD
004E72B4  004E7782  004E7C0C  004D4D47  004E24CC  00449BA2
0042728E  0044A6AA  0042728E  00449C4C  0042728E  0045DCE6
004EC4EB  004D6D00  0057A82C  0044B1E7  0044ED10  004486A9
00449D16  0044A6AA  0042728E  00449C4C  0042728E  0042CA0D
0042CAA8  
Raw:
004020A2  00402226  00402249  0041805C  00417CE9  004180BC
00420057  00420055  00540042  0055942B  0055947D  00470051
005A002C  005A002C  00420057  00420055  005594C2  005595AD
00468A07  00449BA2  0042728E  00468A3C  0042728E  00449BA2
0042728E  004E5F70  0044AA23  004486A9  00449D16  0044A6AA
0044A6CD  0042728E  00449C4C  0042728E  004498B7  00449561
0044958B  0045DC92  0044965A  00449676  004496BD  004E5C69
004E61BD  00449BA2  0042728E  004135C8  0044AA23  004486A9
0044A979  00449D16  0044A6AA  0044A6CD  0042728E  00449C4C
0042728E  004E72B4  00449BA2  0042728E  0044AA23  004486A9

```

Через веб нормально.
Шара например:
https://cloud.mail.ru/public/49ye/UmCQTCqL3

**Comment by Corak667** [comment]
Пересоздал - нормально. Влияли настройки:
было:
[Games2-Str]
email=mrakoook@mail.ru
password=??????
tc_pwd_mngr=0
unlimited_filesize=0
split_large_files=0
twostep_auth=0
public_account=0
public_url=
description=
encrypt_files_mode=0
encrypt_filenames=0


Пересоздал:
[Corak2]
email=mrakoook@mail.ru
password=??????
tc_pwd_mngr=0
unlimited_filesize=0
split_large_files=0
twostep_auth=0
public_account=0
public_url=
description=
encrypt_files_mode=0
encrypt_filenames=0

**Comment by pozitronik** [comment]
1) Когда уже научишься репорты по форме прикладывать?
2) Проблема, так понимаю, в имени соединения?

**Comment by Corak667** [comment]
1. Фиг знает, я просто затираю форму нафиг и пишу по своему, так проще и быстрее. А там было что-то весомое для репорта?
2. Не совсем имя - скорее то, что у меня в обоих именах соединения использовались те же самые мейлы и пароль, (при этом заходил в оба и отметил что они одинаковы)...
я это заметил и заменил мейл и пароль во 2м, попытался зайти и оно выдает такую ошибку. Перезагружал тотал - такая же ошибка. И только когда создал новое имя соединения - оно нормально прошло и тот который вызывал ошибку парсинга - тоже проходит.
Так что видимо где-то в SSL или еще где оно что-то запоминает если имя соединения было то же что и прошлое...

**Comment by pozitronik** [comment]
[Прочти пожалуйста](https://github.com/pozitronik/CloudMailRu#%D0%9A%D0%B0%D0%BA-%D0%B8-%D0%BA%D1%83%D0%B4%D0%B0-%D0%BF%D1%80%D0%B0%D0%B2%D0%B8%D0%BB%D1%8C%D0%BD%D0%BE-%D0%B6%D0%B0%D0%BB%D0%BE%D0%B2%D0%B0%D1%82%D1%8C%D1%81%D1%8F-%D0%BD%D0%B0-%D0%BF%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D1%8B).
Это не просто так написано.

Если бы ты приложил лог, возможно я увидел бы в нём какие-то признаки ошибки. Где и как взять лог, в документации написано.
