### ISSUE TITLE
Не входит в директории корзины .trash (парсит обычный вход, вместо списка удаленных)

### ISSUE THREAD

**Issue by Corak667** [pozitronik/CloudMailRu#183]
Хотел вернуть один файл, но сейчас не входит в директории корзины .trash
Видит только корневую папку в облаке, но ни в одну не входит.
В логе тоже ничего не видно (поставил на LogLevel=63).
```
CONNECT \Games1-Act
Login to *********@list.ru
Requesting auth token for *********@list.ru
Parsing token data...
Connected to *********@list.ru
Total space: 1024 Gb, used: 839 Gb, free: 184 Gb.

```
По идее там должен быть лист удаленных, но его нету, вместо него выдает будто стандартный вход в облако.

**Comment by pozitronik** [comment]
Исправлено, проверь.

**Comment by Corak667** [comment]
Проверил, да, исправлено, спасибо!

Удаленные тоже отлично видит:
http://picsee.net/upload/2018-04-19/e57d6c04c669.png
(кстати если попытаться войти/enter в удаленные каталоги, то никакого сопоставленного действия, только если в свойства alt+enter, возможно это поведение тоже стоило бы потом изменить)
По шарам отлично: 
http://picsee.net/upload/2018-04-19/db34f210ac36.png

**Comment by pozitronik** [comment]
>кстати если попытаться войти/enter в удаленные каталоги, то никакого сопоставленного действия, только если в свойства alt+enter, возможно это поведение тоже стоило бы потом изменить на стандартное для удаленных директорий

Это некорректируемое поведение, описанное в документации.

**Comment by Corak667** [comment]
Да видел, просто думал есть какие-то варианты) Ну ладно, мелочи
