### ISSUE TITLE
Функция показа .shared (список ссылок) - показывает только доступные шары в корневом каталоге

### ISSUE THREAD

**Issue by Corak667** [pozitronik/CloudMailRu#184]
Функция показа .shared (список ссылок) - показывает только доступные шары в корневом каталоге (хотя у меня их валом внутри)
http://picsee.net/upload/2018-04-11/f8fb6d891308.png
Видимо аналогично:
https://github.com/pozitronik/CloudMailRu/issues/183

Подозреваю что с .invites тоже проблема, хотя я ими не пользуюсь и проверить не могу...

**Comment by pozitronik** [comment]
same as #183
