### ISSUE TITLE
eldSocketError ошибка сети: #10054 Connection reset by peer при отправке данных

### ISSUE THREAD

**Issue by userosos** [pozitronik/CloudMailRu#185]
[wcftplog.txt](https://github.com/pozitronik/CloudMailRu/files/2065121/wcftplog.txt)

- Total Commander x64 9.12
- Windows 10 x64
- v03042018. 
https://github.com/pozitronik/CloudMailRu/blob/master/MailRuCloud.wfx64 - так же реагирует.
- Копирую фаил около 7 Гб на меил.ру диск, архив 7z.
- Не копируется фаил, выскакивает ошибка:
Error uploading file
путь\до\файла
Continue operation?
eldSocketError ошибка сети: #10054 Connection reset by peer при отправке данных

**Comment by pozitronik** [comment]
Удаётся ли скопировать файл размера, меньше, чем 2 Гб?

**Comment by userosos** [comment]
@pozitronik исправил с помощью:
Override split file size to = 2000000000
