### ISSUE TITLE
EIdReadTimeout при скачивании

### ISSUE THREAD

**Issue by MeteorBurn** [pozitronik/CloudMailRu#186]
При скачке папки из облака часто появляется ошибка EIdReadTimeout
Read Time Out при получении данных с адреса.

Работаю через прокси. Пробовал, как через HTTP, так и через SOCKS.

После нескольких "повторов" скачивание продолжается, но затем вновь возникает с новыми файлами.

Как решить, подскажите?

**Comment by pozitronik** [comment]
1. Поиграться с параметром [таймаута](https://github.com/pozitronik/CloudMailRu#network-operations-timeout-ms). Посмотреть, будут ли изменения.
2. Проверить доступность тех же файлов повторно. Т.е. "застряло" на каком-то файле - останавливаем операцию, и пытаемся скопировать конкретно его.
3. Если воспроизводится на каких-то конкретных файлах - пробуем повторить операцию без прокси/с другим прокси. Если и там те же траблы - пишите, будем разбираться конкретнее, если нет - проблема, вероятно, на сетевой стороне, можно попробовать решить увеличением количества повторных запросов при ошибках скачивания.

**Comment by MeteorBurn** [comment]
Повысил таймаут и увеличил повторное количество скачиваний при ошибке без вывода диалогового окна.
Какое значение таймаута посоветуете?

Благодарю за ответ.

**Comment by pozitronik** [comment]
>Какое значение таймаута посоветуете?

Это значение нужно подбирать эмпирически, в зависимости от качества соединения.
