### ISSUE TITLE
Не работает скачивание с облака, везде "Redirection limit" 

### ISSUE THREAD

**Issue by Corak667** [pozitronik/CloudMailRu#187]
Не работает скачивание с облака, везде "Redirection limit", Try another shard?
http://imagizer.imageshack.com/img921/2396/Nr2pgR.png

"Shard received: https://cloclo3.datacloudmail.ru/get/
Redirection limit reached when trying to download https://cloclo3.datacloudmail.ru/get/exua_backup2_Games/Games/0jRPG/151%20Tentacles/info.txt"

"
Shard received: https://cloclo14.datacloudmail.ru/get/
Redirection limit reached when trying to download https://cloclo14.datacloudmail.ru/get/exua_backup5_music_games/Music/0Unsort/0BackupVK/playlist1.xml
"

Загрузка на облако вроде нормально

**Comment by Corak667** [comment]
upd: Прошло, но только после перезагрузки системы (XP). Перезапуск TC ничего не давал. 
На 7рке тоже выдавало ошибку скачивания, но без "Redirection limit", тоже прошло, но без перезагрузки.

**Comment by pozitronik** [comment]
Issue #18
