### ISSUE TITLE
Access violation при добавлении пароля шифрования

### ISSUE THREAD

**Issue by SchwarzKopf-M** [pozitronik/CloudMailRu#188]
Решил обновиться... Но при установке пароля выдаётся ошибка. Тотал 64. На 32-битке такой ошибки нет. Немного соврал... На 32 при установке пароля ошибка.

![default](https://user-images.githubusercontent.com/1192230/43610092-defd5fc2-9694-11e8-887d-d52984a7dcb8.png)

![3](https://user-images.githubusercontent.com/1192230/43610628-3311e83e-9696-11e8-9a84-5b315e209ef1.png)

**Comment by pozitronik** [comment]
Не могу воспроизвести.
Нужна пошаговая последовательность действий.

**Comment by SchwarzKopf-M** [comment]
Можно поставить "всегда шифровать", кнопка "установить пароль", ввести любой пароль и нажать "ОК" и сразу можно это видеть. На 64-битном тотале вскакивает окно, а при отладке 32-битного, видно что и как происходит. И ещё заметил что в файле настроек строка CryptedGUID_files шифруется в секции "[]" вместо того чтобы в секции с названием учётной записи. Может так нужно...

**Comment by pozitronik** [comment]
Исправлено. Проблема была как раз в том, что неверно определялась учётная запись для шифрования.

**Comment by pozitronik** [comment]
Перепроверил - работает. Может быть бинарник не перезаписался (на всякий случай уточню - исправленные бинарники в master, а не в релизе), или что-то в этом духе?
Ещё, как вариант - покорежённый MailRuCloud.ini. Как называется аккаунт, для которого ставится пароль? Может быть в имя попал какой-то непредусмотренный символ.
На x32 работает, кстати?

**Comment by SchwarzKopf-M** [comment]
Я перекомпилировал сам. Но перепроверю на 32 и 64 ещё раз. Предварительно и инишка в порядке и имя на английском полностью. Специально возьму из master и перепроверю.

**Comment by SchwarzKopf-M** [comment]
При компиляции 3-битки, та-же ошибка в том-же самом месте. Но строка CryptedGUID_files сохраняется в нужной секции. И 64-битка так-же валится с окном сразу и как вредыдущей версии вообще не сохраняется строка CryptedGUID_files.

**Comment by pozitronik** [comment]
Нужно посмотреть содержимое MailRuCloud.ini, можно с удалёнными адресами и без паролей.

**Comment by SchwarzKopf-M** [comment]
Я всё равно пароль по своему шифрую. :)
[12345]
email=12345@mail.ru
password=нету
tc_pwd_mngr=0
unlimited_filesize=0
split_large_files=0
twostep_auth=0
public_account=0
public_url=
description=
encrypt_files_mode=1
encrypt_filenames=0
CryptedGUID_files=E4492FF3F1A15CB0F180874A950F5C064652B6CEE090011217E17458BAF7FD9CAB6EDC55FBF30331A70774B9030D2677

**Comment by pozitronik** [comment]
По прежнему не получается воспроизвести.
Этот виолейшен мог возникать, если в списке аккаунтов не был выбран ни один элемент. Я исключил эту ситуацию, и не вижу, куда можно копать дальше.

**Comment by SchwarzKopf-M** [comment]
Я не знаю... Запустил чистую виртуалку, установил с сайта тотал, без плагинов, без взлома, без ключей. Посчитал то ошибка из-за того что у меня последняя версия, специально установил версию 9. Запустил, установил плагин, ввёл любые данные, "Всегда", "Установить пароль", любая буква, кнопка "ОК" и результат сразу. Должно воспроизводиться... Случайные факторы мне кажется исключились. Не может-же это быть потому то у меня монитор квадратный. У всех квадратный. Проследил историю. Такая ошибка возникает с момента появления на форме кнопки "Set password" как таковой, до этого ошибки не бы
![default](https://user-images.githubusercontent.com/1192230/44473081-15847780-a61f-11e8-91a2-6dfd711a4634.png)
ло.

**Comment by pozitronik** [comment]
Забавно.
Сделал всё точь в точь по алгоритму - есть виолейшен.
Запустил под отладчиком дебаг-версию - нет виолейшена.
Но хотя бы есть, куда копать.

**Comment by SchwarzKopf-M** [comment]
Ну наконец-то. :) Я уж думая я какой-то не такой. :) Хорошо, ждёмс.

**Comment by pozitronik** [comment]
Патч в мастере, проверяй.

**Comment by pozitronik** [comment]
Разобрался, проверяй.

**Comment by SchwarzKopf-M** [comment]
Нет, всё так-же и на 32 и на 64.

**Comment by pozitronik** [comment]
Никаким образом не могу повторить.

Если есть возможность, то надо протрейсить [вот этот](https://github.com/pozitronik/CloudMailRu/blob/4f16da5002def243677c6b923f2ed24698cb4b20/TCPasswordManagerHelper.pas#L237) участок кода, от GetMem до FreeMem.

**Comment by SchwarzKopf-M** [comment]
Попробовал проделать эту процедуру... Прошёл цикл до появления окна, но при передачи фокуса окну опять проходит цикл и так по кругу и даже не получилось ввести пароль. Мож чё не так делал... К тому-же не зная принципа взаимодействия плагина с Тоталом и каких-то параметров которые должны быть, думаю вряд ли сделаю что-то полезное. По-моему только ты сам можешь с этим справиться. Тем более как-бы уже получил ошибку при отладке... Осталось только разобраться.

**Comment by pozitronik** [comment]
>Тем более как-бы уже получил ошибку при отладке... Осталось только разобраться.

С последним патчем ошибка уже никак не воспроизводится (проверено на нескольких машинах). Учитывая суть исправленной ошибки, это дало мне все основания считать, что она исправлена; потому и попросил оттрейсить код, чтобы получить хоть какую-то зацепку. Возможно, ошибка есть в каком-то другом месте, но я не вижу, в какм.

>Прошёл цикл до появления окна, но при передачи фокуса окну опять проходит цикл и так по кругу и даже не получилось ввести пароль.

Достаточно поставить точки останова на 241 и 248 строках TCPasswordManagerHelper.pas. Пошагово трейсить, в общем-то, не нужно, достаточно выяснить, падает ли (а если падает - то на какой именно из этих строк) плагин.

**Comment by SchwarzKopf-M** [comment]
Ну блин... :) Ошибка в любом случае у тебя должна появляться на любой машине. :)
Трассировка не к ему не приводит, AV вылазит в этой строке на уровне взаимодействия с Тоталом.
НО!!!
Твой вариант:

GetMem(buf, 1024);
  ZeroMemory(buf, 1024);
  WStrCopy(buf, PWideChar(CurrentPassword));

  if self.RequestHandleProc(RT_Password, PWideChar(Verb + ' пароля шифрования'), 'Новый пароль:', PWideChar(CurrentPassword), 1024) then
  begin
    CurrentPassword := buf;
    self.SetPassword(crypt_id, CurrentPassword);
    result := TFileCipher.CryptedGUID(CurrentPassword);
  end;

  FreeMem(buf);

А теперь мой:

  if self.RequestHandleProc(RT_Password, PWideChar(Verb + ' пароля шифрования'), 'Новый пароль:', buf, 1024) then

Как говорится найди свою ошибку. :) Долго я мучился, оказывается нельзя передавать пустую строку.
Исправь в Мастере и закрывай. :)

**Comment by SchwarzKopf-M** [comment]
Похоже то я уже не внимательный был... То что было уже исправлено "buf" я почему-то пропустил. Пардон. :) Спасибо.
