### ISSUE TITLE
Некорректное отображение информации о свободном/занятом пространстве

### ISSUE THREAD

**Issue by pozitronik** [pozitronik/CloudMailRu#189]
[Репорт](http://forum.wincmd.ru/viewpost.php?p=127891)

Причина: поменялись имена переменных в API.

**Comment by pozitronik** [comment]
Fixed at de7380e0c5223a74618996a288e4e2c4d9044cff

**Comment by pasha00000** [comment]
Приветствую.

После данного исправления перестали отображаться у всех файлов указана дата 01.01.1970 03:00, которая появилась и у папок, хотя её ранее не было. На версии v03042018 такого не наблюдается и отображаются верные даты. Тотал 9.21a, Win7x64.
На скриншоте наглядно видно:
![2018-09-08_022314](https://user-images.githubusercontent.com/43064642/45247217-f79d5f00-b30e-11e8-97c4-134c6380311d.png)

**Comment by pozitronik** [comment]
Исправлено.
