### ISSUE TITLE
Падение при соединении

### ISSUE THREAD

**Issue by pozitronik** [pozitronik/CloudMailRu#19]
[Репорт](http://forum.wincmd.ru/viewpost.php?p=117863).
Проблема [не воспроизводится](http://forum.wincmd.ru/viewpost.php?p=117868) на старом билде.

**Comment by pozitronik** [comment]
Не удаётся воспроизвести.

**Comment by 3soolo3** [comment]
От этого ошибка не исправилась.
Сегодня скачал свежий master - баг на месте

---------------------------
Total Commander 8.52
---------------------------
Exception in MailRuCloud.wfx:FsFindFirstW!
External exception EEDFADE
Windows 7 SP1 6.1 (Build 7601)

Windows exception: 0EEDFADE
Stack trace:
04A908F6
675200  >675C04  610624  4EB3C0  4EC264  656B01
446938  4467E5  447DC2  44671B  448B06  4467E5
448752  425B40  447CF7  425B40  447C65  425B40
447DC2  448752  425B40  447CF7  425B40  42B224
42B2C0  70687F  
Raw:
703ABB  6FC608  675200  4020A2  402249  4026A0
407919  6B82C7  6AC4EA  6AC4EA  6AEEFE  6AEF80
5DF0B9  5DF0B9  70399F  70388D  58A85B  703ABB
6FC608  703ABB  6FC608  7038A3  6729CA  5E2761
6C1E9C  6C1E9C  67C23C  7038A3  6729CA  5E2761
6C1E9C  674117  471467  6B7D62  61A7DA  61A7FD
703ABB  6FC608  4023EF  4026B8  7036C6  5DF8C7
402249  4033D0  4021C8  417968  4175F5  4179C8
675C04  471467  6B7D62  61A7DA  61A7FD  703ABB
6FC608  5E2761  6C1E9C  6C1E9C  704693  70399F

**Comment by 3soolo3** [comment]
Интернет у меня на компе через шлюз.
Может быть это влияет

**Comment by pozitronik** [comment]
Воспроизвести по прежнему не удаётся, пока не понятно, в какую сторону копать.

**Comment by 3soolo3** [comment]
Может ли влиять то, что интернет через шлюз?
Думаю, нужна сборка с флагами, чтобы узнать на каком именно этапе обрыв

**Comment by pozitronik** [comment]
Я подготовлю тестовую сборку в отдельной ветке.

**Comment by pozitronik** [comment]
Ошибка возникает при открытии плагина (отображении списка аккаунтов) или при входе в аккаунт?

**Comment by 3soolo3** [comment]
При попытке входа. Список аккаунтов отображается нормально

**Comment by pozitronik** [comment]
1. Возьмите бинарники [отсюда](https://github.com/pozitronik/CloudMailRu/tree/debug).
2. Воспроизведите ошибку.
3. Скопируйте сюда (или в личку на форуме) содержимое лога (он будет где-то в %temp%\\_tc\\). Адрес ящика можно стереть, он роли не сыграет.

По логу я пойму, на каком месте сыпется.

**Comment by 3soolo3** [comment]
По умолчанию у меня никаких файлова не создаётся
Как ни бился - не смог настроить создание файла
Переписал вручную:

DEBUG: Section init
DEBUG: Accounts list
DEBUG: Found 1 accounts
DEBUG: Section free
DEBUG: Extracting real path from \soolo3
DEBUG: Reding remote dir
CONNECT soolo3@mail.ru
Login to soolo3@mail.ru
Recuesting auth token for soolo3@mail.ru
Connected to soolo3@mail.ru
Total space: 102400Mb, used: 1Mb, free 102399 Mb

На этом этапе вываливается окно ошибки
При попытке ещё раз войти в папку soolo3 выдаёт ещё 2 строчки:

DEBUG: Extracting real path from \soolo3
DEBUG: Reding remote dir

В общем, дальше списка аккаунтов плагин не ходит

**Comment by pozitronik** [comment]
Насчёт файл: как только откроешь список соединений в дебажной версии, откроется панельска с протоколом. Даблклик по ней откроет просмотрщик с этим файлом, в нём можно будет посмотреть путь к файлу (и после падения TC найти его).
Кое-какие намётки появились, будет ещё одна отладочная версия.

**Comment by pozitronik** [comment]
Ещё раз по тому же алгоритма пожалуйста.

**Comment by 3soolo3** [comment]
DEBUG: Section init
DEBUG: Accounts list
DEBUG: Found 1 accounts
DEBUG: Section free
DEBUG: Extracting real path from \soolo3
DEBUG: Reading remote dir
CONNECT soolo3@mail.ru
Login to soolo3@mail.ru
DEBUG: SSL create
DEBUG: HTTP create
DEBUG: Cookie attaching
DEBUG: SSL attaching
Requesting auth token for soolo3@mail.ru
DEBUG: Getting 
DEBUG: HTTP init
DEBUG: SSL create
DEBUG: HTTP create
DEBUG: Cookie attaching
DEBUG: SSL attaching
DEBUG: HTTP init done, requesting...
DEBUG: requesting done, server answer: <!DOCTYPE html><html xmlns="http://www.w3.org/1999/xhtml"><head><meta charset="utf-8"/><meta http-equiv="Content-Type" content="text/html; charset=utf-8"/><meta http-equiv="X-UA-Compatible" content="IE=edge"/><link rel="shortcut icon" type="image/png" href="https://img.imgsmail.ru/cloud/img/build/release_CLOUDWEB-6886_37-0-1.201608081742/favicon32x32.png"/><script>if ( window.devicePixelRatio >= 2 ) {
					document.head.insertAdjacentHTML('beforeend', '\u003Clink rel="shortcut icon" type="image/png" href="https:\/\/img.imgsmail.ru\/cloud\/img\/build\/release_CLOUDWEB-6886_37-0-1.201608081742\/favicon64x64.png" /\u003E');
				}</script><link rel="apple-touch-icon" size="64x64" href="https://img.imgsmail.ru/cloud/img/build/release_CLOUDWEB-6886_37-0-1.201608081742/favicon64x64.png"/><sDEBUG: Freeing HTTP
Connected to soolo3@mail.ru
DEBUG: Getting 
DEBUG: HTTP init
DEBUG: SSL create
DEBUG: HTTP create
DEBUG: Cookie attaching
DEBUG: SSL attaching
DEBUG: HTTP init done, requesting...
DEBUG: requesting done, server answer: {"email":"soolo3@mail.ru","body":{"overquota":false,"used":1,"total":102400},"time":1470749035694,"status":200}
DEBUG: Freeing HTTP
Total space: 102400Mb, used: 1Mb, free: 102399Mb.
DEBUG: Getting 
DEBUG: HTTP init
DEBUG: SSL create
DEBUG: HTTP create
DEBUG: Cookie attaching
DEBUG: SSL attaching
DEBUG: HTTP init done, requesting...
DEBUG: requesting done, server answer: {"email":"soolo3@mail.ru","body":{"count":{"folders":1,"files":3},"tree":"623865646562363030303030","name":"/","grev":4,"size":1616447,"sort":{"order":"asc","type":"name"},"kind":"folder","rev":4,"type":"folder","home":"/","list":[{"count":{"folders":0,"files":0},"tree":"623865646562363030303030","name":"Camera Uploads","grev":3,"size":0,"kind":"camera-upload","rev":3,"type":"folder","home":"/Camera Uploads"},{"mtime":1409429932171,"virus_scan":"pass","name":"Screenshot_2014-08-30-23-18-52.png","size":775122,"hash":"83B96F4EF60B0983D0E963F7B4EE3E026788C612","kind":"file","weblink":"927c40ead9c0/Screenshot_2014-08-30-23-18-52.png","type":"file","home":"/Screenshot_2014-08-30-23-18-52.png"},{"mtime":1409429958418,"virus_scan":"pass","name":"Screenshot_2014-08-30-23-19-18.png","size":773606,"hash":"CED0860B5B1FDAEB43DDA9504811E89B5069C834","kind":"file","weblink":"3d05e5b305f5/Screenshot_2014-08-30-23-19-18.png","type":"file","home":"/Screenshot_2014-08-30-23-19-18.png"},{DEBUG: Freeing HTTP
DEBUG: getDirListingFromJSON {"email":"soolo3@mail.ru","body":{"count":{"folders":1,"files":3},"tree":"623865646562363030303030","name":"/","grev":4,"size":1616447,"sort":{"order":"asc","type":"name"},"kind":"folder","rev":4,"type":"folder","home":"/","list":[{"count":{"folders":0,"files":0},"tree":"623865646562363030303030","name":"Camera Uploads","grev":3,"size":0,"kind":"camera-upload","rev":3,"type":"folder","home":"/Camera Uploads"},{"mtime":1409429932171,"virus_scan":"pass","name":"Screenshot_2014-08-30-23-18-52.png","size":775122,"hash":"83B96F4EF60B0983D0E963F7B4EE3E026788C612","kind":"file","weblink":"927c40ead9c0/Screenshot_2014-08-30-23-18-52.png","type":"file","home":"/Screenshot_2014-08-30-23-18-52.png"},{"mtime":1409429958418,"virus_scan":"pass","name":"Screenshot_2014-08-30-23-19-18.png","size":773606,"hash":"CED0860B5B1FDAEB43DDA9504811E89B5069C834","kind":"file","weblink":"3d05e5b305f5/Screenshot_2014-08-30-23-19-18.png","type":"file","home":"/Screenshot_2014-08-30-23-19-18.png"},{"mtime":14

**Comment by pozitronik** [comment]
Парсер съедает содержимое лога, пришлите файл в почту nospamloud at gmail dot com

**Comment by 3soolo3** [comment]
Да вроде ничего не срезается
Отправил 2 лога
Первый файл при первой попытке соединения, второй - вторая попытка соединиться после закрытия окна с ошибкой.

**Comment by pozitronik** [comment]
Ага, не срезается. Видимо, внутренний логгер TC имеет ограничения на размер записываемой строки. Подсуну свой, надо будет повторить.

**Comment by pozitronik** [comment]
Переписал логгер. Теперь протокол будет сыпаться в файл debug.log в каталоге, куда установлен плагин. Его нужно будет прислать на почту или прикрепить к сообщению здесь.

**Comment by 3soolo3** [comment]
Отправил на почту, уж очень страшный там лог ))

**Comment by pozitronik** [comment]
Попробуйте обновление из master.
Проблема в том что для пары файлов возвращалось неожиданное время модификации, парсер пытался запихнуть его в integer, и падал. Я поменял формат хранения времени, теперь не падает, но для этих файлов время может показываться некорректно.

**Comment by pozitronik** [comment]
Пожалуйста.
Мне бы помогла информация о том, какая дата изменения у этих файлов должна быть на самом деле.

**Comment by 3soolo3** [comment]
Не знаю, мой ли это телефон прикольнулся, или Облако прикольнулось, но вот, например:
21/01/46633 13:29
![default](https://cloud.githubusercontent.com/assets/16206472/17522745/db76ee18-5e60-11e6-92cc-05d5f1c45d61.png)

**Comment by pozitronik** [comment]
Оригиналов файлов нет (посмотреть даты на них)? Заливка была через браузер или каким-то клиентом?

**Comment by 3soolo3** [comment]
Реальные даты в названии.
Оригиналов не осталось.
Загружал, предположительно, клиентом Облака для Андроид

**Comment by pozitronik** [comment]
Ок, спасибо.
