### ISSUE TITLE
Заливка файла в облако по хешу

### ISSUE THREAD

**Issue by 1yura** [pozitronik/CloudMailRu#190]
Предлагаю расширить функционал команды clone. Если там параметр вида hash\*size\*fileName то "заливаем" файл по хешу. Полезная вещь для спасения файлов на случай блокировки аккаунта.
Я указал параметр size, поскольку уже существующая функция TCloudMailRu.addFileToCloud это требует. Но если можно без него обойтись - еще лучше. fileName - может быть опциональным, если не указан - то можно использовать хеш в качестве имени.
Поскольку сейчас команда clone принимает ссылки (типа https://..), по первому символу параметра можно сказать - это ссылка или нет, т.к. хеш не может начинаться с "h". 
Также было бы полезно при настоящей заливке файлов в облако иметь лог, в котором бы были эти самые строки hash\*size\*fileName, чтобы при необходимости были под рукой.

**Comment by pozitronik** [comment]
Сделал отдельную команду `hash`
Формат: `hash "hash:size:name"` или `hash hash:size`. Кавычки нужны, если в имени файла есть пробелы.
В окне свойств файлов появилось поле, в котором отображается команда в нужном формате.

Размер файла указывать обязательно, он требуется API, видимо во избежание коллизий.
Над логированием нужно подумать.

**Comment by 1yura** [comment]
Спасибо, работает отлично!

**Comment by areht** [comment]
> В окне свойств файлов появилось поле, в котором отображается команда в нужном формате.

А сдампить это можно?

**Comment by pozitronik** [comment]
Можно поиграться с набором колонок, вывести туда нужные поля, и скопировать стандартной командой TC.

**Comment by areht** [comment]
> Можно поиграться с набором колонок, вывести туда нужные поля, и скопировать стандартной командой TC.

Но это только если внутри одной папки, дерево так не получится?

**Comment by pozitronik** [comment]
Дерево не получится. Могу в свойства каталога добавить генерацию такого дампа, но тогда нужна и обратная команда, а это чуть сложнее.
Заводите тикет, если нужна такая штука.

**Comment by pozitronik** [comment]
Доработал инструментарий:
1. Имя файла в команде можно указывать с путем, он будет воссоздан относительно текущего каталога.
2. В диалоге свойств файлов появилась вкладка Hashes list. В ней можно получить рекурсивный список хеш-команд для текущего каталога (для файла тоже работает), сохранить или загрузить список. Там же можно загруженный список применить.
3. Ранее сделанное поле с командой убрал - список хешей полностью перекрывает его функцию.

Нужно протестировать.

**Comment by 1yura** [comment]
Всё работает хорошо, спасибо! Если применить загруженный список, то видимых изменений в текущей директории не происходит, файлы появляются после ctrl+R.  Но это мелочь.

**Comment by pozitronik** [comment]
Добавил обновление панели после выполнения команды.
