### ISSUE TITLE
Переопределение сервера выгрузки

### ISSUE THREAD

**Issue by KGB-USSR** [pozitronik/CloudMailRu#193]
Возможно ли в настройках плагина переопределять конкретный сервер выгрузки, например cloclo39-upload.cloud.mail.ru, по аналогии с ключом shard_override. 
Дело в том, что не все сервера облака Mail.ru позволяют выгружать контент на максимальной тарифной скорости, идут провалы до 10-20 Мбит/c (при тарифной 100 Мбит/c), что существенно увеличивает время аплоада.

**Comment by pozitronik** [comment]
Сделал ключ `upload_url_override`
На серверной стороне такая подмена не прокатывает, при попытке аплоада переопределённый сервер отвечает [кодом 418](https://developer.mozilla.org/ru/docs/Web/HTTP/Status/418).
Ключ (без документирования) в коде оставлю, может пригодиться для отладки.
