### ISSUE TITLE
[bug] Невозможно остановить сканирование листа хешей или прямых ссылок

### ISSUE THREAD

**Issue by Corak667** [pozitronik/CloudMailRu#195]
Пытался щас получить список ссылок файлов для расшаренной директории - и сразу остановить процесс сканирования. Остановка не работает ни в случае получения хешей ни прямых ссылок (Download Links и Hashes list). Помогает только полное прерывание процесса TC
http://imagizer.imageshack.com/img923/1962/UjosL1.png

**Comment by pozitronik** [comment]
Проверяй.

**Comment by Corak667** [comment]
Проверил, работает и очень шустро! Спасибо!
