### ISSUE TITLE
2 factor code not saving, every time asking when login

### ISSUE THREAD

**Issue by karb10** [pozitronik/CloudMailRu#196]
### Сообщаешь о проблеме?

Сначала прочти [FAQ](https://github.com/pozitronik/CloudMailRu#%D0%A7%D0%B0%D1%81%D1%82%D0%BE-%D0%B7%D0%B0%D0%B4%D0%B0%D0%B2%D0%B0%D0%B5%D0%BC%D1%8B%D0%B5-%D0%B2%D0%BE%D0%BF%D1%80%D0%BE%D1%81%D1%8B). Внимательно прочти.

Прочёл, но проблема ещё не решилась?

Тогда **обязательно** сообщи:
- Версию и разрядность Total Commander, на которой воспроизводится проблема.
- Версию и разрядность операционной системы, на которой воспроизводится проблема.
- Номер сборки плагина, на которой воспроизводится проблема. **Обязательно** убедись, что проблема воспроизводится в самой свежей бинарной сборке ([x32](https://github.com/pozitronik/CloudMailRu/blob/master/MailRuCloud.wfx)/[x64](https://github.com/pozitronik/CloudMailRu/blob/master/MailRuCloud.wfx64)).
- Пошаговую последовательность действий, при которой воспроизводится проблема, даже если она кажется очевидной. Если однозначно выявить такую последовательность не получается - пиши, как есть, будем разбираться.
- Как проявляется проблема? Опиши словами, скриншот я спрошу, если потребуется.
- **Обязательно** - протокол соединения (не копируй его содержимое, приложи файл).

Без этой информации найти и решить проблему будет трудно, не трать моё и своё время. Спасибо.

### Предлагаешь улучшение?

Проверь [существующие тикеты](https://github.com/pozitronik/CloudMailRu/issues?utf8=%E2%9C%93&q=label%3Aenhancement). Если идея ещё не предлагалась - пиши в свободной форме.

**Comment by pozitronik** [comment]
No clear problem description provided.
