### ISSUE TITLE
Инструкция для компиляции

### ISSUE THREAD

**Issue by OmlineEditor** [pozitronik/CloudMailRu#198]
Добавьте инструкцию как правильно скомпилировать вашу программу.
Я например очень плохо знакома с паскалем, инструкция бы очень  пригодилась.

**Comment by darkieua** [comment]
Поддерживаю, инструкция была бы очень кстати.

**Comment by pozitronik** [comment]
Собственно, инструкция укладывается в три пункта:

1. Ставим Embarcadero RAD Studio версии 10+ (должно собираться на любой подверсии);
2. Открываем MailRuCloud.dproj;
3. F9.

*.wfx/wfx64 - это *.dll-файлы, отлаживаются они аналогично.

**Comment by pozitronik** [comment]
done at 1931e8287240f9fcb320c44aa1668163a0d41dea
