### ISSUE TITLE
Пакетное создание публичных ссылок

### ISSUE THREAD

**Issue by KhamzinR** [pozitronik/CloudMailRu#199]
Прошу рассмотреть возможность пакетного формирования публичных ссылок на выделенные файлы или папки. Например, выделяю список файлов или папок, формируем пакетно на них ссылки и выводим в виде списка или текстового документа все ссылки+файлы/папки:
files1.avi - link1.cloud.mail.ru
files2.avi - link2.cloud.mail.ru
dir3 - link3.cloud.mail.ru
dir4 - link4.cloud.mail.ru

**Comment by pozitronik** [comment]
Интерфейс плагинов не позволяет получить список выделенных объектов, к сожалению.
