### ISSUE TITLE
Файл pluginst.inf

### ISSUE THREAD

**Issue by Hooter** [pozitronik/CloudMailRu#20]
нужно добавить файл _pluginst.inf_ чтобы плагин устанавливался автоматически
`[plugininstall]
description=CloudMailRu 07072016 (32bit+64bit)
type=wfx
file=MailRuCloud.wfx
defaultdir=CloudMailRu
version=07072016
`

**Comment by pozitronik** [comment]
Есть ли способ делать на гихабе релизы в архиве без подкаталогов? Иначе смысл pluginst.inf теряется, а готовить релизные архивы вручную я не хочу.

**Comment by FazZzuR** [comment]
Я для своей небольшой софтины писал release.bat. Который компилил, копировал все ини и файлы ресурсов, паковал все это в архив и архив в папку /compiled. В итоге релиз последней версии делался в два клика - запуск бат файла, и отправка коммита на гитхаб. Хотя и отправку коммита можно было в бат засунуть, но у меня нужды такой не было =)

**Comment by pozitronik** [comment]
Меня интересуют именно релизы на github. Понятное дело, что я могу автоматизировать сборку релиза как отдельного файла (возможно, так и поступлю, если не найду альтернатив), но хотелось бы использовать стандартный функционал.

**Comment by velikodniy** [comment]
Вообще держать исходники и бинарники в одной куче не очень удобно. Лучше сделать скрипт для релизов. Тем более, у них есть [удобный API](https://developer.github.com/v3/repos/releases/). Через этот же API можно к релизу прикреплять дополнительные файлы. Так что можно одним скриптом/программой публиковать релиз сразу с zip-архивами с плагином под разные архитектуры.

**Comment by pozitronik** [comment]
Похоже, это то, что требуется, спасибо!

**Comment by pozitronik** [comment]
Добавил автоинсталл в последний релиз.
