### ISSUE TITLE
(Feature request) Хэш сумма в свойствах файла (по Alt+Enter)

### ISSUE THREAD

**Issue by OmlineEditor** [pozitronik/CloudMailRu#200]
Можно ли добавить в свойства файла (вызываемые по нажатию Alt+Enter) хэш сумму этого файла? Было бы очень полезно и информативно.

**Comment by pozitronik** [comment]
Она есть на вкладке hashes list.

**Comment by OmlineEditor** [comment]
hashes list есть если смотреть папку, а для одного файла нету.
