### ISSUE TITLE
Просмотр видео без скачки. Потоковое видео.  

### ISSUE THREAD

**Issue by OmlineEditor** [pozitronik/CloudMailRu#201]
Сейчас для просмотра видео его нужно полностью скачать (в temp папку) и только потом его можно смотреть. В самом облаке через web интерфейс можно сразу без скачки начать смотреть видео. Можно ли сделать возможность просмотра видео без полной скачки, как например по локальной сети с соседнего компьютера.

**Comment by Twillo** [comment]
Есть такой не трудный способ. Скачиваете VLC Player или PotPlayer, в Total Commander'е нажимаете правой кнопкой на видео которое хотите смотреть и заходите в свойства. Ставите галочку на "Public Access Enabled", внизу где пишет "Download links" появится длинная ссылка (не путайте с "Public Link"). Копируете ссылку, в плеере заходите Медиа > Открыть URL, вставляете ссылку и нажимаете воспроизвести.
![2019-01-10_183535](https://user-images.githubusercontent.com/46563729/50968889-c7f1a400-1506-11e9-9d54-5da1e17ddba7.png)
![2019-01-10_183655](https://user-images.githubusercontent.com/46563729/50968890-c7f1a400-1506-11e9-8312-b46a3364517d.png)
