### ISSUE TITLE
(Bug) Неверно показывает имя копируемого файла

### ISSUE THREAD

**Issue by OmlineEditor** [pozitronik/CloudMailRu#202]
При копировании нескольких файлов одновременно в облако, в окошке копирования не верное показывается имя копируемого файла. Показывается во всех окошках одно и тоже имя и это имя последнего файла что поставлено на копирование. Вот на примере виден только 5й файл, а на самом деле копируется 3й, 4й, 5й:
[![bugMail.png](https://i.postimg.cc/63HpH8zJ/bugMail.png)](https://postimg.cc/TLDx1YZC)
------
Total Commander x32 v9.21a
Win 7 x64
Номер сборки плагина x32 v28122018

**Comment by pozitronik** [comment]
Это проблема TC, а не плагина.
