### ISSUE TITLE
(Feature request) Показ размера облака на панельке TC

### ISSUE THREAD

**Issue by OmlineEditor** [pozitronik/CloudMailRu#203]
Сейчас нельзя видеть размер облака на панеле. Для простого диска размер виден, но для облака размер только в логах. Добавьте размер облака на панель. Пример (кликните на картинку чтобы посмотреть крупнее):
[![mailspace.png](https://i.postimg.cc/8c9W0KwS/mailspace.png)](https://postimg.cc/ZvPC9L17)

**Comment by pozitronik** [comment]
Интерфейс плагинов не поддерживает эту возможность.
