### ISSUE TITLE
(Feature request) Параллельные загрузки в облако

### ISSUE THREAD

**Issue by OmlineEditor** [pozitronik/CloudMailRu#204]
Загрузка данных в облако почему идет довольно медленно, до 10 Мбит/с (1,2 Мбайта/с). Можно ли сделать параллельные загрузки если файлов очень много? тогда загрузка будет идти намного быстрее. В настройках можно сделать опцию если для загрузки два и более файлов то грузить их в "N" потоков, где N можно менять пользователю самостоятельно. Загрузка в несколько раз быстрее это очень полезная опция, особенно если файлов много.
Я пробовала грузить в 5 потоков, вроде нормально, время загрузки сократилось в 5 раз:

[![speed.png](https://i.postimg.cc/t4YCB3MX/speed.png)](https://postimg.cc/PCnjxwHc)

**Comment by pozitronik** [comment]
Один файл в несколько потоков - нельзя.
Несколько файлов в несколько потоков - только вручную. Я подумаю над возможностями автоматического распараллеливания загрузок, но обещать ничего не могу.

**Comment by pozitronik** [comment]
Автоматическое распараллеливание труднореализуемо, если реализуемо вообще. Придётся делать какую-то сложную прослойку, не только выполнящую разбитие задач на потоки и контроль за ними, но и скрывающую от TC этот процесс (для него каждая задача атомарна и должна такой оставаться).
С учётом того, что это легко делается руками - оно того не стоит.

**Comment by OmlineEditor** [comment]
Хорошо, тогда будет делать распараллеливание руками.
