### ISSUE TITLE
Сохранение структуры и метаданных из облака в файл

### ISSUE THREAD

**Issue by pozitronik** [pozitronik/CloudMailRu#205]
Обсуждение инициировано [тут](http://forum.wincmd.ru/viewtopic.php?p=129079#129079).

**Comment by pozitronik** [comment]
Вариант решения: делать по запросу снапшот структуры облака в указанный каталог. Внутри снапшота - JSON от API (если можно получить полную структуру)/либо генерируемый обходом.
В плагине дать возможность входить в эти снапшоты как в псевдокаталоги (вместо загрузки с сервера отдавая JSON снапшота). Тему можно развить до сравнения с текущей структурой/восстановления удалённых файлов по хешу и т.д.

**Comment by OmlineEditor** [comment]
Если вы сможете сделать образ того что лежит в облаке, это будет просто шикарно. Если у меня есть много музыки или сериалы в облаке тогда я могу сделать образ того что лежит в облаке, передать кому либо образ и он сможет мгновенно у себя в облаке создать нужные файлы, это намного лучше и проще чем давать ссылки на кучу папок. Я надеюсь вы это сделаете в ближайщее время.

**Comment by pozitronik** [comment]
Это уже есть. Вкладка Hashes list в свойствах файла/каталога. Получаем хеши, передаём кому надо. Их можно вставить прям там же списком, нажать кнопку ☑, плагин восстановит структуру из хешей в текущем расположении.

**Comment by OmlineEditor** [comment]
Сделайте всплывающие подсказки над всеми кнопками в свойствах файла/каталога. Не понятно что за кнопки и зачем они нужны. И в свойствах одного файла нет его хэш суммы. Как получить для одного файла хэш?

**Comment by pozitronik** [comment]
>И в свойствах одного файла нет его хэш суммы.

Как же нет, когда есть?

**Comment by pozitronik** [comment]
Подсказки добавлены. Сохранение структуры отдельно делать не стану - списка хешей достаточно.
