### ISSUE TITLE
Ошибки при паралелльных загрузках

### ISSUE THREAD

**Issue by OmlineEditor** [pozitronik/CloudMailRu#207]
Total Commander 9.21a X86
Windows 7 X64
CloudMailRu v28122018 x86 

Пошаговая последовательность действий, при которой воспроизводится проблема:
- в папке много папок и файлов, я беру часть выделяю для загрузки жму F5 начинается загрузка.
- поторяю выделени части папок и файлов и отправляю на загрузку в облако
- всего примерно по 5...7 паралельных загрузок (так быстрее всего).
- если файлов для загрузки мало то паралелльные загрузки проходят хорошо, если файлов много, например в папка было много файлов, тогда иногда возникают проблема с загрузкой, вываливается сообщение что не могу загрузить в облако такой-то файл.
- если еще в добавок жать паузу на некоторых загрузках тогда ошибки появляются чаще.

Похоже что при паралельных загрузках в облако есть проблемы с корректной работой API и неверно обрабатываются паузы.

Логи плагином не ведутся, поэтому я не могу дать больше информации. Как вариант можно при проблемах в папке с настройками плагина делать log файл с ошибками?

**Comment by pozitronik** [comment]
По моим наблюдениям, TC вообще не очень хорошо работает с несколькими параллельными сетевыми закачками, и на это поведение влияет множество факторов. Отследить и отладить это будет очень трудно. Я попытаюсь воспроизвести ошибку, но не уверен, что выйдет.
Ошибки попадают в протокол, если это не отключено принудительно. Где находится файл протокола - написано в документации.

**Comment by pozitronik** [comment]
Не могу воспроизвести.

**Comment by areht** [comment]
а работа с сетью средствами ТС происходит?

**Comment by pozitronik** [comment]
С сетью, в данном случае, общается плагин, а потоками управляет TC.

**Comment by pozitronik** [comment]
Можно попробовать новый [пре-релиз](https://github.com/pozitronik/CloudMailRu/releases/tag/v21052019), там переделана логика создания подключений к серверу, что может оказать влияние на описанную проблему.

**Comment by pozitronik** [comment]
Решаю тут: #209
