### ISSUE TITLE
Ошибка при загрузке файла: "EIdSocketError ошибка сети: Socket Error # 10060"

### ISSUE THREAD

**Issue by Corak667** [pozitronik/CloudMailRu#208]
EIdSocketError ошибка сети: Socket Error # 10060
Connection timed out. при отправке данных на адрес https://pu.cloud.mail.ru/upload/?cloud_domain=1&x-email=loseman%40list.ru&fileapi15559801270246

**Comment by pozitronik** [comment]
Это сетевая ошибка, таймаут подключения к серверу. Плагин это никак не регулирует.
