### ISSUE TITLE
Total падает при попытке открыть окно настроек.

### ISSUE THREAD

**Issue by FazZzuR** [pozitronik/CloudMailRu#21]
Собственно как было дело - установил плагин, установил ssl библиотеки для x64, добавил аккаунт, отметил опцию использовать библиотеки из папки тотала.  Успешно зашел в папку. Но когда в следующий раз попытался подключиться - could not load library. При нажатии ctrl+enter total стал выдавать стандартное виндовое - Total Commander has stopped working.

**Comment by pozitronik** [comment]
Поведение такое, будто каталог плагина недоступен для чтения (не может подгрузить библиотеки и считать файл конфига).

**Comment by FazZzuR** [comment]
Спасибо. Сижу под учеткой built-in админа windows 10. И все работает окей если тотал запускать от имени адменистратора... Просто ноукоментс с поведения винды =)

**Comment by FazZzuR** [comment]
Как я решил проблему - снял галочку использования библиотек только из папки тотала. Ибо наблюдал такую картину - удаляю плагин, ставлю его заного, добавляю аккаунт и ставлю галочку использования dll из папки тотала. После чего 1 раз подключаюсь к диску и при всех последующих попытках получаю сообщение о невозможности загрузки библиотек.

**Comment by pozitronik** [comment]
Т.е. с использованием библиотек из каталога плагина не работает, а в других случаях срабатывает только один раз?
Я не понимаю пока ни алгоритма воспроизведения проблемы, ни способа устранения.

**Comment by FazZzuR** [comment]
Если поставить опцию - Использовать библиотеки из папки тотала, срабатывает только один раз, при всех следующих попытках получаю ошибку о том что не удалось загрузить ssl библиотеки. Если же опцию не ставить - все работает отлично. Win10

**Comment by pozitronik** [comment]
> Если поставить опцию - Использовать библиотеки из папки тотала
Только такой опции нет. Есть использование библиотек из каталога плагина.

**Comment by FazZzuR** [comment]
Посыпаю голову пеплом. Прошу прощения что потратил время из-за своей невнимательности.

**Comment by pozitronik** [comment]
Ничего страшного.
