### ISSUE TITLE
Не загружает новые файлы найденные по хешу (dev ветка)

### ISSUE THREAD

**Issue by Corak667** [pozitronik/CloudMailRu#210]
Сейчас столкнулся с проблемой в dev ветке, что хеш сканирует, а файл не загружает, в результате в базу данных мейла добавляется хеш, но сам алиас файла данных не добавляет. А если предварительно отключить добавление по хешу и загрузить файл - то при удалении этого файла и попытке добавить уже с опцией добавления по хешу - добавляет нормально:
https://youtu.be/a8J-wmoRxik
"
File exua_backup5_music_games\Music\Heavy\Y&T\2010 - Facemelter\03 - How Long.mp3 found by hash.
e:\MusicUpload\Y&T - 2010 - Facemelter\03 - How Long.mp3->\0Music\exua_backup5_music_games\Music\Heavy\Y&T\2010 - Facemelter\03 - How Long.mp3
"

Находит по хешу, но сами файлы никак не загружаются в директорию облака.

**Comment by pozitronik** [comment]
Исправлено.

**Comment by Corak667** [comment]
Да, все работает отлично, спасибо!
