### ISSUE TITLE
Публичные аккаунты: протухание ссылок

### ISSUE THREAD

**Issue by pozitronik** [pozitronik/CloudMailRu#211]
Непонятно, существовала ли проблема всегда, или же это свежие изменения на серверах.

В публичных аккаунтах ссылка на файл, полученная в getSharedFileUrl живёт буквально несколько секунд после первого обращения. Можно перед каждым обращением перечитывать токены, но а) это накладно б) перечитывание токенов уничтожает текущие ссылки (получаем проблемы с параллельными загрузками и списками на загрузку).

Возможные решения:
1) Оставить, как есть. Функционал ну такой себе.
2) Обновлять токены при необходимости. Не решит проблемы б.
3) Пытаться получать публичные данные через SHARD_TYPE_WEBLINK_VIEW вместо SHARD_TYPE_GET. Судя по всему, эти ссылки не протухают. Но поскольку схема разделения шардов не ясна, это может привести к неучтённым проблемам.

**Comment by yar229** [comment]
> 3\. Пытаться получать публичные данные через SHARD_TYPE_WEBLINK_VIEW вместо SHARD_TYPE_GET. Судя по всему, эти ссылки не протухают. Но поскольку схема разделения шардов не ясна, это может привести к неучтённым проблемам.

`/api/v2/dispatcher?`
[ShardInfoRequest](https://github.com/yar229/WebDavMailRuCloud/blob/master/MailRuCloud/MailRuCloudApi/Base/Requests/WebV2/ShardInfoRequest.cs)

мм... Схема разделения шардов?

**Comment by pozitronik** [comment]
>Схема разделения шардов?

Я не вижу в ShardInfoRequest.cs (или, быть может, просто не понимаю, в силу незнания языка), как выбираются шарды. Но, думаю, понял, что имеется в виду.

У меня шарды забираются через диспетчер, по умолчанию для любой загрузки файлов (анонимно или нет) выбирается тот, который get. Я не помню, почему так; возможно я просто сделал это, подсмотрев обращения браузера в авторизованном аккаунте, и оставил для публичных ссылок, потому что это просто работало.

Сейчас я вижу проблему, описанную в тикете. Если смотреть запросы браузера, то видно, что при запросе на скачивание файла диспетчером отдаётся ссылка с get-шарда (вида https://cloclo15.cldmail.ru/), при этом каждый повторный запрос перезапрашивает шард (но не ключ), а сколько такая ссылка будет жить - неясно. В случае, если запрошен просмотр файла, отдаётся ссылка с weblink_view-шарда (вида https://cloclo19.datacloudmail.ru/weblink/view), и эта ссылка живёт минимум несколько часов. Но непонятно, для каких целей можно использовать этот тип шардов, для всех ли файлов он может отдать данные, и вообще.

Однако эти шарды можно использовать для #169, например.

**Comment by pozitronik** [comment]
Реализовал в коде, одновременно разбираясь, что к чему. Основная разница между шардами в заголовках: get-шард просто отдаёт файл на скачивание, weblink_view - дополняет заголовком с типом файла (т.о. открытие ссылки в браузере приведёт к просмотру файла, если это возможно). Вопрос со временем жизни ссылок остаётся открытым, как получить гарантированные результаты - я не знаю.
Оба варианта использованы для решения задачи #169.
Другие типы шардов (thumbnails, video и т.д.) отдают ссылки, работающие, видимо, только для авторизованного владельца и потому применимы ограниченно.
