### ISSUE TITLE
Баг с квадратной скобкой ]

### ISSUE THREAD

**Issue by kotpilot** [pozitronik/CloudMailRu#215]
Total Commander 9.21a 
Windows 10
CloudMailRu v29052019-pre
При добавлении на вкладке Accounts публичных ссылок, если в Аccount name имя в квадратных скобках, наблюдается баг с множеством ссылок. 
Например, 
[Олег Леконцев] Всегда готов! Перевоспитываем внутреннего прокрастинатора (2019)
_https://cloud.mail.ru/public/3U2w/4F8E4rktH 
Баг, кажется, только с закрывающейся скобкой ]
Ну и чтоб два раза не ходить. 
Еще если в имени стоит например  :  то папка не копируется из облака в сетевую шару. 
Но это может быть баг smb шары на freebsd (xigmanas), точнее zfs. В любом случае очень бы помогло автопереименование проблемных символов или какое-нибудь сообщение при копировании что-ли, а то не копируется в тихую и не сразу поймешь, что не скопировалось особенно когда в папке много других папок и файлов. 
![01](https://user-images.githubusercontent.com/39924255/59634454-7dc8ba80-9157-11e9-8723-e9ef7c823a7c.jpg)
![02](https://user-images.githubusercontent.com/39924255/59634462-81f4d800-9157-11e9-909f-63a212f5dcfc.jpg)

**Comment by pozitronik** [comment]
Со скобкой всё просто: данные аккаунтов хранятся в ini-файлах, а скобки - зарезервированный символ для обозначения имени секции. Оптимальнее всего обойти это, запретив использовать скобку в этом поле.
>Ну и чтоб два раза не ходить.

Стоит заводить по одному репорту на проблему. Завёл issue #216

**Comment by pozitronik** [comment]
Исправлено в dev-ветке.
