### ISSUE TITLE
Загрузка\выгрузка файлов в фоновом режиме

### ISSUE THREAD

**Issue by Corrector1374** [pozitronik/CloudMailRu#22]
Хотелось что бы загрузка\выгрузка файлов могла происходить в фоновом режиме.

**Comment by pozitronik** [comment]
https://github.com/pozitronik/CloudMailRu/issues/8

**Comment by Corrector1374** [comment]
Я имел ввиду не параллельную загрузку\выгрузку, а то что при копировании файлов в облако окно с прогрессом висит на переднем плане и не дает пользоваться TC.

**Comment by pozitronik** [comment]
Это оно и есть.
Технически, это включается в коде одной строчкой. Но если при запущенном фоновом процессе обратиться к облаку (а это произойдёт так или иначе, например при перечитывании списка каталогов), с некоторой вероятностью возникают сбои. А иногда - не возникают. Но чаще - вс-таки возникают =) Отловить их у меня не получается.
