### ISSUE TITLE
Проблема открытия папок в beta

### ISSUE THREAD

**Issue by Owyn** [pozitronik/CloudMailRu#223]
- Версию и разрядность Total Commander, на которой воспроизводится проблема. **TC 9.22A x64**
- Версию и разрядность операционной системы, на которой воспроизводится проблема. **Win 10 x64**
- Номер сборки плагина, на которой воспроизводится проблема.  **v29052019-pre** (последняя)

- Пошаговую последовательность действий, при которой воспроизводится проблема, даже если она кажется очевидной. Если однозначно выявить такую последовательность не получается - пиши, как есть, будем разбираться.
1) скачиваю 64-bit version only Total Cmd 9.22a и плагин
2) распаковываю плагин в `totalcmd/AddOn/mailrucloud/`
3) включаю "Load SSL libraries only from plugin directory" в опциях плагина, т.к. иначе ошибка загрузки SSL, перезапуская totalcmd
4) открываю "Сеть \ FS плагины", нажимаю облако -> my_username -> ввожу пароль
5) захожу в своё облако, вижу список файлов и папок, могу их скачивать и закачивать, втч и внутрь папок, НО:  

**6**) при попытке открыть любую папку слышу только звук ошибки "пум-пум" и ничего не происходит, даже если выйти на уровень вверх и попытаться обартно зайти в корень облака (myusername) то обратно уже не пустет с тем же звуком "пум-пум"
- Как проявляется проблема? Опиши словами: **пум-пум**

- **Обязательно** - протокол соединения - ничего не пишется при ошибке туда, только сам заход в облако
```
CONNECT \moi_oblak
Login to moi_oblak@mail.ru
Connected to moi_oblak@mail.ru
Total space: 1024 Gb, used: 69 kb, free: 1023 Gb.
```

v28122018 (стабильная версия) работает нормально

**Comment by pozitronik** [comment]
Это исправлено в мастер-сборке.
