### ISSUE TITLE
Error uploading file! для путей больше 255 символов

### ISSUE THREAD

**Issue by Owyn** [pozitronik/CloudMailRu#224]
Попробовал загрузить папку шифрованных файлов в облако, после завершения и сверки синхронизацией папок от TC обнаружило что 152 файла не были загружено в облако, попробовал загрузить вручную один из них, получил ошибку, поискал по длинне пути большего чем 255 символов - коммандер нашел как раз 152 файла

![error](https://user-images.githubusercontent.com/1309656/64888586-09c58200-d674-11e9-8651-99b98f606c29.jpg)

лог:
```
Total space: 1024 Gb, used: 10 Gb, free: 1013 Gb.
```

Раз лог пустой - видимо ошибка локальная, например размер буфера для пути файла в 256? Т.к. облако заявляет о поддержке путей до 1024х байтов, а лимит в 255 символов должен быть только на имя файла или папки отдельно (а имя файла у меня **238** всего)
```
Максимальная длина имени папки | 255 символов UTF-8
Максимальная длина имени файла | 255 символов UTF-8
Максимальная длина пути к файлу (включает в себя путь к папке + имя файла) | 1024 байта
```

TotalCmd 9.22A x64
Windows 10 x64
v28122018
Поддержка длинных путей в windows включена ( https://mspoweruser.com/ntfs-260-character-windows-10/ )

**Comment by pozitronik** [comment]
Каков исходный путь любого проблемного файла (полностью, начиная от корня диска) и каков ожидаемый конечный виртуальный путь в плагине (начиная от корневого каталога плагина, включая имя аккаунта)?

**Comment by Owyn** [comment]
исходный `V:\UP\H\X2IQANFB2Y6H4PUXM5KPHQDDXEA34EGUS6AHW\UQVWESUPRUTGGU5T95EBGDWF5MHRDPE42PCBJGIBUAAAYYU29294ERNV3I7GZYPSWI7BB9NS7V49PJFYC2RPDXX8I65M3TM4XEN9U43KJXXEJCCEA6VZIMY955SWZCEJIH4X87B3JHKX8DDIGDZKNWJ2GEXYXVEWIR4RR3AHP5Z7MU5HCM2JTKMYC383NYTNP68BFHBP8U7H79QBG5TWTUECVJR64CJ25RP88SGAUBT3I` (283) 
ожидаемый в облаке `\\\CloudMailRu\Owyn\H\UQVWESUPRUTGGU5T95EBGDWF5MHRDPE42PCBJGIBUAAAYYU29294ERNV3I7GZYPSWI7BB9NS7V49PJFYC2RPDXX8I65M3TM4XEN9U43KJXXEJCCEA6VZIMY955SWZCEJIH4X87B3JHKX8DDIGDZKNWJ2GEXYXVEWIR4RR3AHP5Z7MU5HCM2JTKMYC383NYTNP68BFHBP8U7H79QBG5TWTUECVJR64CJ25RP88SGAUBT3I` (259?)

**Comment by pozitronik** [comment]
Исправлено в мастер-сборке.

**Comment by Owyn** [comment]
Проверил - работает, и теперь всё загрузилось и локально идентично облаку 👍
