### ISSUE TITLE
Access violation at address 000000006307C719 in module 'libeay32.dll'

### ISSUE THREAD

**Issue by nestoris** [pozitronik/CloudMailRu#225]
Total Commander 9.0 64-bit 2016-11-23
Windows 7 x64 (через wine)
- Номер сборки плагина не знаю (предыдущая была "version=281218", в ней возникала та же проблема), склонировал с гитхаб/позитроник пару часов назад и перезаписал.
Был установлен более старый плагин с папками icons, x32, x64 и файлами MailRuCloud.wfx, MailRuCloud.wfx64 и ридми.мд. Сначала перезаписал только папки и файлы, которые были установлены, потом, когда проблема не решилась, выгрузил всё, что было в zip-архиве в папку с плагином.
- Как проявляется проблема? Не заходит в облако, ругается на адрес 000000006307C719 в библиотеке libeay32.dll.
[cmr.log](https://github.com/pozitronik/CloudMailRu/files/3612014/cmr.log)

**Comment by pozitronik** [comment]
Я не смог воспроизвести эту ошибку, правда и не надеялся: слишком много переменных и неизвестных. Непонятно, какой дистрибутив Linux используется и какая версия wine, неясно, откуда берутся ssl-библиотеки, и как wine обеспечивает к ним доступ.
Можно предположить, что wine старается обеспечить среду, неотличимую от windows, соответственно, должна применяться такая же логика использования ssl-библиотек: если в системных каталогах/каталоге TC есть ssl-библиотеки - плагин будет использовать их (в зависимости от того что уже загружено). Либо, если выставлена опция принудительного использования библиотек в каталоге плагина, - обращаться только к ним. Этот и только этот случай может быть хоть как-то проверен.
Соответственно, стоит действовать аналогично описанному в [этом разделе](https://github.com/pozitronik/CloudMailRu#%D1%8F-%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%B8%D0%BB-%D0%BF%D0%BB%D0%B0%D0%B3%D0%B8%D0%BD-%D0%BD%D0%BE-%D0%B2%D0%BE%D0%B7%D0%BD%D0%B8%D0%BA%D0%B0%D0%B5%D1%82-%D0%BE%D1%88%D0%B8%D0%B1%D0%BA%D0%B0-could-not-load-ssl-library)

Интереса ради, я попытался запустить плагин в wine-окружении. Возможности установить linux нативно или в виртуальной машине у меня не было, но я смог воспользоваться linux-подсистемой в windows 10. На wine 3.0 x64-stable всё заработало абсолютно нормально с библиотеками из дистрибутива.
