### ISSUE TITLE
Не работает загрузка файлов больше 2Гб

### ISSUE THREAD

**Issue by pozitronik** [pozitronik/CloudMailRu#228]
[Сообщение на форуме](http://forum.wincmd.ru/viewpost.php?p=130778)
Нужно проверить и исправить, если подтвердится.

**Comment by pozitronik** [comment]
В коде никаких аномалий, похоже на отбой сервером. Нужно покупать подписку и проверять.

**Comment by shamarin** [comment]
С подпиской работает, у меня с февраля подписка и файлы больше 2 ГБ без проблем заливаются.

**Comment by pozitronik** [comment]
Спасибо за информацию!

**Comment by Owyn** [comment]
Подтверждаю не грузит больше 2гб файлы.
```
c:\UP\Folder\file1.mp4->\MyName\Folder\file1.mp4
c:\UP\Folder\file2.avi->\MyName\Folder\file2.avi
c:\UP\Folder\file3.mkv->\MyName\Folder\file3.mkv (22mb file)
File size > 2147483392 bytes, file will be splitted.
EIdSocketError ошибка сети: Socket Error # 10054
Connection reset by peer. при отправке данных на адрес https://pu.cloud.mail.ru/upload/?cloud_domain=1&x-email=MyName%40mail.ru&fileapi15716901310246
Partial upload error, code: 4 Retry attempt 1
EIdSocketError ошибка сети: Socket Error # 10054
Connection reset by peer. при отправке данных на адрес https://pu.cloud.mail.ru/upload/?cloud_domain=1&x-email=MyName%40mail.ru&fileapi15716901620246
Partial upload error, code: 4 Retry attempt 2
EIdSocketError ошибка сети: Socket Error # 10054
Connection reset by peer. при отправке данных на адрес https://pu.cloud.mail.ru/upload/?cloud_domain=1&x-email=MyName%40mail.ru&fileapi15716901930246
Partial upload error, code: 4 Retry attempt 3
EIdSocketError ошибка сети: Socket Error # 10054
Connection reset by peer. при отправке данных на адрес https://pu.cloud.mail.ru/upload/?cloud_domain=1&x-email=MyName%40mail.ru&fileapi15716902240246
Partial upload error, code: 4 Retry attempt 4
EIdSocketError ошибка сети: Socket Error # 10054
Connection reset by peer. при отправке данных на адрес https://pu.cloud.mail.ru/upload/?cloud_domain=1&x-email=MyName%40mail.ru&fileapi15716902550246
Partial upload error, code: 4 Retry attempt 5
EIdSocketError ошибка сети: Socket Error # 10054
Connection reset by peer. при отправке данных на адрес https://pu.cloud.mail.ru/upload/?cloud_domain=1&x-email=MyName%40mail.ru&fileapi15716902860246
Partial upload error, code: 4 Retry attempt 6
EIdSocketError ошибка сети: Socket Error # 10054
Connection reset by peer. при отправке данных на адрес https://pu.cloud.mail.ru/upload/?cloud_domain=1&x-email=MyName%40mail.ru&fileapi15716903160246
Partial upload error, code: 4 Retry attempt 7
EIdSocketError ошибка сети: Socket Error # 10054
Connection reset by peer. при отправке данных на адрес https://pu.cloud.mail.ru/upload/?cloud_domain=1&x-email=MyName%40mail.ru&fileapi15716903460246
Partial upload error, code: 4 Retry attempt 8
EIdSocketError ошибка сети: Socket Error # 10054
Connection reset by peer. при отправке данных на адрес https://pu.cloud.mail.ru/upload/?cloud_domain=1&x-email=MyName%40mail.ru&fileapi15716903770246
Partial upload error, code: 4 Retry attempt 9
EIdSocketError ошибка сети: Socket Error # 10054
Connection reset by peer. при отправке данных на адрес https://pu.cloud.mail.ru/upload/?cloud_domain=1&x-email=MyName%40mail.ru&fileapi15716904080246
Partial upload error, code: 4 Retry attempt 10
EIdSocketError ошибка сети: Socket Error # 10054
Connection reset by peer. при отправке данных на адрес https://pu.cloud.mail.ru/upload/?cloud_domain=1&x-email=MyName%40mail.ru&fileapi15716904400246
Partial upload error, code: 4 Retry attempt 11
EIdSocketError ошибка сети: Socket Error # 10054
Connection reset by peer. при отправке данных на адрес https://pu.cloud.mail.ru/upload/?cloud_domain=1&x-email=MyName%40mail.ru&fileapi15716904700246
Partial upload error, code: 4 Retry attempt 12
EIdSocketError ошибка сети: Socket Error # 10054
Connection reset by peer. при отправке данных на адрес https://pu.cloud.mail.ru/upload/?cloud_domain=1&x-email=MyName%40mail.ru&fileapi15716905020246
Partial upload error, code: 4 Retry attempt 13
EIdSocketError ошибка сети: Socket Error # 10054
Connection reset by peer. при отправке данных на адрес https://pu.cloud.mail.ru/upload/?cloud_domain=1&x-email=MyName%40mail.ru&fileapi15716905330246
Partial upload error, code: 4 Retry attempt 14
Partial upload aborted.
c:\UP\Folder\big_file1.mkv->\MyName\Folder\big_file1.mkv (2gb+ file)
File size > 2147483392 bytes, file will be splitted.
Partial upload aborted.
Total space: 1024 Gb, used: 282 Gb, free: 741 Gb.
```

**Comment by pozitronik** [comment]
Owyn,
судя по этому логу, происходит попытка загрузить файл больше двух гигабайт с его разделением на части (размер частей в логе не указывается). Если аккаунт платный (в данном тикете речь идёт именно об этой ситуации), то такой ошибки быть не должно, но тогда непонятно, зачем включать режим разделения. Если аккаунт бесплатный, можно попробовать выставить в настройках меньший размер разделяемой части, чтобы убедиться, что проблема в этом.

**Comment by shamarin** [comment]
> 
> 
> Owyn,
> судя по этому логу, происходит попытка загрузить файл больше двух гигабайт с его разделением на части (размер частей в логе не указывается). Если аккаунт платный (в данном тикете речь идёт именно об этой ситуации), то такой ошибки быть не должно, но тогда непонятно, зачем включать режим разделения. Если аккаунт бесплатный, можно попробовать выставить в настройках меньший размер разделяемой части, чтобы убедиться, что проблема в этом.

На платном я не испытываю проблем, файлы свыше 2 ГБ закачиваются без проблем и без разделения на части.

**Comment by Owyn** [comment]
Аккаунт бесплатный, поставил 1147483392 вместо 2147483392 - успешно закачало, хотя окошко копирование файла и пробегало много больше раз чем 3 (не считая calculating hash) (хотя файла создало 3)

Так что вероятно дефолтное значение размера для разделения некорректное

**Comment by pozitronik** [comment]
Это поведение описано в readme: судя по косвенным данным, этот лимит может колебаться (разные проверяющие обнаруживали разные лимиты). Собственно, эта настройка и сделана для самостоятельного выставления подходящей величины. Как определяли дефолтный размер - сходу не вспомню.

**Comment by Owyn** [comment]
Мб с запасом величину поставить для всех? Или она там в мегабайтах отличается для людей? хмм

**Comment by pozitronik** [comment]
Приобрёл подписку для тестов. Проблема не подтверждена.

**Comment by FiLinX** [comment]
Странно, а я думал это уже давно ясно.  Хотя, возможно я заблуждаюсь..
Вобщем вот моя легенда - http://forum.wincmd.ru/viewtopic.php?p=129036#129036
И вот из неё я и сделал вывод  -  на бесплатном аккаунте, выставлять в "Override split file size to" размер больший, чем 1500000000, противопоказано для 32 битных систем! 
Так как в таких системах всей памяти обнаруживается лишь 3072 МБ, а задействовано под процесс определённой программой, вообще не может быть более 2ГБ, без танцев с IncreaseUserVa, то вот своими эмпирическими тестами я считаю это и вычислил..
Или это всё не так? )

**Comment by pozitronik** [comment]
Это не так **в большинстве случаев**.
Ни разбиение, ни загрузка не используют отображение данных в память, кроме случаев включённого шифрования. Вот оно производится целиком в памяти.

Понять, вызвана ли проблема недостатком памяти довольно просто — плагин сообщит с EOutOfMemory.

**Comment by Immick** [comment]
На текущий момент с активной подпиской при попытке загрузить файл размером 2.19 ГБ в логах выдается:

`File size > 2147483392 bytes, ignored.`

**Comment by pozitronik** [comment]
Галочка Ignore 2Gb limit (paid account) включена?
