### ISSUE TITLE
Синхронизация файлов > 2GB

### ISSUE THREAD

**Issue by Owyn** [pozitronik/CloudMailRu#229]
![compare](https://user-images.githubusercontent.com/1309656/68343716-769e4b00-00fe-11ea-86a9-60004c3a752b.jpg)

Можно-ли как-то перехватить и модифицировать плагином стандартный синхронизатор чтоб разъединенные файлы 2ГБ+ не считал рзными и не пытался их по новой загружать каждый раз, а части удалять?

П.С. - почему для некоторых разъединенных файлов создаётся .crc файл, а для других нет?

**Comment by pozitronik** [comment]
Нет, нельзя. Разъединение существует только для плагина, это, в своём роде, хак, потребность в котором никак не могла быть предусмотрена разработчиком TC.

>почему для некоторых разъединенных файлов создаётся .crc файл, а для других нет?

CRC-файл должен создаваться всегда, если все части разбитого файла залиты без ошибок. Возможно, я пропустил какую-то ситуацию, например, когда происходит перезапись существующих "кусков" с подтверждением операции. В этом случае мне нужно знать, как воспроизвести ошибку. Если такие примеры будут - заводите одельный тикет, буду разбираться.
