### ISSUE TITLE
Не сохраняются дата/время файла, заливаемого в облако

### ISSUE THREAD

**Issue by pozitronik** [pozitronik/CloudMailRu#23]
Проверить, поддерживается ли это в API, если да - то реализовать.

**Comment by pozitronik** [comment]
Сохранение времени файла при закачке в облако не поддерживается (файлу присваивается текущее время). Это время можно сохранять при загрузке (commit 3cf32e39629823f1540a554b451e48fa32a28396),  функция сделана опциональной (57a5c62216abd18c1c1fdd3a242715914ec0d7f7) (отключение немного экономит трафик).

**Comment by Tallefer** [comment]
Просьба уточнить, "Сохранение времени файла при закачке в облако не поддерживается" чем именно, АПИ? Так как сам клиент это умеет делать. Для полной замены клиента реально не хватает именно этой фичи.

**Comment by pozitronik** [comment]
Десктопные клиенты работают по своему протоколу, с большим набором возможностей. Плагин работает, "притворяясь" браузером, через web-api, в котором этой фичи нет.
