### ISSUE TITLE
Зависает закачка пустого файла

### ISSUE THREAD

**Issue by pozitronik** [pozitronik/CloudMailRu#231]
Subj

**Comment by pozitronik** [comment]
На однобайтовый файл сервер стал отвечать "File too short", интересно.

**Comment by pozitronik** [comment]
Попытка посмотреть, что происходит при работе в браузере:
- До какого-то лимита размера метод upload не вызывается, сразу происходит add по хешу. Из этого можно сделать вывод, что для небольших файлов хеш считается на клиенте.
- Найти в клиентском коде логику такого разделения не удалось: скрипты здорово переделаны с тех пор, как я последний раз в них вникал, и как работает новый код я уже не в силах понять (или, по крайней мере, не готов тратить на это время). Более того: в скриптах встречаются намётки третьей версии API (текущая, судя по всему, вторая), но в каком она статусе - неясно.
- При уточнении поведения выяснилось интересное: файлы размером до 20 байтов включительно, состоящие из символа 0x0, в веб-интерфейсе не закачиваются. Если в таком файле будет любой другой символ - закачка проходит.
Оследить в отладчике конкретику я не могу, но можно догадаться, что функция подсчёта хеша на клиентской стороне глючит для таких файлов.
- Исходя из этого решение такое: для файлов размером <20 байт включать режим добавления по хешу принудительно. Лимит размера сделать настраиваемым.

**Comment by yar229** [comment]
Извиняюсь, если не в тему, но разве что-то со времен вот [этого обсуждения](https://github.com/pozitronik/CloudMailRu/issues/135#issuecomment-343752299) изменилось?

**Comment by pozitronik** [comment]
Видимо изменилось  —  по крайней мере раньше такого поведения за сервером я не замечал. Речь о том, что теперь файлы, чей размер меньше или равен длине хеша, не могут быть закачаны в облако в принципе (на операци upload API отвечает "File too short"). И постить их больше не нужно, достаточно сразу добавлять.
Эта экономия на спичках немного поломала работу плагина.
