### ISSUE TITLE
403 Forbidden при загрузке

### ISSUE THREAD

**Issue by Ankarii** [pozitronik/CloudMailRu#232]
TotalCommander 9.22a x64 и Windows 10 Pro x64 (1909)
и
TotalCommander 9.22a x64 и Windows 7 Pro x64

Ошибка: HTTP/1.1 403 Forbidden при попытке что-то закачать на облако. Пробовал на двух разных машинах на разные учетные записи. Заново переустанавливал TC и плагин - не помогло.
Обнаружил проблему на v31102019. Со страницы проекта скачал новые Binary build	(4 days ago) - проблема не ушла.
[wcftplog.txt](https://github.com/pozitronik/CloudMailRu/files/4077410/wcftplog.txt)

**Comment by pozitronik** [comment]
Подтверждаю, у меня тоже началось.

**Comment by pozitronik** [comment]
Материал для размышления:
- в браузере всё ок.
- от юзерагента проблема не зависит.
- нашёл расхождения с получением шарда закачек (вместо upload плагин получал public_upload), поправил, но проблему это не решает.

Гипотеза 1: что-то где-то поменялось в API, что я пока не заметил.
Гипотеза 2: mailru начал бороться с альтернативными клиентами.

Буду разбираться.

**Comment by OmlineEditor** [comment]
> Гипотеза 2: mailru начал бороться с альтернативными клиентами.

Если это так тогда нужно замаскировать плагин под их программу. Думаю там только пару проверок для этого используют.

**Comment by OmlineEditor** [comment]
В логах написано:
_Forbidden при отправке данных на адрес https://pu.cloud.mail.ru/upload_
Разве до этого на домен pu.cloud.mail.ru данные грузили? там кажется другие домены были типа: cloclo5-3.i.mail.ru или cloclo18.i.mail.ru. Возможно сайты поменяли.

**Comment by debobrov** [comment]
Поставил последнюю версию, файлы не загружаются, пишет ошибку. 
EIdHTTPProtocolException ошибка с сообщением: HTTP/1.1 403 Forbidden при отправке данных на адрес https://pu.cloud.mail.ru/upload/...

**Comment by SloNicK-GH** [comment]
Такая же беда. Интересно, что удалять разрешает, а копировать нет...

**Comment by OmlineEditor** [comment]
Официальный ответ от поддержки cloud.mail.ru:
...Мы специально не ограничиваем сторонний софт...
Возможно что-то поменяли в API.

**Comment by pozitronik** [comment]
В API изменился алгоритм загрузки файлов:
- Вместо метода POST теперь используется PUT.
- Ответ сервера поменял формат, вместо хеша и размера теперь отдаётся просто хеш.
- Перед первой загрузкой после логина также выполняется запрос с методом OPTIONS. Далее он не выполняется, насколько я могу судить. Здесь ещё нужно исследовать.

После соответствующих доработок плагин смог загружать файлы, но я пока сталкиваюсь с проблемами при их добавлении.

**Comment by pozitronik** [comment]
Исправленная версия в master. Нужно ещё поправить кое-какие мелочи, но это уже по мере появления рабочего времени.

Изменения в API довольно логичны: вместо постинга формы с полем, содержащим данные файла, теперь используется метод PUT, принимающий данные файла как есть. При этом сервер кодом ответа может сообщить, был ли уже этот файл в облаке глобально.

**Comment by pozitronik** [comment]
Запрос options не обязателен, работает и без него.
