### ISSUE TITLE
Сервер больше не авторизует с текущим UserAgent

### ISSUE THREAD

**Issue by pozitronik** [pozitronik/CloudMailRu#235]
Плагин перестал авторизоввываться ни на публичных, ни на пользовательских аккаунтах.

**Comment by Corak667** [comment]
"CONNECT \0backup1
Login to ruwimlvovich@mail.ru
Requesting auth token for ruwimlvovich@mail.ru
Parsing token data...
Current upload shard is undefined, trying to get one
error: parsing auth token for ruwimlvovich@mail.ru
"

**Comment by Impg** [comment]
Здравствуйте
И у меня проблема с авторизацией: что-то не так с токеном
http://joxi.ru/Vm6zdDjHj5yVam

**Comment by midi-creator** [comment]
СПАСИТЕ, ПОМОГИТЕ!!!!
CONNECT \
Login to 
Current upload shard is undefined, trying to get one
error: parsing auth token for

**Comment by NewSky13** [comment]
Да. И публичные ссылки не работают и в аккаунты не пускает
`Login to ***@mail.ru
Current upload shard is undefined, trying to get one
error: parsing auth token for ***@mail.ru`
`CONNECT \***
Open https://cloud.mail.ru/public/uRS1/***/
Can't get public share download token`

**Comment by 1ehacom** [comment]
Тоже не могу войти, очень привык к плагину...надеюсь

**Comment by pozitronik** [comment]
Текущий способ авторизации больше не работает. Текущий способ выглядит так: сначала постится логин, в ответ приходит инфа об аккаунте, и только после этого можно постить пароль.

**Comment by KGB-USSR** [comment]
Павел! А решение то будет?

**Comment by SolTomsk** [comment]
Да, очень ждем!

**Comment by pozitronik** [comment]
Над исправлением работаю по мере появления свободного времени, на карантине его вовсе не прибавилось. С изменениями разобрался, решение постараюсь выложить в ближайшие дни, но обещать ничего не могу.

**Comment by NetworkWolf** [comment]
CloudMailRu-20012020 устарел User Agent.
сейчас даже Chrome 61 не пускает в облако.
ваш
HTTP.Request.UserAgent := 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.17 (KHTML, like Gecko) Chrome/24.0.1312.57 Safari/537.17/TCWFX

обновите пожалуйста
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.162 Safari/537.36

**Comment by pozitronik** [comment]
Блин, мне и смешно, и грустно.
Грустно, потому что я некоторое время убил, разбираясь с проблемой, но копал, как оказалось, совсем не туда.
Смешно, потому что смена юзерагента действительно помогла. Спасибо огромное, что обратили внимание.

**Comment by pozitronik** [comment]
Исправление в master и в [релизах](https://github.com/pozitronik/CloudMailRu/releases/tag/v05042020).
Дополнительно сделал возможность переопределять useragent в конфиге, нужно будет документироватью

**Comment by NetworkWolf** [comment]
а я могу в ini файлах как-то прописать новый User Agent ?
хотя бы временно..

**Comment by Owyn** [comment]
> Дополнительно сделал возможность переопределять useragent в конфиге

Очень кстати хорошо, давно хотелось поставить свою useragent как в браузере основном

П.С. - лучше бы прямо в настройках его можно было ставить, а не ток в конфиге

**Comment by pozitronik** [comment]
> а я могу в ini файлах как-то прописать новый User Agent ?

В новом релизе - можно. В MailRuCloud.global.ini (может находиться в разных каталогах, в зависимости от настроек, по умолчанию - рядом с плагином) в секцию [Main] вписать
UserAgent=<нужный UA>

**Comment by pozitronik** [comment]
>Очень кстати хорошо, давно хотелось поставить свою useragent как в браузере основном

У меня была давняя договорённость с mail.ru, что я не меняю UA, чтобы они могли отслеживать статистику использования плагина. Но, думаю, в текущих обстоятельствах эта договорённость теряет силу.

>П.С. - лучше бы прямо в настройках его можно было ставить, а не ток в конфиге

Я сделал быстрое решение, выносить редактор на форму нужно чуть дольше.

**Comment by Owyn** [comment]
`UserAgent=Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0` 
без кавечек же?

> У меня была давняя договорённость с mail.ru, что я не меняю UA, чтобы они могли отслеживать статистику использования плагина. Но, думаю, в текущих обстоятельствах эта договорённость теряет силу.

Так что таки произошло? Они выключили поддержку старого Хрома 24й версии и забыли про работоспособность плагина? Или решили запрещать и не пущать т.к. 0.1% пользователей создают 30% всей нагрузки?

**Comment by NetworkWolf** [comment]
> Так что таки произошло

новая почта. - новое облако 

всё играют с картинками.  дубы.....

**Comment by pozitronik** [comment]
>без кавечек же?

Настройка без кавычек. Но в текущую версию вписана актуальная, т.е. и так должно работать.

>Так что таки произошло?

Понятия не имею. К сожалению, у меня не осталось контактов тех людей, с которыми я это обговаривал, да и было это на словах. Вряд ли вообще они это помнят, даже если всё ещё работают там. И вряд ли заботятся о каком-то стороннем софте - для Облака плагин выглядит обычным браузером, нет никакого смысла с ним бороться.
Скорее всего действительно убрали поддержку старых браузеров, а плагин зацепило.

**Comment by KGB-USSR** [comment]
Еще бы эту проблему решить https://github.com/pozitronik/CloudMailRu/issues/230 Неужели никто не пользуется двухфакторной авторизацией?

**Comment by NetworkWolf** [comment]
первой строкой сработало. 
[Main]
UserAgent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/602.1.50 (KHTML, like Gecko) Version/30.0 Safari/602.1.50

-----
Время	 6 апреля, 00:32
 Устройство	 Mac OS, Safari - неизвестная версия, Москва, Россия

**всё супер!**

**Comment by OmlineEditor** [comment]
Тикет пока открыт но есть новая версия которая кажется работает.
Решение уже полностью найдено или еще что-то нужно по мелочи доработать в коде?

**Comment by KGB-USSR** [comment]
Еще бы эту проблему решить https://github.com/pozitronik/CloudMailRu/issues/230 коллективным разумом. Неужели никто не пользуется двухфакторной авторизацией?

**Comment by pozitronik** [comment]
В диалог настроек добавлено редактирование Useragent.
В документацию добавлено описание параметра.
