### ISSUE TITLE
APPCRASH в процессе

### ISSUE THREAD

**Issue by Owyn** [pozitronik/CloudMailRu#238]
Тыкаю compare, жду результата, тыкаю synchronize, в окошке снимаю галку с "confirm overwrites" и жму OK и когда уже должен пойти процесс загрузки\удаления файлов - краш (несколько раз повторил - снова краш при попытке)

Синхронизировал несколько папок по-отдельности - всё ок прошло, есть подозрение крашит из-за того что я всё сразу хочу одной операцией (раньше работало, но и крашилось раньше тоже бывало пока я отворачивался - но сейчас не хочет вообще всё синхронизировать)

```
Имя сбойного приложения: TotalCommander64.exe, версия: 9.2.2.1, метка времени: 0x00000000
Имя сбойного модуля: KERNELBASE.dll, версия: 10.0.18362.719, метка времени: 0xb31987d3
Код исключения: 0x0eedfade
Смещение ошибки: 0x000000000003a859
Идентификатор сбойного процесса: 0x444
Время запуска сбойного приложения: 0x01d60b9237f03feb
Путь сбойного приложения: S:\Program Files\totalcmd\TotalCommander64.exe
Путь сбойного модуля: S:\WINDOWS\System32\KERNELBASE.dll
Идентификатор отчета: a6397abf-421e-49cd-a232-905b606bff36
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом: 
```

```
Контейнер ошибки 1680897355039554256, тип 4
Имя события: APPCRASH
Отклик: Нет данных
Идентификатор CAB: 0

Сигнатура проблемы:
P1: TotalCommander64.exe
P2: 9.2.2.1
P3: 00000000
P4: KERNELBASE.dll
P5: 10.0.18362.719
P6: b31987d3
P7: 0eedfade
P8: 000000000003a859
P9: 
P10: 

Вложенные файлы:
\\?\S:\ProgramData\Microsoft\Windows\WER\Temp\WER60D6.tmp.dmp
\\?\S:\ProgramData\Microsoft\Windows\WER\Temp\WER6173.tmp.WERInternalMetadata.xml
\\?\S:\ProgramData\Microsoft\Windows\WER\Temp\WER6193.tmp.xml
\\?\S:\ProgramData\Microsoft\Windows\WER\Temp\WER6191.tmp.csv
\\?\S:\ProgramData\Microsoft\Windows\WER\Temp\WER61A2.tmp.txt

Эти файлы можно найти здесь:
\\?\S:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_TotalCommander64_a486e30bd66cce660f4d793dd0cf1bfd83c31c_a238aac6_68e25b57-1b5e-45e4-9e89-77fe15af0da8

Символ анализа: 
Повторный поиск решения: 0
Идентификатор отчета: a6397abf-421e-49cd-a232-905b606bff36
Состояние отчета: 268435456
Хэшированный контейнер: 4ac32c6574c6ef8c6753bf3d1706bad0
Идентификатор GUID CAB: 0
```

TC 9.22a официальная
Win10 64bit

- протокол соединения - пустая папка _tc

**Comment by pozitronik** [comment]
Я не смог воспроизвести. По факту я никогда не пользовался инструментом синхронизации TC, и могу не понимать что-то с лёту, но пробная синхронизация отработала вполне успешно.
Опишите подробно, по шагам, что и как делаете, попробую разобраться.

**Comment by Owyn** [comment]
Возможно виной https://github.com/ValdikSS/GoodbyeDPI/releases 
запускаю его `goodbyedpi.exe -e 40` (фрагментация https пакетов)

после того как выключил - все синхронизировалось успешно

**Comment by pozitronik** [comment]
У меня отработало, в том числе, и с goodbyedpi (я просто запустил с этими параметрами).

**Comment by Owyn** [comment]
Разве что в кол-ве файлов может быть различие т.к. у меня их много (100к+ файлов, 2.5к папок), отдельные папки (5к файлов и меньше) и с ним проходили

Хотя в любом случае это не критично, просто забываю иного выключить (а сейчас после перерыва работы плагина и вообще забыл что его надо было выключать...)
