### ISSUE TITLE
Сохранение структуры и файлов из облака в удобочитаемый файл

### ISSUE THREAD

**Issue by OmlineEditor** [pozitronik/CloudMailRu#239]
Если у вас есть несколько облаков и вы точно не помните где лежит **нужный** вам файл вам придется подключиться к каждому из них и найти его. Это немного неудобно, особенно если у вас много облаков по 8 Гб и файлы сильно разбросаны.

Сейчас данные из облака сохраняются в файл в таком виде (разделитель двоеточие):
hash "BF221CA4AA726D42D7267167CC90D42C470BDE3:12345:folder\File.txt"
т.е.
hash "ХЭШ:размер:ИмяФайлаСПолнымПутем"

Можно ли переделать структуру в такой вид (разделитель табуляция, пробелы это будут имена в файле):
folder\File.txt    12345   BF221CA4AA726D42D7267167CC90D42C470BDE3
т.е.
ИмяФайлаСПолнымПутем   =TAB=>  размер  =TAB=> ХЭШ

Этот формат позволит использовать плагин Diskdir 1.3 https://www.ghisler.com/plugins.htm
Это упростит хранение и поиск файлов.

Для совместимости можете сделать поддержку двух вариантов хранения файлов, старый и новый.

**Comment by pozitronik** [comment]
#37
