### ISSUE TITLE
Error: parsing auth token

### ISSUE THREAD

**Issue by lepidonotus** [pozitronik/CloudMailRu#240]
Total Commander 9.51 64bit (переустанавливал несколько раз с нуля)
Win 10 64bit 1803 OS build 17134.1365
Плагин 64бит v05042020
Действия:
    1. Акк существует и работае через браузер. 2 факторная автоизация. 1Терабайт бесплатная версия
2. В плагине ввожу данные аккаунта. Пароль не шифрую. Разбиваю большие файлы по 2 гига. И отмечаю 2 факторную авторизацию. Остальное по умолчанию
3. Пытаюсь открыть обычный путь для облака [mail_name@mail.ru]
4. Ввожу код 2 факторной авторизации
5. Current upload shard is undefined, trying to get one
error: twostep auth failed
и выкидывает в папку со списком облаков \\\CloudMailRu\

Есть другой акк без 2 факторной авторизации. Работоспособность тоже проверена через браузер
Делаю всё тоже самое, за исключение галочки на двухфакторной в настройках и ввода кода соответственно
Результат:
Current upload shard is undefined, trying to get one
error: parsing auth token for mail_name2@mail.ru
[wcftplog.txt](https://github.com/pozitronik/CloudMailRu/files/4466538/wcftplog.txt)

**Comment by pozitronik** [comment]
Подтверждаю неработоспособность двухфакторной аутентификации. С парольных входом проблем не вижу.

**Comment by lepidonotus** [comment]
Добрый день!

Спасибо за ответ. 2 факторную я и отключить могу. А что делать с парольным
входом не знаю. Пробовал несколько раз. И на других аккаунтах тоже.


вс, 12 апр. 2020 г., 20:21 Pavel Dubrovsky <notifications@github.com>:

**Comment by pozitronik** [comment]
UPD: нет, не подтверждаю - при проверке забыл для аккаунта переключить настройку.

Не могу воспроизвести. Единственное, что необычное вижу в логе - сообщение
`CryptProc returns error: Encrypt failed`

Оно выдаётся при ошибке взаимодействия с криптофункцией в Total Commander. Но понять, как это связано пока не могу.

Работал ли плагин раньше? Если да - то после каких действий перестал? На чистой **отдельной** копии Total Commander проблема воспроизводится?

**Comment by lepidonotus** [comment]
Плагин работал. Причём с несколькими акками одновременно. Потом майл ру
что-то обновили у себя и плагин работать перестал. Не помню, что он писал в
протоколе.
Сейчас же новый, поставленный с нуля тотал. С оффсайта. Все предыдущие
настройки я удалил (ini файл) . Поставил всё новое. Плагин тоже последний.


вс, 12 апр. 2020 г., 20:32 Pavel Dubrovsky <notifications@github.com>:

**Comment by pozitronik** [comment]
В описанном виде ситуация похожа на issue #235
Возможно вы каким-то образом подключаете старую версию плагина?
Проверить можно, использовав сборку прямо из мастер-ветки ([x32](https://github.com/pozitronik/CloudMailRu/blob/master/MailRuCloud.wfx)/[x64](https://github.com/pozitronik/CloudMailRu/blob/master/MailRuCloud.wfx64): замените эти файлы в каталоге плагина скачанными, запустите TC, и откройте настройки плагина. Если на вкладке Network Settings есть галка "Change plugin UserAgent" - то загрузилась и используется актуальная версия. Если и с ней проблема воспроизводится - будем копать дальше.

**Comment by lepidonotus** [comment]
Плагин из мастер ветки работает без 2 факторной. Похоже и правда старая
версия подцеплялась.

Спасибо за быстрое решение проблемы.

вс, 12 апр. 2020 г., 20:44 Pavel Dubrovsky <notifications@github.com>:
