### ISSUE TITLE
Кнопка установки пароля

### ISSUE THREAD

**Issue by SchwarzKopf-M** [pozitronik/CloudMailRu#241]
Заметил интересное поведение кнопки установки пароля при шифровании данных... При нажатии этой кнопки появляется окошко для ввода пароля, но окно появляется не модальным и на кнопку можно ещё много раз нажать и много раз появляется новое окно. Если это окно закрыть, то уже само окно свойств плагина теряет модальность и можно при открытом окне мышкой что-то делать в самом окне Тотала.
Это нормально?

**Comment by pozitronik** [comment]
Так происходит из-за того, что диалог запроса всегда создаётся самим TC, без возможности изменить модальность. При закрытии диалога фокус также всегда возвращается в окно TC, игнорируя имеющиеся модальные окна. С одной стороны, такое поведение похоже на ошибку самого TC, с другой - это имеет свою логику.
Интересно, что окно запроса глобального пароля модально по отношению к вызывающему окну, а не к окну TC, например.

Я попробую обойти это через создание собственных диалогов, так будет быстрее, чем ждать исправлений от Гислера.

**Comment by pozitronik** [comment]
Исправлено. Я написал собственный обработчик вызова диалога запроса пароля, которому можно указать родительский компонент. Этот обработчик вызывается только при запросе пароля шифрования из диалога настроек, во всех остальных случаях по прежнему вызывается обработчик TC.
К сожалению, диалог запроса пароля может некорректно позиционироваться на мультимониторных конфигурациях, в случае, когда диалог настроек плагина находится не на основном мониторе. Я думаю, что это какая-то ошибка VCL.

**Comment by SchwarzKopf-M** [comment]
Что-то я не вижу в исходниках файла RequestDialog.dfm...

**Comment by pozitronik** [comment]
My bad, пропустил при добавлении в индекс. Поправлено.

**Comment by pozitronik** [comment]
Лол, вспомнил, что у меня уже есть диалог AskPassword. Хотя назначение у них примерно идентичное, внутренняя логика всё же разная. Надо вспоминать, что там, и унифицировать.
