### ISSUE TITLE
Шифрование с добавлением соли

### ISSUE THREAD

**Issue by OmlineEditor** [pozitronik/CloudMailRu#243]
Сейчас у вас используется AES шифрование без соли. Это дововольно сильное упущение и влияет на безопасность. Можно ли добавить в алгоритм шифрования соль? Чтобы содержимое файлов и имена файлов шифровались с использованием соли.

https://ru.wikipedia.org/wiki/Соль_(криптография)

**Comment by pozitronik** [comment]
Соль применяется при сверке хешей; если бы вся логика шифровки/расшифровки работала на серверной стороне - это имело бы смысл. В случае, когда всё происходит на стороне клиента, это бессмысленно.

**Comment by OmlineEditor** [comment]
> Соль применяется при сверке хешей; если бы вся логика шифровки/расшифровки работала на серверной стороне - это имело бы смысл. В случае, когда всё происходит на стороне клиента, это бессмысленно.

Вы не правы, соль применяется чтобы было сложней понять что лежит в зашифрованных данных. Если имена файлов одинаковвые и отличаютя только в конце цифрами (допустим для фото) это позволит понять что лежит в зашифрованных данных. Если сравнивать одинаковые участки зашифрованных данных внутри файла можно будет понять что лежит, возможно и не оплучится расшифровать но понять что лежит можно. Соль поможет исключить одинаковые блоки на выходе при одинаковых входных блоках. При использовании одного ключа идентичные блоки открытого текста шифруются в идентичные блоки зашифрованного текста; таким образом, этот метод плохо скрывает структуру данных, что также делает его неустойчивым к статистическому анализу. Если вы это понимаете, прошу добавить использование соли.

**Comment by pozitronik** [comment]
Окей. Где соль будете хранить? На клиенте? Не уверен, что это будет лучше сложного пароля для

> понять что лежит в зашифрованных данных.

Я понимаю, чего вы хотите (как вариант, можно сделать опциональное соление хешом пароля), но не думаю, что оно того стоит.

**Comment by OmlineEditor** [comment]
> Где соль будете хранить?
Соль можно в открытую хранить, это допустимо и возможно. И соль для каждого файла должна быть разной. Нельзя соль использовать одну и туже. 
Соль можно хранить в самом файле что зашифрован, первые 128 бит это будет соль - это чтобы шифровать сам файл. В имени файла будем хранить соль, первые 16 символов соль - это чтобы зашифровать имя файла. Если сначала обработать солью данные, а потом шифровать уйдет проблема статистического анализа и повысится криптостойкость.

> можно сделать опциональное соление хешом пароля
нельзя, соль нужно всегда для каждого файла использовать разную.

> не думаю, что оно того стоит
Параноики оценят любую помощь с вашей стороны чтобы не прогресировала их мания преследования. Любое усиление шифрования и устранение потенциальных уязвимостей хорошо будут встречены пользователями.

Как вариант можно в меню указать что нужно ли использовать соль или нет. Варианты с солью и без соли разумеется не совместимы друг с другом, но перезалить данные с облака, т.е. слить и потом залить с солью это думаю не проблема.

Если есть возможность прошу подумать над проблемой и ее лучшей реализацией.

**Comment by OmlineEditor** [comment]
Если возможно откройте тикет и сдеайте сообщение на форуме, возможно получится получить дельные советы по усилению защиты.

**Comment by pozitronik** [comment]
> Соль можно хранить в самом файле что зашифрован, первые 128 бит это будет соль - это чтобы шифровать сам файл. В имени файла будем хранить соль, первые 16 символов соль - это чтобы зашифровать имя файла. 

Вы предлагаете отправлять соль, которой зашифрованы данные, вместе с самими данными? Вам не кажется, что это противоречит самой идее?

>Если возможно откройте тикет и сдеайте сообщение на форуме

Я по прежнему не вижу в предложении рационального зерна. Я не специалист в криптографии, но мне не удалось с лёту найти доказательств того, что есть практически реализуемые способы хотя бы опознать структуру данных, зашифрованных AES. Такое доказательство, возможно, смогло бы убедить меня в необходимости что-то делать.

**Comment by OLEG4120** [comment]
Параноики не юзают мыло.ру ))

**Comment by OmlineEditor** [comment]
> Вы предлагаете отправлять соль, которой зашифрованы данные, вместе с самими данными? Вам не кажется, что это противоречит самой идее?

Нет, все нормально соль вообще можно хранить в открытом виде. она не является чем-то супер важным. Она только для усложениея анализа данных и усложнения атаки по радужным таблицам.


> практически реализуемые способы хотя бы опознать структуру данных, зашифрованных AES
Структуру данных AES вы не отличите от любой ругой структуры, там почти всегда рандомные данные с линейным распределением всех возможных байт. Нам не нужно определять структуру, нам важен сам факт что без соли одни и теже данные имеют один и тот же зашифрованный вид, соль нужна чтобы  одни и теже данные выглядели по разному.
