### ISSUE TITLE
error: parsing authorization data

### ISSUE THREAD

**Issue by oleg-zubarik** [pozitronik/CloudMailRu#244]
Вечер добрый, после обеда перестал работать плагин.

Total Commander 8.52a 32bit, 64bit
Windows 10 x64
CloudMailRu-master v05042020

Захожу в FS-плагины -> CloudMailRu -> Имя моего облака. В консоли: "error: parsing authorization data" (лог тут [wcftplog.txt](https://github.com/pozitronik/CloudMailRu/files/4760272/wcftplog.txt)). При этом одноразовый пароль для двухфакторной аутентификации приходит в SMS, но окошко для его вставки не появляется.

Пробовал:
1) Новый чистый Total Commander 8.52a с единственным заново подключенным плагином CloudMailRu-master v05042020
2) Перезагружать компьютер
3) Подключаться в другое облако
4) Подключаться на другом компьютере с чистым Total Commander 8.52a и единственным заново подключенным плагином CloudMailRu-master v05042020

Результат одинаковый: "error: parsing authorization data".
Кажется, разработчики облака что-то поправили в API на своей стороне

**Comment by oleg-zubarik** [comment]
На x64 работает, на x32 после ввода одноразового пароля Total Commander вылетает. Протесчено на 2 стендах.

**Comment by pozitronik** [comment]
Да, подтверждаю. Только в x32, и только в release-сборке. 
Падает при попытке освобождения буфера, выделенного под код авторизации. Почему - непонятно.

**Comment by Keks1984** [comment]
Не работает. Пишет error: parsing authorization data. Иногда даже смс приходит двухфакторной авторизации.

**Comment by pozitronik** [comment]
> Не работает. Пишет error: parsing authorization data. Иногда даже смс приходит двухфакторной авторизации.

Уточню, на всякий случай: именно на x64 в последней master-сборке?

**Comment by Keks1984** [comment]
> > Не работает. Пишет error: parsing authorization data. Иногда даже смс приходит двухфакторной авторизации.
> 
> Уточню, на всякий случай: именно на x64 в последней master-сборке?

![TC](https://user-images.githubusercontent.com/67436484/85817902-b64a9d80-b788-11ea-9e5f-fe4870e23bb2.png)
Да. Total Commander 9.51 final x64 с оффсайта.

**Comment by pozitronik** [comment]
Речь о [мастер-билде](https://github.com/pozitronik/CloudMailRu/blob/master/MailRuCloud.wfx64) плагина.
Я проверил работу двухфакторки, на x64 всё работает, как ожидается, и с СМС-подтверждением, и кодом через приложение. С x32-билдом проблема пока не решена, не доходят руки.

**Comment by Keks1984** [comment]
> Речь о [мастер-билде](https://github.com/pozitronik/CloudMailRu/blob/master/MailRuCloud.wfx64) плагина.
> Я проверил работу двухфакторки, на x64 всё работает, как ожидается, и с СМС-подтверждением, и кодом через приложение. С x32-билдом проблема пока не решена, не доходят руки.

Спасибо. Все работает. Просто изначально делал по инструкции из описания. Там ни слова про это.

**Comment by pozitronik** [comment]
> Спасибо. Все работает. Просто изначально делал по инструкции из описания. Там ни слова про это.

[Вот, первым же пунктом](https://github.com/pozitronik/CloudMailRu#%D0%BA%D0%B0%D0%BA-%D0%B8-%D0%BA%D1%83%D0%B4%D0%B0-%D0%BF%D1%80%D0%B0%D0%B2%D0%B8%D0%BB%D1%8C%D0%BD%D0%BE-%D0%B6%D0%B0%D0%BB%D0%BE%D0%B2%D0%B0%D1%82%D1%8C%D1%81%D1%8F-%D0%BD%D0%B0-%D0%BF%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D1%8B). Не говоря уж о упоминании в этом обсуждении.

**Comment by pozitronik** [comment]
> Падает при попытке освобождения буфера, выделенного под код авторизации. Почему - непонятно.

Копаю: падает при включении оптимизации (**{$O+}**) компилятора, другие настройки (отладочные символы, выравнивание, etc) как будто бы не влияют. Переключение менеджера памяти с основного на отладочный также не влияет.

**Comment by pozitronik** [comment]
Я так и не смог понять, что является причиной ошибки. Включение оптимизаций исключает работу с отладчиком, а отключение оптимизации не воспроизводит ошибку. Основное подозрение - на некорректную обработку буфера в диалоговой функции Total Commander, вторичное - на какую-то ошибку преобразования типов при работе со словарём. Но оба подозрения достаточно необъективны и непроверяемы.

Мне пришлось обойти это, использовав вместо коллбека TC свою диалоговую функцию, благо такая в плагине уже имеется. Она не требует прямой инициализации буфера, и с ней всё отрабатывает хорошо. Просьба проверить на мастер-сборках.
