### ISSUE TITLE
OpenSSL 1.0.2 замена на новый OpenSSL 1.1

### ISSUE THREAD

**Issue by shamarin** [pozitronik/CloudMailRu#245]
Библиотека OpenSSL 1.0.2 уже считается устаревшей и хотелось бы замена на новую библиотеку OpenSSL которая более безопасна.

**Comment by pozitronik** [comment]
К сожалению, поддержка SSL 1.1 пока [не реализована](https://github.com/IndySockets/Indy/issues/183) в библиотеке Indy. Пока ждём.

**Comment by nikolasiii** [comment]
Здравствуйте! Есть какая-то информация по доработке Indy? Может есть какие-то другие компоненты для delphi 10 в которых уже реализовали SSL v1.3 не знаете?

**Comment by pozitronik** [comment]
Информация есть по ссылке на тикет постом выше. Как только тикет закроется, мы об этом узнаем.

Теоретически, можно заменить сетевой движок на curl, но это объём работы, с которым я не готов связываться. Пока что оптимально дождаться доработок в indy.

**Comment by nikolasiii** [comment]
Благодарю!

**Comment by nikolasiii** [comment]
Я очень извиняюсь что пишу сюда, я сейчас удалю. Помогите пожалуйста если не затруднит. В чём может быть проблема. Выходит ошибка. 
Delphi 10
Indy взял здесь: https://github.com/IndySockets/Indy
OpenSSL использую 1.0.2u

Raise exception class EIdOSSLUnderluingCryptoError with message 'Error connecting with SSL. error:1409442E:SSL routines:SSL3_READ_BYTES:tlsv 1 alert protocol version'.

Код такой (основные моменты):
uses IdSSL, IdSSLOpenSSL;
    IOHandler := TIdSSLIOHandlerSocketOpenSSL.Create(nil);
	IOHandler.SSLOptions.SSLVersions := [sslvSSLv2, sslvSSLv23, sslvSSLv3, sslvTLSv1, sslvTLSv1_1, sslvTLSv1_2];
    IOHandler.SSLOptions.Method := sslvTLSv1_2;
	enc := TEncoding.Default;
	ss := TStringStream.Create('',enc);
    http.Get(URL, ss);
	
URL поддерживает и v1.2 и v1.3, я проверил через https://www.wormly.com/test_ssl

**Comment by shamarin** [comment]
> 
> 
> Информация есть по ссылке на тикет постом выше. Как только тикет закроется, мы об этом узнаем.
> 
> Теоретически, можно заменить сетевой движок на curl, но это объём работы, с которым я не готов связываться. Пока что оптимально дождаться доработок в indy.

curl конечно более перспективен.

**Comment by pozitronik** [comment]
> curl конечно более перспективен.

Займётесь?

**Comment by shamarin** [comment]
> 
> 
> > curl конечно более перспективен.
> 
> Займётесь?

На php можно было бы попробовать.

**Comment by pozitronik** [comment]
> На php можно было бы попробовать.

[Пробуйте](https://github.com/pozitronik/cloud-mail-ru-php).

**Comment by g0blin-NN** [comment]
уже 3.
https://www.openssl.org/blog/blog/2021/09/07/OpenSSL3.Final/

**Comment by pozitronik** [comment]
> 
> 
> уже 3.
> https://www.openssl.org/blog/blog/2021/09/07/OpenSSL3.Final/

Нам всё ещё нужна поддержка в Indy.

**Comment by pozitronik** [comment]
Close due to #276
