### ISSUE TITLE
При скачивании частей файла, создавать на диске sparse файл исходного размера

### ISSUE THREAD

**Issue by z0hm** [pozitronik/CloudMailRu#246]
Если, конечно, возможно писать в файл со смещениями, равными сумме предыдущих частей.
Это позволит избежать необходимости иметь свободное место = 2 х размер_файла для последующей локальной его склейки.

Если это невозможно, то реализовать автоматическую склейку путём доклеивания к предыдущей части, начиная с момента загрузки и проверки первых 2-х частей.

**Comment by pozitronik** [comment]
Плагин не занимается склейкой частей файлов, только разбитием. Тому есть две причины:
Во-первых, этот функционал изначально есть в TC (хотя только для локальных файлов), и дублировать его в плагине нерационально.
Во-вторых, плагин ничего не может гарантированно знать о частях файлов в облаке, даже если разбитие происходило через него. Максимум - можно сделать предположение, проанализировав имена файлов и наличие *.crc (как и сделано в TC); но в любом случае пользователь сам, в явном виде, должен указывать/подтверждать это. Реализовать это, в принципе можно, но я предвижу некоторые неоднозначные моменты, которые будет трудно обойти в существующем WFX API.
Итого, по некоторому размышлению, прихожу к выводу, что оно того не стоит: это будет попытка дублировать уже имеющуюся возможность со смутными перспективами удачной реализации.
