### ISSUE TITLE
Не подключается к облаку 403 Forbidden

### ISSUE THREAD

**Issue by OmlineEditor** [pozitronik/CloudMailRu#247]
TC 9.51
Plugin v05042020
Win 7 x64

Вчера все работало со всеми облаками, а сегодня появилось сообщение об ошибке, как в прошлый раз 4 месяца назад когда что-то поменяли в облаке:
EIdHTTPProtocolException ошибка с сообщением: HTTP/1.1 403 Forbidden при отправке данных на адрес https://cloud.mail.ru/api/v2/user/space?home=/&api=2&build=... и тут куча не понятных данных включая пароль и логин.
ответ сервера: {"email":"user@mail.ru","body":"token","time":1596724739914,"status":403}

Можете посмотреть и поправить?

**Comment by BlackBoxJack** [comment]
https://habr.com/ru/company/mailru/blog/513356/
Вот они что-то там поменяли, и у меня тоже не работает 👍

**Comment by Student152** [comment]
TC 9.0
Plugin v05042020
Win 7 x64

Перестал соединяться 09/08 с ошибкой Login to ***@mail.ru error: parsing auth token for ***@mail.ru

**Comment by pozitronik** [comment]
Не могу воспроизвести ни на релизной, ни на текущей мастер-версии. Это не значит, что проблемы не существует, это значит, что она меня не коснулась.

**Comment by nonameformr** [comment]
тож работает )

**Comment by Student152** [comment]
> TC 9.0
> Plugin v05042020
> Win 7 x64
> 
> Перестал соединяться 09/08 с ошибкой Login to ***@mail.ru error: parsing auth token for ***@mail.ru

Сегодня всё работает как обычно

**Comment by OmlineEditor** [comment]
Кажется проблема пропала сама собой, прошло пару дней и вроде щас все нормально. Возможно это временная проблема была. Тикет закрываю.
