### ISSUE TITLE
Невозможно скачивать/загружать/расшаривать - сплошные ошибки EIdHTTPProtocolException с 403 при отправке по адресам https://cloud.mail.ru/api/v2/dispatcher/  и https://cloud.mail.ru/api/v2/file/publish,

### ISSUE THREAD

**Issue by Corak667** [pozitronik/CloudMailRu#248]
Невозможно скачивать/загружать/расшаривать - сплошные ошибки EIdHTTPProtocolException с 403 при отправке по адресам https://cloud.mail.ru/api/v2/dispatcher/  и https://cloud.mail.ru/api/v2/file/publish,

лог
"
EIdHTTPProtocolException ошибка с сообщением: HTTP/1.1 403 Forbidden при отправке данных на адрес https://cloud.mail.ru/api/v2/dispatcher/, ответ сервера: {"email":"inferanaloos@mail.ru","body":"token","time":1597245444651,"status":403}
EIdHTTPProtocolException ошибка с сообщением: HTTP/1.1 403 Forbidden при отправке данных на адрес https://cloud.mail.ru/api/v2/file/publish, ответ сервера: {"email":"inferanaloos@mail.ru","body":"token","time":1597245450409,"status":403}
"

**Comment by pozitronik** [comment]
Подтверждаю.

**Comment by midi-creator** [comment]
та жа фигня ((((((((((

**Comment by cheldonic** [comment]
Я так понимаю это после обновления десятки. На других машинах, где обновлений не было и проблем нет

**Comment by Corak667** [comment]
> Я так понимаю это после обновления десятки. На других машинах, где обновлений не было и проблем нет

Нет, это у всех, у меня XP например

**Comment by kybyx** [comment]
> Я так понимаю это после обновления десятки. На других машинах, где обновлений не было и проблем нет
Да, никто вашу десятку не юзает кроме вас. Большинство осталось на "православной" семёре. Судя по вашему каменду другие машины вы не юзали просто.

> Невозможно скачивать/загружать/расшаривать - сплошные ошибки EIdHTTPProtocolException с 403 при отправке
Подтверждаю, сегодня с утра как раз попал в момент когда всё меняли у себя мыловцы. И смена юзер агента больше не спасает к сожалению... 

> это у всех,
Угу, и AirExplorer перестал работать с мейлом. 
Однако я сильно удивился когда увидил что эмулятор вебдава wdmrc продолжил работать. В чём их секрет интересно. Наверно какой-то устаревший юзерагент юзают так что вебинтерфейс мыла их жалеет.

**Comment by yar229** [comment]
> Однако я сильно удивился когда увидил что эмулятор вебдава wdmrc продолжил работать. В чём их секрет интересно. Наверно какой-то устаревший юзерагент юзают так что вебинтерфейс мыла их жалеет.

Другие протоколы используются.

**Comment by alexer40** [comment]
Может помогут мои наблюдения.
1. Вышла исправленная версия Air Explorer version 3.0.5 August 13, 2020 -Fixed mail.ru support.
2. Установил, смотрю сниффером. Получается После авторизации АЕ запрашивает новый токен, затем проверяет его запросом свободного места и если ошибка снова запрос нового токена, проверка. Если норм использует для загрузки файла.
http://prntscr.com/tziocw

**Comment by pozitronik** [comment]
Да, спасибо. Проблема пока больше в отсутствии у меня времени, чем в технических вещах.

**Comment by Student152** [comment]
Несколько дней назад работало и вот опять:

Current download shard is undefined, trying to get one
EIdHTTPProtocolException ошибка с сообщением: HTTP/1.1 403 Forbidden при отправке данных на адрес https://cloud.mail.ru/api/v2/dispatcher/, ответ сервера: {"email":"r*********v@inbox.ru","body":"token","time":1597506908007,"status":403}

**Comment by ralexxx** [comment]
3 дня назад перестали работать Plugin TC CloudMailRu и AirExplorer 
Система Win7 64-bit

**Plugin TC CloudMailRu**
Папка открывается
Файл открыть нельзя
Файл скопировать с облака нельзя
при попытке записи на облако выдает ошибку Error: The remote server returned an error: (403) Forbidden

**AirExplorer** 
Папка открывается
Файл открыть можно
Файл скопировать с облака можно
при попытке записи на облако выдает ошибку Error: The remote server returned an error: (403) Forbidden

Кто-то писал в поддержку MailRu? Похоже проблема у них...

**Comment by alexer40** [comment]
AirExplorer уже сделали исправление 13 числа, но похоже кривое.
Air Explorer version 3.0.5 August 13, 2020 -Fixed mail.ru support.
> Кто-то писал в поддержку MailRu? Похоже проблема у них...
А смысл? Это неофициальный API.

**Comment by OmlineEditor** [comment]
Есть ли возможность у mail.ru определить чем мы пользуемся браузером или сторонним плагином? 
Могут ли они так бороться с неофициальными клиентами?
По идеи не должны но у меня есть сомнения.

**Comment by pozitronik** [comment]
Определённо я знать не могу. Плагин - это почти тот же браузер, но это "почти" оставляет предостаточное пространство для маневра.
Энивей, пока план прежний: буду смотреть, как браузер "общается" с облаком, и воспроизводить у себя.

**Comment by ralexxx** [comment]
> > Кто-то писал в поддержку MailRu? Похоже проблема у них...
> 
> А смысл? Это неофициальный API. И это проблема в измененном API

Привык к этому плагину!!! 
Я все-таки написал в поддержку MailRu
https://help.mail.ru/cloud_web/confines

Вот что они ответили:
Здравствуйте.
Указанное ПО не является нашим, поэтому мы не можем нести ответственность
за его работоспособность.
С уважением, Илья П.
Служба поддержки пользователей
Облако Mail.ru

**Comment by Owyn** [comment]
Лучшеб написали им чтоб они возможность сохранять оригинальные даты файлов при загрузке сделали чем просить починить чужое ПО =_=

**Comment by alexer40** [comment]
Хочу сообщить момент, теперь токен живет около 1-1.10  часа, потом его перезапрашивать надо.

**Comment by tormanidze** [comment]
Я с вас просто офигеваю. Именно майл.ру и уменьшило **специально** время жизни токена, чтобы бороться с левыми приложениями, потому что для работы с облаком у них есть своё приложение, и внезапно оно платное. Ржал с такого наива сегодня полдня, даже зарегился специально.

**Comment by alexer40** [comment]
> Я с вас просто офигеваю. Именно майл.ру и уменьшило специально время жизни токена, чтобы бороться с левыми приложениями,

Вы не правы, это рекомендуемое поведение стандарта Oauth авторизации. К примеру так ведет себя гуглдрайв, яндекс диск (на пол года выдают).

**Comment by kybyx** [comment]
> Вы насмешили своим комментом множество программистов просто им лень регистрироваться

Настоящие программисты никогда  и не за что на гитхабе не зарегаются, он же теперь Мелкомягкий ;)

>А AE через некоторое время не работает, токен устаревает а новый он не запрашивает.

Ну так оформите багрепорт и отошлите УАЕ арзработчику, что бы исправил новый баг. Он  же бапки получает за свой софтец

**Comment by pozitronik** [comment]
Покопался с запросами. Произошли два изменения:
1. Теперь токен передаётся не в GET-запросе, а в заголовке X-CSRF-Token. С добавлением такого заголовка всё начинает работать.
2. Токен, видимо, действительно теперь протухает в течение часа. Нужно определять протухание (по коду ответа) и перезапрашивать.
Никакой конспирологии тут нет, это вполне логичные изменения. Мне потребуется некоторое время на актуализацию кода, но проблема выглядит решённой.

- [ ] Проверить работу с публичными аккаунтами.

**Comment by tormanidze** [comment]
Ну-у, не знаю. В моей вселннной, друзья, вполне логичным выглядят действия майл.ру по ограничению функционала бесплатных прикладух. И обращения в их поддержку очень смешны!

**Comment by ralexxx** [comment]
> Лучшеб написали им чтоб они возможность сохранять оригинальные даты файлов при загрузке сделали чем просить починить чужое ПО =_=
Действительно! не обращал внимания... с датами ерунда полная. 
Напишу!

**Comment by pozitronik** [comment]
Исправления в master и в релизах.

Я **не уверен**, что протухший токен обновится, как ожидается - у меня просто нет времени ждать протухания, чтобы посмотреть, как отработает функция перезапроса. По видимой логике - всё должно быть хорошо, но тестирование не проводилось.
В остальном всё работает.

Пожалуйста, пишите здесь только то, что непосредственно относится к обсуждаемой проблеме, оффтопик тратит моё и ваше время. Спасибо.

**Comment by tormanidze** [comment]
Логинится нормально, папки все видны, но ни скачать, ни загрузить не даёт.
`CONNECT \***
Login to ***@mail.ru
Current upload shard is undefined, trying to get one
Connected to ***@mail.ru
Total space: 1024 Gb, used: 297 Gb, free: 726 Gb.
Current download shard is undefined, trying to get one
EIdHTTPProtocolException ошибка с сообщением: HTTP/1.1 403 Forbidden при отправке данных на адрес https://cloud.mail.ru/api/v2/dispatcher/, ответ сервера: {"email":"***@mail.ru","body":"token","time":1597910609612,"status":403}
Total space: 1024 Gb, used: 297 Gb, free: 726 Gb.
Current upload shard is undefined, trying to get one
EIdHTTPProtocolException ошибка с сообщением: HTTP/1.1 403 Forbidden при отправке данных на адрес https://cloud.mail.ru/api/v2/dispatcher/, ответ сервера: {"email":"***@mail.ru","body":"token","time":1597910623933,"status":403}
EIdHTTPProtocolException ошибка с сообщением: HTTP/1.1 403 Forbidden при отправке данных на адрес ?cloud_domain=2&x-email=***%40mail.ru, ответ сервера: {"email":"***@mail.ru","body":"token","time":1597910624004,"status":403}
Current upload shard is undefined, trying to get one
EIdHTTPProtocolException ошибка с сообщением: HTTP/1.1 403 Forbidden при отправке данных на адрес https://cloud.mail.ru/api/v2/dispatcher/, ответ сервера: {"email":"***@mail.ru","body":"token","time":1597910627730,"status":403}
EIdHTTPProtocolException ошибка с сообщением: HTTP/1.1 403 Forbidden при отправке данных на адрес ?cloud_domain=2&x-email=***%40mail.ru, ответ сервера: {"email":"***@mail.ru","body":"token","time":1597910627783,"status":403}
Current upload shard is undefined, trying to get one
EIdHTTPProtocolException ошибка с сообщением: HTTP/1.1 403 Forbidden при отправке данных на адрес https://cloud.mail.ru/api/v2/dispatcher/, ответ сервера: {"email":"***@mail.ru","body":"token","time":1597910628421,"status":403}
EIdHTTPProtocolException ошибка с сообщением: HTTP/1.1 403 Forbidden при отправке данных на адрес ?cloud_domain=2&x-email=***%40mail.ru, ответ сервера: {"email":"***@mail.ru","body":"token","time":1597910628460,"status":403}
Total space: 1024 Gb, used: 297 Gb, free: 726 Gb.
`

**Comment by coldun** [comment]
@tormanidze, а версия плагина точно последняя, ? В исправленной всё работает нормально.
![Запись_2020_08_20_12_55_32_361](https://user-images.githubusercontent.com/38978645/90757751-b4174200-e2e6-11ea-9484-56900467ae60.gif)

**Comment by Owyn** [comment]
Стоит папка облака по умолчанию для правой стороны, т.е. при запуске ТС сразу спрашивает пароль для входа, но после его ввода не входит - пишет `error: parsing auth token for user@mail.ru`, хотя если после этого вручную зайти в netowrking - mail cloud и опять ввести пароль - то нормально входит и грузит всё

```
CONNECT \User
Login to User@mail.ru
error: parsing auth token for User@mail.ru
CONNECT \User
Login to User@mail.ru
Connected to User@mail.ru
```

**Comment by pozitronik** [comment]
> Логинится нормально, папки все видны, но ни скачать, ни загрузить не даёт.

По логу похоже на проблему получения шарда. У себя воспроизвести не могу, но проверю.
 
> 
> Стоит папка облака по умолчанию для правой стороны, т.е. при запуске ТС сразу спрашивает пароль для входа, но после его ввода не входит - пишет `error: parsing auth token for user@mail.ru`, хотя если после этого вручную зайти в netowrking - mail cloud и опять ввести пароль - то нормально входит и грузит всё
> 

Не подтверждаю.

**Comment by tormanidze** [comment]
> @tormanidze, а версия плагина точно последняя, ? В исправленной всё работает нормально.
Действительно: ссылка на !текущий стабильный релиз! ведёт на прошлую версию. В новой всё ОК.

**Comment by pozitronik** [comment]
> 
> 
> > @tormanidze, а версия плагина точно последняя, ? В исправленной всё работает нормально.
> > Действительно: ссылка на !текущий стабильный релиз! ведёт на прошлую версию. В новой всё ОК.

Всё верно, последний релиз был помечен как пред-релизный (это логично, с учётом внесённых изменений). Убрал пометку, чтобы не было разночтений.

**Comment by nikorn** [comment]
При скачивании последнего релиза Microsoft Windows Defender ругается на 32-разрядную версию файла - содержит троян (см. прилагаемый скриншот). **Что это может быть?**
![trojan](https://user-images.githubusercontent.com/11365254/91025604-4cbd0300-e602-11ea-8984-66d21dd483fe.jpg)
Работа 64-разрядной версии при этом не нарушается.

**Comment by pozitronik** [comment]
Пожалуйста, по другим проблемам заводите новые тикеты.

**Comment by nikorn** [comment]
Хорошо. Понял.
Написал в ту же ветку, поскольку проблема относится только к
этому конкретному исправлению/релизу. В прошлой версии этого не было
---
Никита Корняков


пн, 24 авг. 2020 г. в 12:22, Pavel Dubrovsky <notifications@github.com>:
