### ISSUE TITLE
Возможность заливать файл из нескольких буферов в памяти поступающих последовательно

### ISSUE THREAD

**Issue by Laex** [pozitronik/CloudMailRu#25]

**Comment by pozitronik** [comment]
?

**Comment by Laex** [comment]
Dokan. При копировании файл поступает кусками.

**Comment by pozitronik** [comment]
Мне это ни о чём не говорит. Пожалуйста объясните идею, что это даст, и как это реализуется.

**Comment by Laex** [comment]
Реализуется доступ к облаку через виртуальный диск файловой системы (например, M:\) на основе библиотеки Dokan. Запись фала осуществляется драйвером Dokan путем передачи в процедуру буфера с куском файла. Размер куска зависит от программы, которая выполняет копирование и для больших файлов может быть передано, например, 10-20 кусков по 500кБ.

**Comment by pozitronik** [comment]
Я всё ещё не улавливаю идею.
Бегло ознакомился с описанием Dokan - похоже на аналог fuse. Вы предлагаете сделать с его помощью доступ для всей системы?

**Comment by Laex** [comment]
Ага

**Comment by pozitronik** [comment]
Интересная идея, но я вряд ли потяну по времени. Если найдутся желающие сделать форк - буду рад, может даже поучавствую.
