### ISSUE TITLE
Не обновляется устаревший токен

### ISSUE THREAD

**Issue by OmlineEditor** [pozitronik/CloudMailRu#254]
Вы только частично решили проблему с обновлением токенов при закачке данных в версии v19082020.
Если загружать за 1 раз большой объем данных (например много файлов большого объема или один большой файл на 6 Гб и более) токен не обновляется и вываливается ошибка.
Во пример логов когда заливается несколько больших файлов:
`Current upload shard is undefined, trying to get one
Shard received: https://cld-upload8.cloud.mail.ru/upload-web/, type: upload
d:\films\SerialS01E06.mkv->\Mail.ru\serial\SerialS01E06.mkv
d:\films\SerialS01E07.mkv->\Mail.ru\serial\SerialS01E07.mkv
d:\films\SerialS01E08.mkv->\Mail.ru\serial\SerialS01E08.mkv
d:\films\SerialS01E09.mkv->\Mail.ru\serial\SerialS01E09.mkv
d:\films\SerialS01E10.mkv->\Mail.ru\serial\SerialS01E10.mkv
d:\films\SerialS01E11.mkv->\Mail.ru\serial\SerialS01E11.mkv
d:\films\SerialS01E12.mkv->\Mail.ru\serial\SerialS01E12.mkv
Требуется обновить CSRF-токен при отправке данных на адрес https://cloud.mail.ru/api/v2/file/add
Error uploading file d:\films\SerialS01E13.mkv Retry attempt 1 of 1
Требуется обновить CSRF-токен при отправке данных на адрес https://cloud.mail.ru/api/v2/file/add
Требуется обновить CSRF-токен при отправке данных на адрес https://cloud.mail.ru/api/v2/file/add
Требуется обновить CSRF-токен при отправке данных на адрес https://cloud.mail.ru/api/v2/file/add`

После заливки примерно 5 Гб появляется ошибка, это заливка примерно шла 1 час.

Прошу добавить возможность обновлять токен через определенное время, например включать таймер и как прошло 50 минут, то поставить на паузу загрузку или скачку данных, обновить токен и потом продолжить с новым токеном.

**Comment by pozitronik** [comment]
Теоретически, после сообщения о требовании обновления токена должно это самое обновление произойти. А вслед за этим - повторение последней сбойной операции. Но это поведение не проверялось.
Проверим, починим.

**Comment by OmlineEditor** [comment]
> ... А вслед за этим - повторение последней сбойной операции. 

Если грузится файл 6 Гб и он обрывается то потом заново все начинается? Как сбойная операция повторяется? Если файл большой и все начинается с начала то тогода **вообще никогда** он не загрузится. Нужно как-то продолжать и ставить на паузу до момента проблемы. Надеюсь вы решите проблему.

**Comment by pozitronik** [comment]
Предполагается, что токен разрешает операцию (например, загрузку файла), и если его TTL истекает до завершения этой операции, то на саму операцию это уже не влияет. Но если произошёл сбой передачи, то и токен нужно перезапрашивать.
Пока что наиболее логичное предположение в том, что токен не перезапрашивается.

**Comment by alexer40** [comment]
На сколько я помню, сама загрузка файла токен не требует, а вот следующая операция фиксации - ADD уже требует.  Если add после загрузки не проверяет токен то на 6 гб он точно устаревает и требует обновления.
Смотрю код и что-то не вижу повтор операции addFileByIdentity в случае ошибки получения токена. Может я не прав.

**Comment by OmlineEditor** [comment]
Новые типы ошибок появились при заливке больших файлов, возможно это чем-то поможет
`Current upload shard is undefined, trying to get one`
`Shard received: https://cld-upload4.cloud.mail.ru/upload-web/, type: upload`
`EIdSocketError ошибка сети: Socket Error # 10054`
`Connection reset by peer. при отправке данных на адрес https://cld-upload4.cloud.mail.ru/upload-web/?cloud_domain=2&x-email=*****%40mail.ru`
`Error uploading file d:\soft\nc.7z Retry attempt 1 of 1`
`EIdSocketError ошибка сети: Socket Error # 10054`
`Connection reset by peer. при отправке данных на адрес https://cld-upload4.cloud.mail.ru/upload-web/?cloud_domain=2&x-email=*****%40mail.ru`

**Comment by alexer40** [comment]
> EIdSocketError ошибка сети: Socket Error # 10054
Это не похоже на проблему в программе. Это или ошибка в сети (связь ваш комп - ваша сеть-провайдер-яндекс сервер), например сбойнуло любое оборудование на этом пути, а может  и конечная точка - сервер яндекс не отвечает/оборвал связь.
> Ошибка "Connection reset by peer", которая возникает на клиенте, говорит о том, что удаленная сторона, возможно сервер, разорвала соединение. Причин может быть огромное количество.

**Comment by pozitronik** [comment]
Мне не удалось воспроизвести в точности описанную ситуацию, но я могу предположить, как это может происходить. Вкратце - предположение @alexer40 вполне оправдано. Плюс, я добавил проверки протухания токена к другим операциям - созданию/удалению объектов, клонированию, в общем, везде, где это может пригодиться.
Билды в master.

**Comment by OmlineEditor** [comment]
Вот еще иногда бывает так: - загружается через раз и с ошибкой, но загружается. Вот лог:
`Current upload shard is undefined, trying to get one`
`Shard received: https://cld-upload10.cloud.mail.ru/upload-web/, type: upload`
`EIdSocketError ошибка сети: Socket Error # 11002`
 `при отправке данных на адрес https://cld-upload10.cloud.mail.ru/upload-web/?cloud_domain=2&x-email=***%40mail.ru`
`Error uploading file f:\folder\films.mp4 Retry attempt 1 of 1`
`f:\folder\films.mp4->\cloud\folder\films.mp4`

**Comment by pozitronik** [comment]
Это ошибки на сети, к проблеме обновления токена отношения не имеющие.

**Comment by OmlineEditor** [comment]
> Это ошибки на сети, к проблеме обновления токена отношения не имеющие.

Вы закрыли тикет но новой версии программы нет. Проблема решена? Если да то где новая версия программы?

**Comment by pozitronik** [comment]
Билды в мастер-ветке, о чём написано парой сообщений выше.

**Comment by OmlineEditor** [comment]
> Билды в мастер-ветке, о чём написано парой сообщений выше.

Невижу я в мастер ветке этой новой версии, там только за 18 августа старая версия,  где вы ее увидели дайте ссылку.

**Comment by pasha00000** [comment]
> Невижу я в мастер ветке этой новой версии, там только за 18 августа старая версия, где вы ее увидели дайте ссылку.
https://github.com/pozitronik/CloudMailRu/blob/master/MailRuCloud.wfx
https://github.com/pozitronik/CloudMailRu/blob/master/MailRuCloud.wfx64

**Comment by OmlineEditor** [comment]
> > Невижу я в мастер ветке этой новой версии, там только за 18 августа старая версия, где вы ее увидели дайте ссылку.
> 
> https://github.com/pozitronik/CloudMailRu/blob/master/MailRuCloud.wfx
> https://github.com/pozitronik/CloudMailRu/blob/master/MailRuCloud.wfx64

Я никогда не искала готовые новые версии файлов прямо в исходном коде. Вы меня удивили.
Если новая версия нормально работает поместите ее в: https://github.com/pozitronik/CloudMailRu/releases

**Comment by pozitronik** [comment]
Здесь ресурс для разработчиков, не магазин приложений.

**Comment by OmlineEditor** [comment]
> Здесь ресурс для разработчиков, не магазин приложений.

если вы выпустили новую версию в чем проблема добавить ее в releases? Ведь другие пользорватели могут и не заметить что вы там в коде что-то изменили и выложили программу прямо рядом с кодом, а не в releases.

**Comment by pozitronik** [comment]
Процесс ведётся так:
- Пользователи сообщают о проблеме/пожелании, заводя тикет.
- Я делаю доработку, собираю билд (билд попадает в версионирование, что тоже бывает важно). Сообщаю о изменении в тикете, ожидая реакции пользователя. Если никакой реакции на ответ нет длительное время, я делаю вывод, что всё хорошо и закрываю тикет. Это оправдано, т.к. некоторые пользователи хотят только сообщить о проблеме, но не интересуются дальнейшим процессом, полагаясь на разработчика.
Таким образом, пользователи отслеживающие разработку, могут получать самые свежие сборки, выступая в роли добровольных тестеров.
- После того, как наберётся достаточное число проверенных изменений/исправлений, я собираю и выкладываю релиз для всех остальных.

Вести обсуждения этого порядка я не намерен.

**Comment by OmlineEditor** [comment]
> Процесс ведётся так:

Вы могли бы выпускать версии и выкладывать их в releases, но только помечать их как Beta. Тогда все пользователи будут видеть что есть новая версия но она может быть не стабильная. Новую версию не нужно искать ее сразу видно и больше пользователей смогут принять участие в проверке. А как только все проверили выпускаете новую версию и подписываете ее Stable. Я думаю это более логичный вариант. Что вы думаете по этому поводу?
