### ISSUE TITLE
Команда clone клонирования в публичный каталог не работает. 

### ISSUE THREAD

**Issue by Corak667** [pozitronik/CloudMailRu#256]
Пытаюсь клонировать данные из публичного линка в папку другого диска через команду clone - но не работает. 
Можете починить?

**Comment by pozitronik** [comment]
А какая точно последовательность действий?

**Comment by Corak667** [comment]
1. Расшариваю ссылку к любому файлу или директории, через свойства или браузер.
2. Захожу через TC и в FS плагине в целевую папку (на другом аккаунте) куда копировать данные
3. Ввожу в адресной строке TC: clone https://cloud.mail.ru/public/GSZa/#### 
(clone адрес-линка).
никакого результата

**Comment by pozitronik** [comment]
Исправлено, билд в мастер-ветке.
