### ISSUE TITLE
Enter auth key ERROR

### ISSUE THREAD

**Issue by Keks1984** [pozitronik/CloudMailRu#257]
Не работает. Просит код из приложения. до этого все работало.

**Comment by pozitronik** [comment]
Пожалуйста, опишите проблему так, [как требуется](https://github.com/pozitronik/CloudMailRu#%D0%BA%D0%B0%D0%BA-%D0%B8-%D0%BA%D1%83%D0%B4%D0%B0-%D0%BF%D1%80%D0%B0%D0%B2%D0%B8%D0%BB%D1%8C%D0%BD%D0%BE-%D0%B6%D0%B0%D0%BB%D0%BE%D0%B2%D0%B0%D1%82%D1%8C%D1%81%D1%8F-%D0%BD%D0%B0-%D0%BF%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D1%8B).

**Comment by Keks1984** [comment]
Все разобрался. Удалил доверенные приложения через браузер. При новом входе он начал просить не смс ввести, а считать qr код приложение почты на телефоне. Отключил двухфакторную авторизацию и все заработало.
