### ISSUE TITLE
Ошибка FsPutFileW! External exception EEDFADE при одновременном перемещении файлов внутри каталогов и копировании на сервер (в фоне и другой области диска).

### ISSUE THREAD

**Issue by Corak667** [pozitronik/CloudMailRu#262]
Ошибка FsPutFileW! External exception EEDFADE при одновременном перемещении файлов внутри каталогов и копировании на сервер (в фоне и другой области диска, с авто-пропуском файлов с тем же именем).
<img src="http://coraksoft1.narod.ru/scr/160483820978_kiss_12kb.png">
скрин: http://coraksoft1.narod.ru/scr/160483820978_kiss_12kb.png

"
---------------------------
Total Commander 9.51
---------------------------
Exception in MailRuCloud.wfx:FsPutFileW!
External exception EEDFADE
Windows XP SP3 5.1 (Build 2600), base: 00400000

Please report this error to the Author, with a description
of what you were doing when this error occurred!

Windows exception: 0EEDFADE
Stack trace:
061BB2FB

Raw:
00402249  00403414  004021C8  0041FE89  >0041FE89  004201A7
004EFFFE  0044FFFE  0044FFFE  0044FFFE  004020A2  00402226
00402249  00417F34  00417BC1  004194F9  00403670  
Press Ctrl+C to copy this report!
---------------------------
ОК   
---------------------------

**Comment by pozitronik** [comment]
Нужен подробный пошаговый протокол действий.
