### ISSUE TITLE
невозможно получить токен авторизации и войти в свое облако. "error: parsing auth token for *@mail.ru"

### ISSUE THREAD

**Issue by Corak667** [pozitronik/CloudMailRu#267]
Там сейчас невозможно получить токен авторизации и войти в свое облако. 
ошибка: "error: parsing auth token for *@mail.ru"
лог:
"
Login to corakdoom@mail.ru
Requesting auth token for corakdoom@mail.ru
Parsing token data...
error: parsing auth token for corakdoom@mail.ru
"

**Comment by coldun** [comment]
```
CONNECT \IceBox
Login to *****@mail.ru
EIdSocketError ошибка сети: Socket Error # 10054
Connection reset by peer. при отправке данных на адрес https://auth.mail.ru/cgi-bin/auth?from=splash
error: getting auth token for *****@mail.ru
```

**Comment by pozitronik** [comment]
На серверах опять блокируют "устаревшие" браузеры по UserAgent.
Чтоб заработало, на вкладке Network Settings включить галку Change plugin UserAgent и заменить строку например, на:
`Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/837.36 (KHTML, like Gecko) Chrome/90.0.3987.162 Safari/837.36/TCWFX(x64)`

Обновлённую сборку попозже сделаю.

**Comment by thisVioletHydra** [comment]
заменил на `Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Mobile Safari/537.36`
не помогает

**Comment by pozitronik** [comment]
У меня работает даже с UserAgent по умолчанию. Возможно, здесь иная проблема, но я ничего не могу сказать конкретно.
