### ISSUE TITLE
Не входит в облако mail.ru

### ISSUE THREAD

**Issue by nikorn** [pozitronik/CloudMailRu#270]
Похоже, mail.ru опять поменял алгоритм работы.

Total Commander 9.22 64 bit
Версия плагина от 19.08.2020 (ориентировочно)

Как и в прошлый раз (https://github.com/pozitronik/CloudMailRu/issues/248), при попытке войти в облако пробегает ProgrewssBar но вход не происходит

**Comment by OLEG4120** [comment]
Обновите плагин,

https://github.com/pozitronik/CloudMailRu/issues/267
