### ISSUE TITLE
Перестал входить в публичные ссылки  (Can't get public share download share)

### ISSUE THREAD

**Issue by AlexPi86** [pozitronik/CloudMailRu#271]
Перестал входить в публичные ссылки  (Can't get public share download share)
При входе через браузер пишет, что установлен устаревший браузер.
Просит установить Atom от Mail.ru
Прошу подкрутить, надо сделать, чтобы облако считало, что подключение идёт через Atom.

**Comment by pozitronik** [comment]
[Прочтите, пожалуйста, документацию](https://github.com/pozitronik/CloudMailRu#%D0%BA%D0%B0%D0%BA-%D0%B8-%D0%BA%D1%83%D0%B4%D0%B0-%D0%BF%D1%80%D0%B0%D0%B2%D0%B8%D0%BB%D1%8C%D0%BD%D0%BE-%D0%B6%D0%B0%D0%BB%D0%BE%D0%B2%D0%B0%D1%82%D1%8C%D1%81%D1%8F-%D0%BD%D0%B0-%D0%BF%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D1%8B).
