### ISSUE TITLE
error: parsing auth token for

### ISSUE THREAD

**Issue by debobrov** [pozitronik/CloudMailRu#274]
На прошлой неделе всё работало нормально, ТС не менял, плагин последней версии.
При попытке зайти пишет в логе

CONNECT \mail.ru
Login to *@mail.ru
error: parsing auth token for *@mail.ru

**Comment by pozitronik** [comment]
С лёту не могу воспроизвести - как работало, так работает.

**Comment by debobrov** [comment]
Можно закрывать, проблема прошла сама собой. В чём была причина - не понятно, как ничего не менял, ДО так и ПОСЛЕ. Видимо какой то сбой на мэиле.

**Comment by NewSky13** [comment]
27.05.2021 22:00 по Москве, ровно то же самое. Не пускает.

**Comment by pozitronik** [comment]
По прежнему не могу воспроизвести, соединяется без всяких проблем.

**Comment by NewSky13** [comment]
А, как и, что можно предоставить или, что и как можно попробовать сделать, что бы собрать больше информации чем в логе пишется, потому как по прежнему ровно та же ошибка и даже по публичной ссылке не открывает, а не только по логину и паролю на аккаунт. До этого, модуль работал, не обновлял ни модуль ни ТС, понадобилось воспользоваться и вот оно так...

**Comment by pozitronik** [comment]
Можно попробовать:
1) Проверить вход в облако через браузер, чтобы проверить доступность сервиса.
2) В настройках плагина прописать рабочий прокси и попробовать подключиться через него.
3) (Просто для спокойствия проверить) вписать в настройках плагина свежий UserAgent, типа
>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36

Сейчас никакого отдельного логирования на случай таких проблем не предусмотрено. Такая проблема может возникнуть только на самом базовом уровне авторизации, когда мы бросаем на сервер учётные данные, и ожидаем, что в возвращённом ответе где-то будет csrf-токен, который плагин из ответа выковыряет, и будет использовать уже при работе по API. Ошибка сигнализирует нам, что ответ был, но токена в нём не нашлось: либо отбойник пришёл (не достучались до сервера по какой-то причине), либо формат выдачи поменялся (но тогда бы у всех отвалилось). Логировать это достаточно бессмысленно.

**Comment by NewSky13** [comment]
Спасибо! Первые два пункта не помогли, а третий исправил ситуацию.

**Comment by pozitronik** [comment]
Видимо, там было что-то старое вручную прописано. Если параметр не менялся руками, то плагин будет представляться не самой старой сборкой, банить которую не должны.
