### ISSUE TITLE
Обновил пароль и постоянно "error: parsing auth token for ***@mail.ru" 

### ISSUE THREAD

**Issue by Corak667** [pozitronik/CloudMailRu#275]
Обновил пароль и постоянно теперь не принимает токен -
"CONNECT \0Corak
Login to corakdoom@mail.ru
Requesting auth token for corakdoom@mail.ru
Parsing token data...
error: parsing auth token for corakdoom@mail.ru
"

**Comment by z0hm** [comment]
Не изменял пароль, но вижу тоже самое: error: parsing auth token for ...

**Comment by chorajhn** [comment]
Такая же фигня, че по русски то нельзя описать как решить проблему - 1. сделать то 2 сделать то... итд, копец надо файлы залить и скачать, а я еб#;% с этим "error: parsing auth token for"

**Comment by chorajhn** [comment]
Короче говоря, если такая фигня происходит, то нужно на cloud.mail.ru из браузера зайти - авторизоваться и подтвердить что это ты, там он предложит каким способом, тогда потом через плагин пускает, вот такая вот херня. Кто не знал - теперь в курсе, как и я!

**Comment by iamwayfaring22** [comment]
https://github.com/pozitronik/CloudMailRu/issues/275#issuecomment-915829596
> 
а можно подробнее? такая же беда и никак не могу войти в учетку облака

**Comment by n81665** [comment]
На Mail опять что то ломают , опять нельзя войти в облако через плагин, 


> Короче говоря, если такая фигня происходит, то нужно на cloud.mail.ru из браузера зайти - авторизоваться и подтвердить что это ты, там он предложит каким способом, тогда потом через плагин пускает, вот такая вот херня. Кто не знал - теперь в курсе, как и я!

Не помогает это уже..  Всё равно ошибку выдает..

**Comment by pozitronik** [comment]
Close due to #290
