### ISSUE TITLE
какая логика у плагина?

### ISSUE THREAD

**Issue by g0blin-NN** [pozitronik/CloudMailRu#277]
тотал 10 x64, плагин новее  нет.
я не пойму просто объясните. вот я переношу папку с файлами.
возникает ошибка
`EIdHTTPProtocolException ошибка с сообщением: HTTP/1.1 500 Internal Server Error при отправке данных на адрес https://cld-uploader12.cloud.mail.ru/upload-web/?xxx ответ сервера: Internal Error`
ладно ошибка на сервере. бывает. нужно остановить. но зачем удаляется папка с файлами с компьютера? она же еще не перенесена на 100%. вот это не понятно. из-за такого поведения приходится два раза делать. сначала копировать потом удалять. одновременно опасно. я уже много файлов потерял. перенос опасен.

**Comment by pozitronik** [comment]
Предполагается, что при ошибке на сервере дальнейшие операции с объектом в зависимости от настроек, либо не должны происходить вовсе, либо пользователь должен уведомляться о сбое для дальнейшего выбора действий.
Если описанное поведение присутствует - это баг. Надо поизучать, а на это, к сожалению, сейчас не могу выделить время.

Тикет пусть висит, как доберусь - посмотрю. Инфы для понимания, в принципе, достаточно, но если будут какие-то подробности - это может помочь.

**Comment by g0blin-NN** [comment]
может это важно. я не знаю. тотал на компьютере с плагином. папки с файлами на шаре. к роутеру подключен жесткий диск. и вот я переношу с жесткого диска роутера в облако файлы папками. при ошибке та папка что копировалась в данный момент просто исчезает с жесткого диска на роутере и не важно сколько там файлов оставалось в папке.

**Comment by g0blin-NN** [comment]
похоже плагин не актуален уже? webdav заработал на всех аккаунтах. не только платных. нужно создать пароль в "Пароли для внешних приложений" на https://id.mail.ru/security
