### ISSUE TITLE
gitreleases.dev deprecated

### ISSUE THREAD

**Issue by mweibel** [pozitronik/CloudMailRu#279]
hi!

I'm the author of [gitreleases.dev](https://gitreleases.dev) and saw that you used gitreleases.dev somewhere in this repository. I can't find it in the code so maybe you removed the link already. 
Just a heads-up that gitreleases.dev will be shut down soon. GitHub has meanwhile added support for linking directly to assets:
https://docs.github.com/en/repositories/releasing-projects-on-github/linking-to-releases

**Comment by pozitronik** [comment]
Hi, @mweibel!
This is the first time I hear about gitreleases.dev and have never used it. It's some kind of mistake, i think.

**Comment by mweibel** [comment]
ok then nevermind :)
