### ISSUE TITLE
Socket Error # 10054

### ISSUE THREAD

**Issue by grisha999** [pozitronik/CloudMailRu#283]
CONNECT \grisha
Login to grisha999@mail.ru
EIdSocketError ошибка сети: Socket Error # 10054
Connection reset by peer. при отправке данных на адрес https://auth.mail.ru/cgi-bin/auth?from=splash
error: getting auth token for grisha999@mail.ru

У меня Win 7 64bit TC 10.50

**Comment by pozitronik** [comment]
Проблема соединения, плагин не может достучаться до указанного адреса.
Проверять сеть, настройки фаервола, прокси, etc.
