### ISSUE TITLE
Перестали работать публичные ссылки.

### ISSUE THREAD

**Issue by kraamis** [pozitronik/CloudMailRu#284]
![Image-013.png](https://user-images.githubusercontent.com/28429238/181752467-2046b2d2-d1e7-4679-8c54-c56936e4b13d.png)

Версии плагина и тотал последние. Винда семёрка и десятка.  На чистом тотале тоже не работает.

**Comment by pozitronik** [comment]
Да, что-то сломалось, постараюсь на выходных посмотреть.

Кстати, что за коллекция Модели?

**Comment by kraamis** [comment]
Из группы ВКонтакте https://vk.com/mdsplay

Там даже за этот год есть записи.

**Comment by pozitronik** [comment]
[Проверяем](https://github.com/pozitronik/CloudMailRu/releases/tag/v290722)

**Comment by kraamis** [comment]
Заработало. Все открывается.

Спасибо!
