### ISSUE TITLE
Прямые ссылки в разделе Download links не работают.

### ISSUE THREAD

**Issue by pozitronik** [pozitronik/CloudMailRu#285]
Subj

**Comment by pozitronik** [comment]
Было:
`https://cloclo11.cloud.mail.ru/public/2pMAChBCaJkuxZYf5QQ/g/no/E8A9/5SooBPVTY/LOSSLESS_VA/[1990] VA - Real Sadness & Other Gregorian Mysteries/Real Sadness & Other Gragorian Mysteries.CUE`

Стало:
`https://cloclo11.cloud.mail.ru/public/2pMAChBCaJkuxZYf5QQ/g/no/E8A9/5SooBPVTY/`
 => 302 редирект на
`https://cloclo11.datacloudmail.ru/public/get/7XMtyzwhcxkWxPPBqZG4dgeb9hhMuDE5zh2wunLu5nknFiCvf2q58jNYYKB7sEfMd6KAmt/no/Real%20Sadness%20%26%20Other%20Gragorian%20Mysteries.CUE`

Вероятно, как временное решение достаточно переформировать ссылку, оставив редирект. Как полное решение - выяснить, как теперь формируются URI и изменить логику формирования.

**Comment by pozitronik** [comment]
Разобрался: для ссылок на каталоги/файлы ссылки формируются по разному, всегда требуют UrlEncode() и всегда отвечают редиректом на постоянный линк.

**Comment by Immick** [comment]
@pozitronik проблема наблюдается вновь. Про обращении по прямой ссылке выдает:

`{ "error": "nosdc" }`
