### ISSUE TITLE
Работа с копированием файлов в фоновом режиме (опционально)

### ISSUE THREAD

**Issue by codestudioua** [pozitronik/CloudMailRu#29]
Сделать как в FTP - возможность закачки/добавления файлов в список загрузок в фоне, чтоб в то же время можно было работать с другими операциями в ТС.

**Comment by pozitronik** [comment]
Список закачки для WFX-плагинов не поддерживается в Total Commander. Фоновая работа реализована.

**Comment by codestudioua** [comment]
А как можно фоновую работу протестировать?
Вижу только паузу: [http://take.ms/Ak1Tb](url)

**Comment by pozitronik** [comment]
Обновите плагин, будет кнопка фоновой работы.
