### ISSUE TITLE
Отображение свободного места в Gb, Mb

### ISSUE THREAD

**Issue by vovka36** [pozitronik/CloudMailRu#30]
Было бы неплохо отображать занятое/свободное место в гигабайтах, когда объем более 1 Гб. Или хотя бы разбивать пробелом значение в мегабайтах.
Так есть сейчас, не очень читабельно:
Total space: 1048576Mb, used: 36353Mb, free: 1012223Mb.
Хотелось бы так:
Total space: 1 Tb, used: 35.50 Gb, free: 988.50 Gb.
Или хотя бы так:
Total space: 1 048 576 Mb, used: 36 353 Mb, free: 1 012 223 Mb.

**Comment by pozitronik** [comment]
Commit 5a28b07
Сделано, с округлением до целых.

**Comment by vovka36** [comment]
Благодарю, но, как мне кажется, округление до гигабайта это сильно грубо. Особенно актуально для не терабайтных аккаунтов. Всё же до сотых (или десятых) было бы правильнее.

**Comment by dmi7ry** [comment]
В TC же есть настройки округления размера (настройки табуляторов). Может быть можно в соответствии с ними отображать размер?

**Comment by pozitronik** [comment]
>Благодарю, но, как мне кажется, округление до гигабайта это сильно грубо
Ладненько, подшлифую, мне на самом деле тоже не очень нравится после дня использования.
> Может быть можно в соответствии с ними отображать размер?
Это было первое, о чём я подумал, но не получится, к сожалению. Во-первых, тотал не даёт эту информацию в API, а выковыривать её окольными путями довольно сложно. Во-вторых, облако отдаёт информацию с округлением до мегабайт, т.е. совсем-совсем как в TC тоже не сделать.
Ну а пилить собственные настройки для мелкой фичи я не очень хочу.

**Comment by pozitronik** [comment]
commit 4076649ba947cf4fd156cb885bd5b42fc9baa97c
Теперь округляем до сотых.
