### ISSUE TITLE
error: parsing auth token for [email]

### ISSUE THREAD

**Issue by Ingridis13** [pozitronik/CloudMailRu#304]
TC 8.51a x64
Win7 x64 Enterprise
Последняя бинарная сборка плагина

При попытке подключения к аккаунту получаю сообщение об ошибке: error: parsing auth token for [email]
Пароль верный, заход через веб-браузер с ним проблем не вызывает.
Пошагово: стандартная процедура захода через TC -- выбираю "папку"/email-аккаунт, нажимаю Enter, ввожу пароль

Большое спасибо заранее!
Очень нравится Ваш плагин -- без него будет крайне сложно.

**Comment by pozitronik** [comment]
1. Последняя бинарная - canary или release?
2. Зайдите в почту mail.ru, привязанную к аккаунту, и проверьте, есть ли там сообщения "Подозрительная попытка входа в аккаунт" или другие сообщения о "подозрительной активности". Mail стал чаще блокировать подключения из плагина, я пока разбираюсь, как это задетектить. Самому мне это удалось решить через смену пароля.

**Comment by Ingridis13** [comment]
release

Первым дело зашёл! Нет, всё чисто. 
Не заходит из 4х разных аккаунтов, с которых как минимум год ранее всё заходило без проблем. 
Посмотрел почту на всех 4х -- оповещений о подозрительной активности нет.

**Comment by pozitronik** [comment]
Включите [протоколирование](https://github.com/pozitronik/CloudMailRu#%D1%83%D1%80%D0%BE%D0%B2%D0%BD%D0%B8-%D0%BF%D1%80%D0%BE%D1%82%D0%BE%D0%BA%D0%BE%D0%BB%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F) отладочных сообщений, соберите лог и приложите его сюда файлом (адреса и какую-то чувствительную информацию можно предварительно вычистить).

**Comment by pozitronik** [comment]
Да, ещё одна причина, которая время от времени случается — перестают пускать «устаревшие» браузеры. Попробуйте в настройках поменять UserAgent на что-то актуальное.

**Comment by pozitronik** [comment]
> Методом научного тыка выяснилось, что не пускает только при использовании Менеджера Паролей в TC. При ручном вводе пароля -- всё Ok.

Возможно, пароль менялся, а в TC сохранился старый. Или наоборот, в TC был сохранён неверный пароль.

**Comment by Ingridis13** [comment]
Нет, пароли все прежние, всё работало до совсем недавнего времени (аккаунтов несколько)
