### ISSUE TITLE
v251223.C запуск файлов из облака

### ISSUE THREAD

**Issue by midi-creator** [pozitronik/CloudMailRu#306]
v251223.C  При двойном клике, например, на экселевском файле ничего не происходит. Откатился на v111223.C - всё работает штатно. Двойной клик - файл скачивается и запускается в экселе

**Comment by pozitronik** [comment]
fixed: https://github.com/pozitronik/CloudMailRu/releases/tag/v261223

**Comment by midi-creator** [comment]
Спасибо!

**Comment by midi-creator** [comment]
К сожалению, обратно открытый и сохранённый файл не заливается, вываливается в ошибку

**Comment by pozitronik** [comment]
Done. Пожалуйста, в дальнейшем делайте один тикет на одну проблему, либо, если интересно заняться тестированием, можем создать отдельную тему для этого.
Спасибо!

**Comment by midi-creator** [comment]
Если надо, с удовольствием готов поучавствовать

**Comment by pozitronik** [comment]
> Если надо, с удовольствием готов поучавствовать

#308

Просто используйте плагин, как обычно. Если что-то сломано - пишите в [этой теме](https://github.com/pozitronik/CloudMailRu/issues/308).
