### ISSUE TITLE
Canary general

### ISSUE THREAD

**Issue by pozitronik** [pozitronik/CloudMailRu#308]
В этом тикете можно сообщать о любых проблемах, возникших при использовании Canary-билдов плагина.

**Comment by midi-creator** [comment]
Приветствую, последняя версия не может ничего удалить из облака. Просто ничего не происходит, после обновления Ctrl+r  всё остаётся на своих местах

**Comment by Corak667** [comment]
Не удаляются именно директории. Файлы удаляет нормально.

**Comment by midi-creator** [comment]
точно, файлы удалились, директории нет((

**Comment by pozitronik** [comment]
https://github.com/pozitronik/CloudMailRu/releases/tag/v270124

**Comment by Corak667** [comment]
@pozitronik 
Обновил, директории до последней канарейки и сих пор не удаляются...(((((((((

**Comment by pozitronik** [comment]
> @pozitronik Обновил до последней канарейки и директории сих пор не удаляются...(((((((((

[CloudMailRuCanary.zip](https://github.com/pozitronik/CloudMailRu/files/14072743/CloudMailRuCanary.zip)
Проверь пожалуйста на этой сборке.

**Comment by Corak667** [comment]
Вот! На этой уже работает, спасибо!

**Comment by pozitronik** [comment]
По факту я не уверен в том, что найденное решение не сломает что-то ещё. Проблема оказалась довольно странной, и я только частично разобрался в причинах.

**Comment by pozitronik** [comment]
За время использования я не нашёл больше никаких проблем. Поставил последнюю сборку как релизную, эту тему закрываю. Дальнейшие баги — в обычном режиме, отдельными тикетами.
