### ISSUE TITLE
error: parsing auth token

### ISSUE THREAD

**Issue by OmlineEditor** [pozitronik/CloudMailRu#311]
Кажется в mail.ru что-то поменяли и вываливается ошибка и не могу войти в аккаунт: 
`error: parsing auth token for ...`
До этого все работало как нужно и проблем не было.

TC v10.50
CloudMailRu v211123

**Comment by pozitronik** [comment]
Не подтверждаю.
#290

**Comment by OmlineEditor** [comment]
Это я уже пробовала, входила через браузер, UserAgent стоит тот же. Ничего не помогает, уже пару дней не пускает через плагин. Наверное есть какое-то еще условие которое плагин не учитывает. Что это может быть, как решить проблему?

**Comment by OmlineEditor** [comment]
Спустя несколько дней проблема решилась сама. облако mail.ru кривое и частенько меня блочит по непонятной причине.
