### ISSUE TITLE
бэкап паролей

### ISSUE THREAD

**Issue by midi-creator** [pozitronik/CloudMailRu#312]
А научите неразумного пожалуйста.
Можно ли забэкапить логины и пароли от mail.ru в плагине?
Аккаунтов несколько

**Comment by pozitronik** [comment]
Пароли можно сохранить прямо в файле конфигурации MailRuCloud.ini. Тогда для бекапа достаточно хранить его копию.
Если пароли сохранены средствами TC, то тут лучше обратиться с вопросом на http://forum.wincmd.ru. Я не изучал этот вопрос.

**Comment by midi-creator** [comment]
Спасибо!
