### ISSUE TITLE
TC, запущенный не под администратором, падает при попытке открыть опции плагина

### ISSUE THREAD

**Issue by fifonik** [pozitronik/CloudMailRu#33]
Win10 x64 1607
TC 8.52a 64 bit
Поставил плагин ("зашёл" в архив с помощью TC, он предложил поставить плагин, я согласился)
Ctrl+1 затем \
Навожусь на CloudMailRu и жму Alt+Enter -- получаю "Total Commander has stopped working"

Workaround:
Зупустить TC от адиинистратора. Настройки плагина откроются и можно создать аккаунты. Перезапустить TC под обычным пользователем и пользоваться созданными аккаунтами.

Огромное спасибо за плагин.

**Comment by pozitronik** [comment]
Это выглядит так, будто у TC не хватило прав доступа к каталогу, куда установлен плагин. Что странно - как тогда плагин установился?
Если запустить сейчас TC под обычным пользователем, настройки открываются? Какие права доступа у файла MailRuCloud.ini?

**Comment by fifonik** [comment]
Когда устанавливался -- винда попросила увеличить права доступа, очевидно я согласился.
Также она это просит когда я, например, пытаюсь что-нить сделать с помощью TC что-нить в Program Files, Windows итд.
В данном случае просто TC падает. Я такого за ним ни разу не наблюдал (а пользуюсь очень давно, правда плагинами он не обвешан).
Под обычным пользователем настройки не открываются. Чтобы в них попасть -- надо запускать TC под администратором.
Права на MailRuCloud.ini: System, Administrators -- всё кроме Special Permissions, Users -- Read и Read + Execute.

**Comment by pozitronik** [comment]
>винда попросила увеличить права доступа, очевидно я согласился.

Для установки плагина не нужны права администратора. Вероятно, у вас была такая ситуация: изначально вы установили TC с повышенными привилегиями, т.о. доступ к содержимому каталога TC для обычных пользователей остался только на чтение. Этого достаточно для беспроблемной работы TC. Когда вы устанавливали плагин, то TC запросил повышение привилегий, поэтому всё установилось. При попытке создать файл настроек в каталоге, недоступном для записи, плагин рухнул и утянул TC.

Такую ситуация я не предусматривал по очевидным причинам. Сделаю нужные проверки.
Вы же можете просто выставить своему пользователю права на запись для каталога плагина, и настройки будут доступны без повышения привилегий.

**Comment by pozitronik** [comment]
Fixed at commit 5d94253423123cfa4c665cc6db9166c78c65f975
