### ISSUE TITLE
Не удается скачать *.desktop файл из облака.

### ISSUE THREAD

**Issue by darkprof83** [pozitronik/CloudMailRu#36]
А вот в облако такой файл заливается. Через веб форму все скачивается нормально. x64, 8.52a
![default](https://cloud.githubusercontent.com/assets/4998392/17980970/53b3fc1c-6b0a-11e6-9ce4-e3600d4aef1f.png)

**Comment by pozitronik** [comment]
Только этот файл, или любой другой?
Судя по видимому на скриншоте кусочку лога, там та же проблема, что в issue #18

**Comment by darkprof83** [comment]
любой другой файл с расширением .desktop

**Comment by pozitronik** [comment]
Не могу воспроизвести.
Вопросы:

1. Что написано в протоколе после ошибки?
2. Что произойдёт, если изменить расширение файлу прямо в облаке и потом попробовать его скачать?

**Comment by darkprof83** [comment]
Видимо все же это #18 после сегодняшнего запуска файлы вообще не скачивает, только заливает. Если скачивать папку то вообще никаких ошибок не выдает, создает пустую папку и делает вид что копирует. После ошибки окно копирования просто закрывается. Где хранятся разные логи я так и не нашел.

**Comment by darkprof83** [comment]
Настроил тотал на логирование и поставил галку плагины файловой системы, выдает вот это:
26.08.2016 15:38:53: FS:Копирование(Ошибка: Неудачное завершение): \\\CloudMailRu\dark_prof\mysites.txt -> e:\rec\mysites.txt

**Comment by pozitronik** [comment]
Лог видно прямо над файловыми панелями, если даблкликнуть по нему, он откроется в листере. По поведению похоже что это #18, точнее можно будет сказать после просмотра лога.

**Comment by darkprof83** [comment]
Спасибо только теперь обратил вниманик
[wcftplog.txt](https://github.com/pozitronik/CloudMailRu/files/439247/wcftplog.txt)

**Comment by pozitronik** [comment]
Yep, это оно. Ждём впиливания OAuth и надеемся, что поможет.
