### ISSUE TITLE
Возможность сохранить на диск структуру файлов и папок

### ISSUE THREAD

**Issue by Dmitro25** [pozitronik/CloudMailRu#37]
Здравствуйте. 
Хотелось бы иметь возможность сохранить на локальный диск структуру файлов и папок, лежащих в облаке, без скачивания их на компьютер. 
Попытался использовать для этих целей плагин DiskDir, чтобы "сохранить" содержимое облака в *.nst файл. По всплывающему окошку вижу, что CloudMailRu прочитал всю структуру папок из облака и... начал скачивать файлы по одному на локальный диск. Я не совсем точно знаю, каким образом взаимодействует плагин с TotalCommander'ом (создание nst-файла вызывается через диалог архивации), но, может быть, есть возможность сохранять структуру облачного диска?

**Comment by pozitronik** [comment]
Видимо, плагин, кроме структуры каталогов, запрашивает ещё и сами файлы, возможно, чтобы получить какие-то атрибуты. Я тут сделать ничего не могу.

**Comment by OmlineEditor** [comment]
> Видимо плагин, кроме структуры каталогов, запрашивает ещё и сами файлы, возможно, чтобы получить какие-то атрибуты. Я тут сделать ничего не могу.

Вы закрыли этот и мой тикет тоже. Я предложил вам вариант решения проблемы. Вы сможеет его реализовать?

**Comment by pozitronik** [comment]
Это не решение, а костыль, потенциально сулящий множество проблем. Я не стану этим заниматься.

**Comment by OmlineEditor** [comment]
> Это не решение, а костыль, потенциально сулящий множество проблем. Я не стану этим заниматься.

Почему костыль поясните? вы сейчас в плагине можете сохранить данные о файлах из облака в файл. структура этих данных:
hash "ХЭШ:размер:ИмяФайлаСПолнымПутем"
я предлагаю эту структуру просто поменять на другую, ничего больше не меняется:
ИмяФайлаСПолнымПутем =TAB=> размер =TAB=> ХЭШ

Мы меняем порядок переменых и за место двоеточия используем табуляцию. Где костыль, я его не вижу? Ткните меня носом, я блондинка и не понимаю в чем может быть проблема? Я здесь виж только положительные моменты. Мы сможем без подключения к облаку знать его содержимое.

**Comment by OmlineEditor** [comment]
> Это не решение, а костыль, потенциально сулящий множество проблем. Я не стану этим заниматься.

вы так и не ответили на вопрос в чем костыль?

**Comment by pozitronik** [comment]
Предполагая, что мой ответ приведёт к дальнейшим спорам, я не стану тратить на них время.
