### ISSUE TITLE
Не верное отображение данных загрузки

### ISSUE THREAD

**Issue by DesignStudio** [pozitronik/CloudMailRu#38]
Версия плагина: 09082016, Win 7 x64, TС 8.52a.
Не верное отображение данных загрузки:
http://take.ms/wNX2l, http://take.ms/CM5T3

**Comment by pozitronik** [comment]
Ссылки 404.
Если речь о загрузке разбитых больших файлов - известное поведение.

**Comment by DesignStudio** [comment]
Нет, не о них. Не могу прикрепить скрины, но если перейти по ссылкам, все видно (обновил линки).

**Comment by pozitronik** [comment]
Объём файлов?

**Comment by DesignStudio** [comment]
Первый (видео) - 1GB, второй (фото) - 12МБ

**Comment by pozitronik** [comment]
А почему тогда на первом скриншоте файл весит 2898,2 Мб, на втором - 2725,3 Мб?

**Comment by DesignStudio** [comment]
Ну диалоговое окно Вами же разработано, Вам и более понятно что на скрине )))
Но по моему это суммарный объем всех залитых в текущей сессии файлов.

**Comment by pozitronik** [comment]
Это тоталовское окно, оно не управляется плагином.
Тотал при файловых операциях запрашивает у плагина объём каждого файла, попадающего в выборку (при скачивании файлов), либо берёт эти данные из файловой системы (при закачивании). Далее, получая от плагина прогресс исполнения операции для текущего файла, тотал пытается посчитать прогресс всей операции и скорость исполнения.

Поэтому у меня слишком мало информаций для понимания. Нужно знать, как воспроизвести - например, найти набор файлов, при операциях с которыми прогресс отображается неверно.

**Comment by DesignStudio** [comment]
Файлы на скрине закачиваются на сервер cloud(а).
И такой глюк встречается не всегда, в большинстве случаев данные более правильны.

**Comment by pozitronik** [comment]
Для начала стоит обновиться до версии 29082016.
Потом найти набор файлов, на котором воспроизводится (если ещё будет воспроизводиться) и запостить сюда список (нужны будут размеры файлов в выборке).

**Comment by pozitronik** [comment]
Есть какие-то данные для анализа?

**Comment by DesignStudio** [comment]
После обновления подобного не замечал. правда и пользовался в последнее время мало.

**Comment by pozitronik** [comment]
Закрываю за нехваткой данных для анализа.
