### ISSUE TITLE
Поддержка прокси из IE

### ISSUE THREAD

**Issue by Dreamer-4pda** [pozitronik/CloudMailRu#40]
На работе корпоративная прокся.
Плагин Cloud, использую для доступа к google диску, отлично работает (в его настройках прокси выбран параметр _As in Internet Еxplorer_)
А при попытке подключения плагином CloudMailRu одна и та же ошибка:
`Cloud login error: Socket Error # 10013`

**Comment by pozitronik** [comment]
Посмотрите, как именно настроен прокси в IE, и настройте плагин аналогично. Подхватывать системные настройки прокси я не стану.
