### ISSUE TITLE
Плагин требует msvcr110.dll

### ISSUE THREAD

**Issue by miller7777777** [pozitronik/CloudMailRu#42]
Ставил сегодня на нескольких ПК (Win2008srvR2x64, WinXPx32, Win7x64). Везде вылезала ошибка с сообщением об отсутствии msvcr110.dll.

На Win10x64 не потребовался.

TC 8.52x32, 8.52ax32

Плагин - последняя версия на текущий день.

Логом я, к сожалению, не озаботился.

Выдрал msvcr110.dll из дистрибутива платформы "1С: Предприятия", положил в папку TC. После этого плагин заработал нормально.

Можно ли включить данный файл в дистрибутив и/или репозиторий? Или написать в readme, что он может понадобиться?

**Comment by pozitronik** [comment]
Библиотеку требует не сам плагин, а подключаемые им SSL-библиотеки (в тех случаях, когда используются билды с этими зависимостями; по-моему на [форуме](http://forum.wincmd.ru/viewtopic.php?t=16041) проходили ссылки на сборки без них). Видимо, лежащая в дистрибутивном архиве версия SSL-библиотек как раз такая, я отдельно этим вопросом не озадачивался по той причине, что упомянутая библиотека в подавляющем большинстве случаев уже есть в системе.
В readme упоминание добавлю.
