### ISSUE TITLE
Total Commander виснет при загрузке.

### ISSUE THREAD

**Issue by darkprof83** [pozitronik/CloudMailRu#43]
Если открыть скажем в правой панели свое облако и закрыть программу, а затем запустить, то программа виснет и в системе перестает срабатывать enter. Доступ к облаку стоит по паролю, без доп пароля. Версия 8.52a 64 бит. На скрине не видно но мышка находится на той кнопке, что должна быть активной :) Заменил в totalcmd.ini путь на локальный и он запустился. Плаг только что обновил.

**Comment by pozitronik** [comment]
Скрина не вижу.

**Comment by pozitronik** [comment]
На TC 9.0b11 не могу воспроизвести.

**Comment by darkprof83** [comment]
Извините пришлось переотправлять сообщение скрин не приаттачился Такая проблема возникает на не активированных ТС из за окна выбора из трех вариантов.
![totalcmd](https://cloud.githubusercontent.com/assets/4998392/18608641/a77139ec-7cf7-11e6-8a68-88331c28eb6a.png)

**Comment by pozitronik** [comment]
Понял.
Тут, к сожалению, я сделать ничего не могу: окно триала выводится выше окна запроса пароля (и выше всех окон в системе, видимо часть защиты от взлома), а фокус остаётся на окне пароля. Возможность дважды нажать Esc ещё остаётся, но в целом тут сделать ничего нельзя, такое поведение должен бы учитывать разработчик TC.

**Comment by darkprof83** [comment]
а нельзя в плагине отлавливать завершение программы и менять путь в панели?

**Comment by pozitronik** [comment]
Нельзя.
