### ISSUE TITLE
Копирование атрибутов файлов/папок вмести с файлами/папками

### ISSUE THREAD

**Issue by DikBSD** [pozitronik/CloudMailRu#45]
Очень часто при копировании папок и/или файлов на облако cloud.mail.ru требуется, чтобы создаваемые папки/файлы на облаке имели те же атрибуты, что и исходные файлы  (время создания, время изменения). От этого зависит работа некоторых мобильных программ, обращающихся к облаку cloud.mail.ru.
Сделайте, пожалуйста, возможность копирования исходных атрибутов на создаваемые файлы/папки на облаке (галочка на диалоге копирования).
Спасибо.

**Comment by pozitronik** [comment]
web-API не поддерживает установку/изменение атрибутов.

**Comment by DikBSD** [comment]
Жаль... Но все равно - спасибо вам за прекрасный плагин.

**Comment by g8tguy** [comment]
можно считать хеш имя файла+дата на локальной машине + хеш имя файла+дата в облаке после копирования. эти данные хранить в файлике и синхронизировать по нему.
вообщем - единственный выход это написать простейший плагин синхронизации папок/файлов для тотала.

**Comment by Corak667** [comment]
@g8tguy кстати неплохая идея - создавать отдельный файл со со списком файлов в текущей папке на облаке и с него уже опционально подтягивать дату для вывода в файловую систему плагина, если этого файла нету или парсинг с него завершается ошибкой, то получать дату с сервера.

**Comment by g8tguy** [comment]
@Corak667 ! подтягивать дату для вывода в файловую систему плагина из файла - это супер идея! единственный нюанс - если дата на сервере отличная от той что в файле синхронизации - то скорей всего файл был изменен через веб интерфейс и соответственно выводить дату с сервера.

**Comment by yar229** [comment]
Таки можно

Код для примера:
[Запрос на авторизацию](https://github.com/yar229/WebDavMailRuCloud/blob/develop2/MailRuCloud/MailRuCloudApi/Base/Requests/Mobile/MobAuthRequest.cs)
[Запрос на добавление файла](https://github.com/yar229/WebDavMailRuCloud/blob/develop2/MailRuCloud/MailRuCloudApi/Base/Requests/Mobile/MobAddFileRequest.cs)
[Формирование тела запроса](https://github.com/yar229/WebDavMailRuCloud/blob/develop2/MailRuCloud/MailRuCloudApi/Base/Requests/Mobile/RequestBodyStream.cs)

**Comment by pozitronik** [comment]
Спасибо, но, насколько понимаю, там не веб-апи же. А у меня всё очень сильно завязано именно на него. Надо крепко думать, как совместить.

**Comment by yar229** [comment]
Да, в общем, та же петрушка, http-запрос послал, ответ как-то распарсил.

**Comment by pozitronik** [comment]
Это, как минимум, будет работать только при oauth-авторизации. Понятно, что всунуть можно, но если уж делать - то делать отдельную реализацию API мобильного клиента.

**Comment by Owyn** [comment]
Очень бы был полезен функционал сохранения дат создания\изменения для файлов при их загрузке в облако (например в файл filelist.txt в корне) с их последующей установкой обратно при скачивании (если их даты будут найдены в filelist.txt)

в формате filelist можно например держать:
путь к файлу | локальные даты | серверные даты для файла

если серверная дата не совпадает с той что в filelist - вероятно файл был изменён с другой машины\ вебинтерфейса - и надо действовать в соответствии с опцией пользователя ( варианты "Использовать новую дату \ игнорироать )

**Comment by pozitronik** [comment]
Зачем в закрытый тикет? Пересоздайте.
