### ISSUE TITLE
Error getting auth token для аккаунта, защищенного 2-факторной авторизацией

### ISSUE THREAD

**Issue by hellboy81** [pozitronik/CloudMailRu#46]
- С указанным паролем в web интерфейсе проходит успешная авторизация
- Кроме того не работае копирование выделенных элементов из ListBox-а с логами

**Comment by pozitronik** [comment]
1. Дупликат #4 
2. И не должно. Даблклик по нему откроет лог в просмотрщике, оттуда и копировать.

**Comment by VecH** [comment]
No master password entered yet
CONNECT xech2x@mail.ru
Login to xech2x@mail.ru
Requesting auth token for xech2x@mail.ru
Error getting auth token for xech2x@mail.ru

Включена двухфакторка
Сгенерировал пароль для внешнего приложения (что бы не запрашивало код от двухфакторки)
Все равно не входит

**Comment by pozitronik** [comment]
Так, для ясности: имеется в виду двухфакторная авторизация в облаке или дополнительная авторизация по мастер-паролю в TC?
В первом случае - поддержки ещё нет. И я не уверен, поддерживаются ли пароли для внешнего приложения в веб-API.

**Comment by VecH** [comment]
Двухфакторная авторизация это после прохода авторизации по логину и паролю надо ввести еще сгенерированный код в смартфоне (использую FreeOTP) или полученный в СМС
_пароли в TC не храню_
при включенной жвуъфакторной авторизации что бы их систему авторизации могли использовать какие нить старые железяки у которых прошивки не обновляются, или например Mail клиенты, там есть опция для генерации пароля таким приложениям, при вводе которых двухфакторка не запрашивается.

учитывая что они тянут с webdav, подозреваю что с двухфакторкой там есть какие то нюансы, хотя официальный клиент облака спрашивает пароль двухфакторки при первом входе

**Comment by hellboy81** [comment]
Имеется ввиду дополнительная авторизация по SMS.

А теперь внимание вопрос: без этой фичи пользоваться плагином бесполезно, т.к. почти все облака должны быть защищены дополнительно.

У меня так утянули один акк с 1ТБ. Безвозвратно. Восстановить его не удалось. Теперь авторизация идет только через SMS.

Поэтому [вопрос](https://github.com/pozitronik/CloudMailRu/issues/44) как бе остается открытым.

**Comment by pozitronik** [comment]
> я пробовал этот метод, не помогло

И не должно было. Даже если эта фича поддерживается web api (что сомнительно), плагин это не поддерживает.
>учитывая что они тянут с webdav, подозреваю что с двухфакторкой там есть какие то нюансы, хотя официальный клиент облака спрашивает пароль двухфакторки при первом входе

Webdav отключён для всех. Официальные мейлрушные клиенты работают по собственному протоколу, и там наверняка фич поддерживается больше.
>А теперь внимание вопрос: без этой фичи пользоваться плагином бесполезно, т.к. почти все облака должны быть защищены дополнительно.

Тикет #4 - один из первых запросов, и сейчас он первый на реализацию. По срокам ничего обещать не могу, пока нет времени. Код открыт, пулл-реквесты принимаются.

> Поэтому вопрос как бе остается открытым.

Во-первых каким боком там Far? Во-вторых - тут точно не самое лучшее место для поиска альтернативных программ.
Оба тикета закрываю для обсуждения.
