### ISSUE TITLE
2 пожелания

### ISSUE THREAD

**Issue by meotian** [pozitronik/CloudMailRu#50]
отличный плагин! хотелось бы возможность копировать линк на файл (если такое возможно)
и еще такой же плагин для яндекс.диска :)

**Comment by pozitronik** [comment]
1. Что конкретно нужно? Ссылку на файл в облаке? Плагин это умеет, Alt+Enter.
2. Webdav Я.д. доступен через webdav-плагин.

**Comment by meotian** [comment]
1. Понял, мерси! Больше пожеланий нет.
2. Поставил, норм. Только не нашел как ссылку узнать там.

**Comment by pozitronik** [comment]
2 - это уже не ко мне.
