### ISSUE TITLE
Выкидывает из логина на сайте.

### ISSUE THREAD

**Issue by MARK2580** [pozitronik/CloudMailRu#51]
Привет.
Ну во первых огромное спасибо за плагин. Уже больше года имею 1ТБ, а юзать его по человечески не могу.
Такой вот вопрос. Когда я логинюсь в TC то на сайте мыла меня тут-же выкидывает. Это какой-то запрет самого мыла на 2 логина одновременно ?

**Comment by pozitronik** [comment]
Я не могу подтвердить такое поведение: я успешно одновременно авторизовался с двух разных компьютеров, в браузере и в плагине. Возможно, запрет на параллельные авторизации настраивается в профиле аккаунта, но я этого не выяснял.
В любом случае, к работе плагина это отношения не имеет.

**Comment by advokatb** [comment]
Проблему подтверждаю, однако соглашусь, что вряд ли дело в плагине.

**Comment by MARK2580** [comment]
Ах да точно, сто лет не залезал в настройки мыла )))))
