### ISSUE TITLE
Функция копирования внутри одного аккаунта выполняет только перемещение файла

### ISSUE THREAD

**Issue by Corak667** [pozitronik/CloudMailRu#54]
Приветствую. Только что попытался скопировать файлы из одной папки в другую  внутри одного аккаунта, результат - файл моментально скопировался в другую папку и временно его "след" остался в исходной, при следующем обновлении папки - исходный файл исчез. То есть функция копирования тут по сути не отличается от перемещения, разве что временно оставляет след в текущей сессии. Возможно ли как-то реализовать нормальное копирование файла? Хотя бы скачиванием в темпоралку на винте и перезаливом в другую на серве, если более шустрый и простой вариант не прокатит.

**Comment by pozitronik** [comment]
1. Подтверждаю, есть баг при копировании файлов в пределах одного аккаунта.
2. Заодно с починкой бага можно оптимизировать перемещение: если в API найдётся подходящая функция, то достаточно будет просто менять путь файлов в облаке.

**Comment by Corak667** [comment]
@pozitronik если в api не найдется аналога, но найдется, например функция сохранения файлов себе в облако из расшаренной ссылки, думаю ее также можно было бы использовать в данном случае, хотя и потребует дополнительные костыли и хитрость.

**Comment by pozitronik** [comment]
Я исправил ошибку, из-за которой копирование и перемещение внутри одного аккаунта работали одинаково, просьба проверить.

Однако, выявилось особенность облака: API не умеет в переименование с изменением пути, переименование возможно только в текущем каталоге. Из-за этого могут быть проблемы в ситуациях, когда копирование/перемещение производится с переименованием, но файл с текущим именем в каталоге-получателе уже есть. Переименовать файл до операции я не имею права (т.к. это в случае последующей ошибки он так и останется переименованным, что нарушает ожидаемое поведение), вводить же работу через временный каталог на сервере/локально - тоже не правильно.
К тому же, в этом случае облако ответит 500 кодом состояния, который  должен обозначать любую ошибку исполнения на стороне сервера, поэтому положиться на этот ответ я не могу.

Так что в таких случаях будет просто сообщаться об ошибке.

**Comment by Corak667** [comment]
Проверил, теперь все отлично копируется и перемещается в пределах аккаунта. Огромное спасибо!
