### ISSUE TITLE
Копирование-перенос файлов между разными аккаунтами

### ISSUE THREAD

**Issue by Corak667** [pozitronik/CloudMailRu#55]
Приветствую. 
В облаке майлру есть возможность "сохранить расшаренный кем-то файл или даже целую папку" себе в целевую папку на своем облаке.
Используя эту фишку возможно было бы реализовать моментальное копирование или перенос файлов между несколькими аккаунтами.
Как реализовать - сделать временную шару по ссылке на одном акке и отпарсив ее уже через плагин - и сохранить в папку на целевом акке. Но думаю это уже можно будет реализовать как логическое продолжение функции обработки ссылок шары. Кстати, возможно это был бы еще один потенциальный метод копирования файлов между папками одного акка, чтобы не пришлось перезаливать через темпоралку или память.
В данный момент попытка копировать между облаками вызывает только панельку закачки "Копирование на сервер", и все..

**Comment by pozitronik** [comment]
Подтверждаю, копирование между аккаунтами не работает. Это довольно странно, я тестировал этот функционал.
Что касается переноса расшаренных каталогов - нужно посмотреть, есть ли подходящий метод в API.

**Comment by pozitronik** [comment]
Копирования между аккаунтами не будет, и я напрямую запретил такое поведение в коде.
Вообще TC умеет распознавать случаи, когда операции проводятся между разными удалёнными ФС (например, разными FTP), и проводить копирование/перемещение через локальную ФС. В случае файлсистемных плагинов проблема в том, что для TC любой такой плагин - одна цельная файловая система. То, что в плагине представлено разными аккаунтами - это всего лишь каталоги первого уровня в представлении TC, так что локальный буфер не подключается.
Реализовать такое распознавание внутри плагина можно, но я не вижу смысла это делать: гораздо проще и правильнее будет пользователю самому проводить копирование в два этапа.

Что касается копирования через временную шару - да, похоже это возможно, но требует времени.

**Comment by Corak667** [comment]
Спасибо) Нечто подобное подозревал, поэтому и предложил вариант про копирование через шару. Ок тогда, остается только ждать его.

**Comment by pozitronik** [comment]
Добавлена поддержка сохранения публичных файлов/каталогов, через команду clone, например
> clone https://cloud.mail.ru/public/BhXc/x4RjZVVK5

Содержимое публичной ссылки сохранится в текущий каталог.

Пока так. Копирование через временную шару - дело времени.

**Comment by Corak667** [comment]
Подтверждаю. Работает отлично:
http://i.imgur.com/I6iMKYK.png
Отличная новость! Спасибо! Буду ждать полноценного копирования между аккаунтами.

**Comment by Corak667** [comment]
А как в дальнейшем планируется это реализовать? Открывать шару для каждого файла из списка копируемых? Вроде как я слышал - там есть лимит на количество открытых ссылок (1500) - более старые при этом закрываются. Так что имеет смысл отключать временную ссылку по результату копирования, чтобы не повредить какие-то официальные опубликованные где-то ссылки.
https://help.mail.ru/cloud_web/confines

**Comment by pozitronik** [comment]
Что-то вроде такого:
if (public_url_exists) {
clone(public_url,new_path);
} else {
public_url = create_pulbic_url(old_path);
clone(public_url,new_path);
remove_public_url(old_path);
}

**Comment by pozitronik** [comment]
Реализована поддержка копирования/перемещения между аккаунтами через публичные ссылки [см](https://github.com/pozitronik/CloudMailRu/blob/master/MailRuCloud.dpr#L745).
Поддержка таких операций должна быть включена в настройках.

Замечания:
1. TC пытается проводить операцию над каждым файлом в отдельности, после каждой итерации вызывая перечитывание структуры каталогов (это, вроде бы, настраивается). Это долго и накладно, поэтому для быстрого копирования рекомендуется использовать **clone**.
2. По той же причине проводимую операцию невозможно отменить, но над этим я ещё постараюсь поработать).

**Comment by Corak667** [comment]
Проверил, да, отлично работает, хоть и очень медленно)

**Comment by pozitronik** [comment]
>Проверил, да, отлично работает, хоть и очень медленно)
См. #62

**Comment by pozitronik** [comment]
commit 073072bb9b69cbd5ca7e88fa091c987b969c8732
Добавил возможность отмены операции по нажатию Cancel

**Comment by Corak667** [comment]
Да, отмена по Cancel работает, подтверждаю.
