### ISSUE TITLE
Удаление папки с облака происходит пофайлово, вместо папки целиком.

### ISSUE THREAD

**Issue by Corak667** [pozitronik/CloudMailRu#56]
Заметил только что, когда пытался удалить массивную папку на более 10000 файлов в своем облаке, что удаление файлов происходит пофайлово, то есть запрашивается КАЖДЫЙ файл в текущей папке (примерно 10 файлов в секунду на моем коннекте), простое удаление папок, где куча мелких файлов может в таком случае занять несколько часов, дней и возможно даже месяцев (в зависимости от скорости соединения). Через интерфейс сайта они вполне удаляются целиком без опроса каждого файла внутри. Возможно ли реализовать аналогичное поведение?

**Comment by pozitronik** [comment]
Это стандартное поведение TC при работе с удалёнными файловыми системами. Я посмотрю, умеет ли API в такое быстрое удаление, и если да - постараюсь сделать опцию для его включения.

**Comment by pozitronik** [comment]
В общем, тут нет ошибки.
При попытке удалить каталог TC запрашивает рекурсивный листинг его содержимого для подсчёта размера и оценки времени удаления, например. Это требует времени, но легко отменяется единоразовым нажатием Esc, либо отключается в настройках TC.
Удаляется же каталог целиком и быстро.

**Comment by Corak667** [comment]
К сожалению нет, если нажать Esc - он просто отменяет удаление. О какой опции идет речь? Если про "подсчитывать место, занимаемое подкаталогами" перед копированием/удалением - то эта опция не помогает.

**Comment by pozitronik** [comment]
Странно, сейчас перепроверил - действительно, удаляет пофайлово. Надо разобраться.

**Comment by pozitronik** [comment]
Изучил, как TC удаляет каталоги: он рекурсивно проходит по всей удаляемой структуре, удаляя каждый файл. В принципе, это логичное поведение.
Чтобы обойти его, добавил команду rmdir. Т.е., чтобы удалить каталог, требуется набрать в командной строке
 rmdir dirname
находясь в родительском каталоге.
Имена каталогов, содержащие пробелы, нужно заключать в двойные кавычки:
 rmdir "some dir"

Прошу проверить.

**Comment by Corak667** [comment]
Проверил, да, через rmdir теперь работает. Спасибо) Возможно ли в дальнейшем определение папок и удаление их через эту комманду в интерфейсе файловой системы?

**Comment by pozitronik** [comment]
> Возможно ли в дальнейшем определение папок и удаление их через эту комманду в интерфейсе "файловой системы"?

Нет, поэтому я и сделал команду.

**Comment by Corak667** [comment]
Похоже явно стоит написать Гислеру о подобной ситуации, думаю он одобрит и сделает решение для плагинов файловых систем. Напишу ему.

**Comment by pozitronik** [comment]
Да, хорошая мысль.

**Comment by Corak667** [comment]
Написал Кристиану, будем ждать ответа.
http://i.imgur.com/CWotwLU.png

**Comment by Corak667** [comment]
Кстати, а вот тут этот сабж мельком поднимали, но нужно знать немецкий или гуглопереводом:
http://ghisler.ch/board/viewtopic.php?t=38607
https://translate.google.com/translate?hl=ru&sl=de&tl=en&u=http%3A%2F%2Fghisler.ch%2Fboard%2Fviewtopic.php%3Ft%3D38607&sandbox=1

**Comment by pozitronik** [comment]
Ага. Но тут уж как всемогущий решит.
Я бы был не против возможности добавлять свои пункты в контекстное меню файлов, например. Другого варианта расширения интерфейса FS-плагинов я не вижу.

**Comment by Corak667** [comment]
Получил ответ от Всемогущего)
http://picsee.net/upload/2016-11-14/4c03c6828d9a.png
Цитирую:
"Hi!

You wrote:
> There's one interesting and very helpful plugin in development:
> https://github.com/pozitronik/CloudMailRu
[...]
> Still we found some troubles in FS plugin api of Total Commander - deletion
> of directories are extremely slow if there many files. There can be
> zillions of them in single folder, and so deletion could be almost eternal,
> because every single file deleting...

There is an easy solution: You need to implement the FsStatusInfo function.
Total Commander will send FS_STATUS_START, FS_STATUS_OP_DELETE
when deleting starts. Set a per thread flag that deleting has started. When
it is set, return INVALID_HANDLE_VALUE when FsFindFirst is called, and
SetLastError(ERROR_NO_MORE_FILES);

Then Total Commander will delete the directory without going inside.
You also need to looks for FS_STATUS_END, FS_STATUS_OP_DELETE
to re-enable reading.

It's important to save that separately per thread, if the plugin supports
background file transfers (only when FsGetBackgroundFlags is
implemented and returns BG_DOWNLOAD or BG_UPLOAD).

Best regards"

**Comment by pozitronik** [comment]
Это был бы хороший вариант, и я над ним уже думал, но, вроде бы, не увидел способа определить, какая именно файловая структура удаляется. Возможно я что-то упустил, Гислеру уж точно виднее. Постараюсь разобраться.

**Comment by pozitronik** [comment]
Проверяем в свежем билде. Удаление и операции между аккаунтами происходят моментально.

**Comment by pozitronik** [comment]
UPD: только удаление. С копированием/перемещением не получилось.

**Comment by Corak667** [comment]
Только что проверил - удаление уже работает моментально. Спасибо)
