### ISSUE TITLE
соединение через HTTP(s) прокси

### ISSUE THREAD

**Issue by JARVISSIMO** [pozitronik/CloudMailRu#57]
добавьте, плиз... :)

**Comment by pozitronik** [comment]
Посмотрю, что можно сделать.

**Comment by pozitronik** [comment]
Так, тащем-то это уже есть: https://geektimes.ru/post/279076/#comment_9539708

**Comment by pozitronik** [comment]
TODO: поменять подпись у опции HTTP на HTTP(S)

**Comment by JARVISSIMO** [comment]
Спасибо! Работает! :+1:
