### ISSUE TITLE
Сохранение оригинального времени создания файла при загрузке на облако.

### ISSUE THREAD

**Issue by Corak667** [pozitronik/CloudMailRu#60]
Возможно ли как-то реализовать, чтобы при самой загрузке файла на облако сохранялось его время создания-(или последнего изменения), а не время загрузки на сервер или это исключено? Я смотрел-включал опцию "Preserve file creation time", но она не помогает в данном случае. Сервер облака как-то присваивает эту дату, а возможно ли ее изменить?
Это было бы крайне актуально для быстрой синхронизации файлов, которые не меняются по размеру, но меняются по содержимому.

**Comment by pozitronik** [comment]
duplicate #45

**Comment by Corak667** [comment]
Подозревал, жаль)
