### ISSUE TITLE
Ошибка при обрыве связи или перегруженности канала во время копирования на облако.

### ISSUE THREAD

**Issue by Corak667** [pozitronik/CloudMailRu#61]
TC может выдать такую ошибку, если канал связи перегружен во время копирования на облако.
http://picsee.net/upload/2016-11-06/493d90f98424.png
```
---------------------------
Total Commander 9.0Я16
---------------------------
Exception in MailRuCloud.wfx:FsPutFileW!
External exception EEDFADE
Windows XP SP3 5.1 (Build 2600), base: 00400000

Please report this error to the Author, with a description
of what you were doing when this error occurred!

Windows exception: 0EEDFADE
Stack trace:
025A8A51

Raw:
00402249  004033EC  004021C8  0042001E  0042002B  0041EE7F
>0042001E  0041F15D  0042002B  0042002B  0042002B  0042002B
0050004B  0050004B  0050004B  004020A2  00402226  00402249
00417E38  00417AC5  00417E98  0042001E  0042001E  0042001E
004192C0  00403648  
Press Ctrl+C to copy this report!
---------------------------
ОК   
---------------------------

```

Также в логе коннекта появляется такая ошибка:
`Adding file error Socket Error # 10060 Connection timed out.
`
и порой такая:
```
EldSocketError ошибка с сообщением Socket Error # 11001 Host not found. при отправке данных на адрес https://...
EldSocketError ошибка с сообщением Socket Error # 10060 Connection timed out. при отправке данных на адрес https://...
```
(Понимаю, что это нормальное поведение при потере коннекта, но потом коннект не восстанавливается в текущей сессии и собственно возможна ли обработка этого исключения в TC?) Плюс переподключение при восстановлении соединения - не происходит и нужно отменять копирование и начинать снова вручную. А может и вообще повиснуть, что приходится перегружать TC.

Как повторить? Достаточно начать скачивать несколько сотен торрентов (даже 15 хватит) сразу вне очереди во время загрузки файлов на облако.

**Comment by pozitronik** [comment]
Если выдаётся неотловленная ошибка, то исключение, вероятно, где-то дальше плагина, например в SSL-библиотеках. Тут я бессилен.
Плагин не устанавливает подключения, как такового, по сути все операции, начиная от получения листинга каталогов до закачки файла атомарны. Если операция отвалилась с ошибкой - правильно будет её остановить и разобраться. Если зависла - тем более.

Кое-какие фиксы в эту сторону я планирую (см #58), но это не совсем про текущую ситуацию.

**Comment by pozitronik** [comment]
Я подтверждаю отсутствие алерта при обрыве связи (при перегрузке канала предполагается аналогичное поведение) - только сообщение в лог. Я не уверен, считать ли это корректным поведением, попробую сделать ключ, отвечающий за появление алерта в такой ситуации.

**Comment by pozitronik** [comment]
commit d2e09bfc0a5ce571ffcfcebdd9ae240d6dfd61ac:
Добавлена возможность переопределять таймауты соединения (указанное время применяется к ConnectTimeout и ReadTimeout). Увеличение таймаута может помочь при плохом соединении (конечно, без гарантий), уменьшение - остановить операцию при перегруженном канале.
commit 74dc1f393c5aff55a1aaa28aa6f5bdaad9e902a2:
Добавлена возможность останавливать операции загрузки/скачивания при любых ошибках (не только сетевых). Если опция "Ask to stop downloads/uploads on any error" включена, то при любой проблеме операция будет приостановлена, а пользователю будет предложено отменить операцию, или продолжить, игнорируя ошибку.

**Comment by Corak667** [comment]
Если отключить соединение:
При закачке: http://i.imgur.com/rnPKinq.png
EIdSocketError ошибка сети: Socket Error # 10054
Connection reset by peer. при отправке данных на адрес https://cloclo11-upload.cloud.mail.ru/upload/...

При скачивании: http://i.imgur.com/41nwErW.png
EIdReadTimeout ошибка с сообщением: Read timed out. при копировании файла с адреса https://cloclo14.datacloudmail.ru/get/...
опции продолжить или отменить нету. Есть только "ок-отмена", это оно?

**Comment by Corak667** [comment]
И вот эта опция категорически не хочет сохраняться. "галочка" слетает при следущем входе в конфиг
http://i.imgur.com/lwflwKI.png

**Comment by pozitronik** [comment]
>Есть только "ок-отмена", это оно?

Подразумевается, что оно.

>Возможности докачки при обрыве нету?

Нету.

>опция "Ask to stop on any error" категорически не хочет сохраняться.

Проверю.

**Comment by pozitronik** [comment]
>опция "Ask to stop on any error" категорически не хочет сохраняться.
fixed @a95df19908ca0b9909c5da946883180a2fcd8139

**Comment by pozitronik** [comment]
Если по фиксам замечаний больше нет, закрываю тикет.

**Comment by Corak667** [comment]
Встречалась еще такая ошибка, кажется если долгое время (где-то около 5 минут) поставить закачку на паузу и потом снова попытаться продолжить
`EIdOpenSSLAPISSLError ошибка с сообщением: error:00000000:lib(0):func(0):reason(0) при отправке данных на адрес https://cloclo39-upload.cloud.mail.ru/upload/?cloud_domain=1&x-email=ruwimlvovich%40mail.ru&fileapi14797050760246
`

**Comment by pozitronik** [comment]
Это ошибка уже в SSL-библиотеке (подозреваю, что какие-нибудь ключи протухают). По идее, при ней нужно перезапускать операцию, но такой механизм сильно усложнит плагин, и делать его я не буду.
