### ISSUE TITLE
Некорректно оценивается прогресс при копировании

### ISSUE THREAD

**Issue by pozitronik** [pozitronik/CloudMailRu#70]
Попытался слить один из своих террабайтных бекапов (LOSLESS_PART1), скопировал корневой каталог. Копирование идёт правильно, скорость, количество файлов и объём данных показываются верно, но общая шкала прогресса - 100% (файловая - корректна).

**Comment by pozitronik** [comment]
В API нет способов влиять на общую шкалу прогресса. TC пытается вычислить её сам, и, видимо, для случаев, когда копирование идёт с перезаписью, не вычисляет (оценка прогресса при этом потребует много приседаний, так что это оправданно).

**Comment by areht** [comment]
Проблема явно не только при перезаписи есть, например при копировании вложенных каталогов до 100% доходит при копировании всех файлов верхнего уровня, игнорируя подкаталоги. 

Не может быть что ТС на столько не умеет считать

**Comment by pozitronik** [comment]
Покопался в задаче. Похоже, на баг самого TC: если копировать каталог, то прогресс для всех файлов верхнего уровня добавляется сразу, а если зайти в каталог и копировать содержимое - то считается нормально.

**Comment by pozitronik** [comment]
Косвенно подтверждаю проблему в TC: при работе с FTP суммарный прогресс также не вычисляется. Гислер упоминал (ссылку дать не могу, давно дело было), что FS-плагины сделаны по образу и подобию внутреннего FTP, логично, что и ошибки одинаковы. Надо репортить (оставлю ссылку в issue #62).
