### ISSUE TITLE
Ошибка при открытии папки на облаке, которая уже удалена.

### ISSUE THREAD

**Issue by Corak667** [pozitronik/CloudMailRu#75]
Каждый раз при перезапуске Total Commander - он запоминает последнюю папку в которой находился. Но в случае если эта папка была удалена (или не создана) в файловой системе облака (например удалял с одного компа, а параллельно работал с этой папкой на другом) - выдает критическую ошибку по исключению в TC. Приходится продолжать выполнение, чтобы он сменил папку. Возможно ли как-то обойти эту ошибку?

http://i.imgur.com/eyzNoWD.png
http://i.imgur.com/TAEdCwP.png
"
---------------------------
Total Commander 9.0Я16
---------------------------
Exception in MailRuCloud.wfx:FsFindFirstW!
Access violation at address 047C28DC. Read of address 00000008
Windows 7 SP1 6.1 (Build 7601), base: 00400000

Please report this error to the Author, with a description
of what you were doing when this error occurred!

Windows exception: C0000005
Stack trace:
047C28DC
>0044707D  0044903A  004262E0  004485DF  004262E0  0044854D
004262E0  004486AA  0044903A  004262E0  0055916F  005591B6
00559294  0042336B  004E98A1  004026B8  004026B8  004262E0
0042B9C4  0042BA60  
Raw:
004EE73C  004E9D6E  00407773  004E45B6  00406F24  004023EF
004033EC  005C0041  004E534D  00406F24  004023EF  004033EC
00424822  004E4AC3  005C0041  004D0BA1  004E4C9C  004020A2
00402249  00417E38  00417AC5  00417E98  004262E0  004493B3
00402E66  0044707D  00449309  00448632  00427FE4  004486AA
0044903A  0044905D  004262E0  004485DF  004262E0  0044854D
004262E0  004493B3  0044707D  00449309  00438326  00448632
004486AA  0044903A  0044905D  004262E0  0055916F  0041F19A
0044854D  004262E0  0041357C  005591B6  00559294  00449309
004486AA  00466E40  00466E78  004023EF  004023EF  0042336B

Press Ctrl+C to copy this report!
Continue execution?
---------------------------
Да   Нет   
---------------------------
"

**Comment by pozitronik** [comment]
Это должно было быть исправлено в мастер-ветке (issue #71).

**Comment by Corak667** [comment]
А, все, понял. Прошу прощения, не обновил до последней версии на одном из компов. Теперь выдает просто path not found, но можно по такой "виртуальной файловой структуре постепенно свободно проходить обратно или даже скопировать туда файл или папку, тогда он создаст такой набор директорий.
