### ISSUE TITLE
Процесс Total Commander завершается во время фонового копирования, если случайно попытаться закрыть процесс, но в предупреждении отказаться  от его завершения.

### ISSUE THREAD

**Issue by Corak667** [pozitronik/CloudMailRu#77]
Заменил крайне неприятный момент - если во время копирования на облако (и возможно с облака тоже), переключить копирование в фоновый режим и случайно попытаться закрыть Total Commander, то будет предупреждение о том, что работает фоновый процесс копирования и вопрос для подтверждения - завершить ли Total Commander принудительно или нет, даже если нажать "нет" - процесс все равно будет завершен. Возможно ли реализовать нормальное поведение, чтобы процесс продолжал работу если нажать "нет"?
"Внимание! активных фоновых сеансов: 1. Настаиваете на завершении?"
http://picsee.net/upload/2016-11-24/12a569a1a16a.png

**Comment by pozitronik** [comment]
У меня на только что вышедшей 9.0 фоновый процесс вообще падает в этом случае вместе с TC. Однозначно баг, не знаю чей - мой, или TC. Проверю.

**Comment by pozitronik** [comment]
Пока идея такая: FsDisconnectW вызывается в основном потоке, в то время, как копирование идёт в фоновом => надо ставить флаг остановки операции.
С другой стороны, дисконнект не должен происходить,, если пользователь не согласился закрыть процесс.

**Comment by pozitronik** [comment]
Ещё идея: возможно, на время показа диалога, фоновый процесс стопорится, и ssl-библиотеки некорректно обрабатывают такую ситуацию.

**Comment by Corak667** [comment]
Вероятность есть, но не думаю - фоновый процесс можно поставить на паузу и где-то через минут 5 вполне нормально восстановить закачку, хотя через 10-20 уже будет отказ ssl для данного файла. Также были ситуации полного отказа ssl (кажется когда несколько компов использовали или слишком долго, причину еще не выяснил), что не было доступа ни до любого из акков вообще, в дальнейшем приходилось перегружать TC, чтобы обновить ssl ключ.

При длительной задержке на паузе фоновой закачки:
```
EIdSocketError ошибка сети: Socket Error # 10053
Software caused connection abort. при отправке данных на адрес https://cloclo37-upload.cloud.mail.ru/upload/?cloud_domain=1&x-email=mrakoook%40mail.ru&fileapi14820890850246

```

Бывало такое:
```
EIdHTTPProtocolException ошибка с сообщением: HTTP/1.1 500 Internal Server Error при отправке данных на адрес https://cloclo38-upload.cloud.mail.ru/upload/?cloud_domain=1&x-email=loseman%40list.ru&fileapi14820748820246, ответ сервера: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html>
<head><title>500 Internal Server Error</title></head>
<body bgcolor="white">
<h1>500 Internal Server Error</h1>
<p>The server encountered an internal error or misconfiguration and was unable to complete your request. Sorry for the inconvenience.<br/>
Please report this message and include the following information to us.<br/>
Thank you very much!</p>
<table>
<tr>
<td>URL:</td>
<td>https://cloclo38-upload.cloud.mail.ru/upload/?cloud_domain=1&amp;x-email=loseman%40list.ru&amp;fileapi14820748820246</td>
</tr>
<tr>
<td>Server:</td>
<td>cloclo38.i</td>
</tr>
<tr>
<td>Date:</td>
<td>2016/12/18 15:27:58</td>
</tr>
</table>
<hr/>Powered by Tengine/2.0.0

```

Также при закачке одного файлов было такое:
```
Adding file error: Error connecting with SSL.
EOF was observed that violates the protocol

```

**Comment by pozitronik** [comment]
>фоновый процесс закачки можно поставить на паузу и где-то через минут 5 вполне нормально восстановить закачку

В случае, когда пользователь нажимает на паузу, процесс не останавливается, TC только передаёт сообщение об нажатии, а дальше паузится.обработчик сетевого потока. А при запросе на закрытии плагин вообще никак не уведомляется, и вариант с остановкой процесса мне кажется вполне вероятным. Я спрошу Гислера об этом, как разгребусь.

> Также были ситуации полного отказа ssl (кажется когда несколько компов использовали или слишком долго, причину еще не выяснил), что не было доступа ни до любого из акков вообще

Могу предложить опциональный воркароунд: не останавливать процесс "посередине" закачки файла, а всегда добивать текущий файл, и только потом стопорить. Поскольку для каждого файла устанавливается новое соединение, то ошибка должна исчезнуть.

**Comment by pozitronik** [comment]
Вышла бета TC 9.10, в чейнджлоге есть упоминание об исправлении этой ошибки:

>06.09.17 Fixed: File system plugins, upload/download in background, try close TC -> program was closed even when the user chose "No" (32/64)

Я проверил, ошибка больше не воспроизводится, баг был в TC.

**Comment by Corak667** [comment]
Подтверждаю, баг действительно уже не воспроизводится
