### ISSUE TITLE
После ошибки загрузки больших файлов падает, не чистит %temp%

### ISSUE THREAD

**Issue by areht** [pozitronik/CloudMailRu#79]
Поймал, что в %temp% лежат залоченные(!) файлы .001, .002 в ассортименте (от разных файлов)

Появляются, если места в %temp% не хватило на разбивку.

Попытка повторной отправки падает, видимо на повторной попытке разбить на то же место. Но, кажется, падает и из других процессов. 

File size > 2000000000 bytes, file will be splitted.
File splitting error code: 4, ignored
File size > 2000000000 bytes, file will be splitted.
File splitting error code: 3, ignored

PS. "File splitting error code: 4" - нельзя же так.. Ну ладно я могу в коде найти, но нормальным людям?
PPS. А сделать виртуальный TStream и складывать в TIdMultiPartFormDataStream.AddObject(), вместо возни с копированием файлов было лень, или так не работает?

**Comment by pozitronik** [comment]
>PS. "File splitting error code: 4" - нельзя же так.. Ну ладно я могу в коде найти, но нормальным людям?

Предполагается, что текст ошибки будет приложен к репорту, и мне этого будет достаточно для первоначального разбирательства. Далее, при необходимости, сообщение будет заменено.

>PPS. А сделать виртуальный TStream и складывать в TIdMultiPartFormDataStream.AddObject(), вместо возни с копированием файлов было лень, или так не работает?

Это хорошая идея, я обдумаю её.

**Comment by pozitronik** [comment]
По моей изначальной задумке, место и не должно чиститься. Это %temp%, подразумевается, что его очисткой должна заведовать ОС. Впрочем, добавить очистку несложно.
TIdMultiPartFormDataStream я вводить не буду. Разбиение файлов сейчас работает достаточно хорошо, я не вижу смысла тратить время даже на эксперименты с другими вариантами.
И теперь файлы чанков не должны лочиться в случае ошибки, просьба проверить на свежем мастер-билде.
