### ISSUE TITLE
Параллельное скачивание

### ISSUE THREAD

**Issue by pozitronik** [pozitronik/CloudMailRu#8]
При запущенном потоке копирования с сервера второй поток копирования может вызвать Access violation at address 045258AE.

**Comment by pozitronik** [comment]
Возникает при параллельном скачивании с разных аккаунтов

**Comment by pozitronik** [comment]
Вероятная причина - при забитом канале скачка по второму может оборваться, и соответствующий FileStream вылетит. Проверить на быстром канале.

**Comment by Laex** [comment]
Поставьте в dpr 
IsMultiThread := True;

**Comment by pozitronik** [comment]
Долбаная магия! Похоже, работает!
Commit e5329a5c0a4715f04295f3146d24bced678f76db
