### ISSUE TITLE
Вопросы сборки под XE3

### ISSUE THREAD

**Issue by SchwarzKopf-M** [pozitronik/CloudMailRu#81]
Взяв исходники, немного подправив их чтобы можно было перекомпилировать в XE3 получил что имена файлав в кириллице не перекодируются. И вот так вот выглядит "Новая папка"
![default](https://cloud.githubusercontent.com/assets/1192230/20869254/e0baab70-ba87-11e6-8900-8dc193ea4bb6.png)

**Comment by pozitronik** [comment]
Надо дифф посмотреть.

**Comment by SchwarzKopf-M** [comment]
Не буду создавать новый отчёт, хотя и не правильно в одном писать о разных ошибках. Но при компиляции на XE3 какая-то ошибка в подсчёте размера и выдаёт вот что:
![default](https://cloud.githubusercontent.com/assets/1192230/20869611/67a6c248-ba8f-11e6-843d-a276b02b4d0a.png)

**Comment by pozitronik** [comment]
Без ссылки на диффы ничего даже приблизительно сказать нельзя. Мой код благополучно собирается в RAD Studio 10 и 10.1

**Comment by SchwarzKopf-M** [comment]
А от меня что-то нужно чтобы посмотреть проблему? Как этот дифф получить?

**Comment by pozitronik** [comment]
Залей изменённые исходники на гитхаб, я посмотрю по возможности.

**Comment by SchwarzKopf-M** [comment]
Целью перекомпиляции была русификация ибо с детства как-то к русскому привык. :) При компиляции для меня было как-то чудно и не привычно видеть как например константу const MAX_UNC_PATH = 32767; можно представить в виде MAX_UNC_PATH.ToString... Маленькое пожелание, код не такой уж большой, лучше было-бы сделать обратную совместимость чтобы вот таких проблем не было. Теперь по проблеме... Здесь используется Indy а они известны проблемами с кодировкой. Под другой свой проект правил исходники чтобы проблем с кодировкой не было, подумал что что-то из-за моих исправлений. Но перекомпилировал с чистой последней Indy, проблема осталась. Может удастся что-то исправить, типа принудительной перекодировки имён... Выкладываю полные исходники. Это архив под видом картинки, а то что-то не получается прислать. Откомпилированный плагин лучше использовать для 32 битного коммандера.
![cloudmailruplg rar](https://cloud.githubusercontent.com/assets/1192230/20891856/75140896-bb25-11e6-9c7b-813366e2bfc7.png)

**Comment by pozitronik** [comment]
Заливать исходники на гитхаб архивом, серьёзно? Я ожидал, что ты сделаешь форк, закоммитишь туда свои правки, ну или сразу сделаешь репозиторий. Сейчас уже можешь не заморачиваться, но на будущее - это корректный вариант.
> MAX_UNC_PATH.ToString

Что!? Зачем!?

**Comment by SchwarzKopf-M** [comment]
Да что-то не думал что так нужно, просто как-бы сообщение об ошибках возможных. А вот что-то типа такого преобразования числового значения в строку было, помню. Ну не важно. В общем посмотри и по-возможности может получится что-то исправить о чём писал. Как-то облаком не пользуюсь, но при желании хорошая штучка. :)

**Comment by pozitronik** [comment]
В какой версии TC тестировал свою сборку?

**Comment by SchwarzKopf-M** [comment]
Сейчас это 9.0. На работе сегодня пробовал сборку одну из первых, по-моему от октября на 8.5, всё тоже самое.

**Comment by pozitronik** [comment]
В общем: явных ошибок в коде я не вижу. После замены dpr-файла версией из master (чтобы избавиться от незначительных несовместимостей) код успешно собрался в RAD Studio 10.1, ни одну из описанных проблем я не наблюдаю. Качать и ставить XE3 у меня нет ни желания, ни времени.
У меня есть следующие предположения:
1. XE3 каким-то образом трактует WideString как AnsiString (маловероятно).
2. Ошибка в используемой XE3 реализации TJSONObject, когда строковые Value теряют кодировку.
3. Упущен какой-то неявный параметр в Indy, отвечающий за кодировку.
Было предположение, что плагин запускается на неюникодной версии TC, но там в принципе не должно работать вообще ничего.
Если есть желание копаться - то всё можно исследовать под отладчиком. Если есть желание помочь - то можешь форкнуться и впилить задачу #63, это будет правильнее, чем напрямую переводить исходники.

**Comment by SchwarzKopf-M** [comment]
Я так и понял что проблема не обнаружится на Берлине раз изначально проблем нет. По первому, согласен. По второму, как-то никогда не приходилось сталкиваться до этого с JSON. По третьему, возможно, тем более знаю что там вообще проблемы, хотя отлаживать чужой код плохо представляя что и как всё должно работать... По последнему, хотя и правильно так будет, но пока обещать не буду, время...
В общем спасибо. :)

**Comment by SchwarzKopf-M** [comment]
Спросить больше не у кого как у автора и чтобы не ошибиться, а можно узнать какие именно данные парсятся вот в таких строках:

if Assigned(Obj.values['size']) then size := StrToInt64(Obj.values['size'].Value);
      if Assigned(Obj.values['kind']) then kind := Obj.values['kind'].Value;
      if Assigned(Obj.values['weblink']) then weblink := Obj.values['weblink'].Value;
      if Assigned(Obj.values['type']) then type_ := Obj.values['type'].Value;
      if Assigned(Obj.values['home']) then home := Obj.values['home'].Value;
      if Assigned(Obj.values['name']) then name := Obj.values['name'].Value;

и т.д.   'name' это понятно, но чтобы не ошибиться. Кажется нашёл проблему...

**Comment by pozitronik** [comment]
Лучше всего поставить брекпойнт, и посмотреть json, пришедший на парсинг. Вопросы отпадут сами собой.
