### ISSUE TITLE
Пустой параметр названия [] аккаунта в MailRuCloud.ini блокирует парсинг всех последующих в листе.

### ISSUE THREAD

**Issue by Corak667** [pozitronik/CloudMailRu#88]
Только что обнаружил, что не могу добавлять аккаунты в лист. Посмотрел причины - в результате какой-то ошибки в плагине - в лист добавилось пустое имя [] в список и все добавленные после него - совершенно не отображаются.
http://picsee.net/upload/2016-12-29/51cb95a24ed2.png
```
[]
description=
email=
password=
tc_pwd_mngr=0
unlimited_filesize=0
split_large_files=1
twostep_auth=0
public_account=0
public_url=

```
Вообщем просьба как-то детектить подобное и сразу убирать из парсинга и всего листа, чтобы не мешало в дальнейшем.

**Comment by Corak667** [comment]
Похоже этот пустой параметр появляется, если удалить аккаунт или обновить один из предыдущих - сейчас проблема снова повторилась и он появился вконце

**Comment by Corak667** [comment]
Да, не удаление, но добавление нового аккаунта - добавляю и сразу вконце этот пустой появляется

**Comment by pozitronik** [comment]
Fixed at b01880be0a7d9808cb33342a6d71cb9672ddd77b
