### ISSUE TITLE
При нажатии Отмены во время закачки на облако - вылетает ошибка при закачке каждого последующего файла

### ISSUE THREAD

**Issue by Corak667** [pozitronik/CloudMailRu#89]
При нажатии Отмены во время закачки на облако вылетает ошибка для каждого копируемого файла. 
"error: uploading to cloud: EInvalidPointer ошибка с сообщением: Invalid pointer operation"
То теперь есть если случайно нажать отмену и попытаться просто пропустить один из файлов (Нажимая "Ок" в диалоге продолжения), то всеравно будет "Ошибка при закачке файла!" для всех последующих. В фоновом режиме порой это может даже не вызвать диалог предупреждения и он длительно попытается пройтись по всем копируемым файлам с ошибками, что совершенно невозможно отменить и приходится ставить на паузу и принудительно выключать TC.
Хотелось бы, чтобы в случае отмены, оно ставило на паузу текущую закачку (как с опцией "Пауза"), но тут уже вызывало диалоговое окно с подтверждением об остановке копирования текущего листа, а не с ошибками, чтобы и можно было продолжить закачку остальных файлов, а не начинать все сначала. Возможен вариант даже 3х опций - "Продолжить, Отмена только текущего файла, Отмена всего листа"
Ну либо сразу останавливало закачку всего листа, не вызывая ошибок.

**Comment by pozitronik** [comment]
Не могу воспроизвести на последней сборке. При каких настройках появляется ошибка, и какая последовательность действий к ней приводит?

**Comment by pozitronik** [comment]
Fixed at c3bf1fa5ec78c0beb01110dec05384a709a8e267

**Comment by Corak667** [comment]
Проблема с пропуском листа всех файлов в режиме фонового копирования при отмене еще не решена
Попробуй начать закачку большого списка файлов, переключить в режим фонового копирования и нажать крестик (отмена-закрыть) на окне текущей закачки.
Будет куча ошибок, которые нельзя прервать или паузнуть - пройдется по всему листу файлов.
"
error: uploading to cloud: EInvalidPointer ошибка с сообщением: Invalid pointer operation
error: uploading to cloud: EInvalidPointer ошибка с сообщением: Invalid pointer operation
"

**Comment by pozitronik** [comment]
Гляну

**Comment by Corak667** [comment]
При нажатии отмены в обычном режиме еще возникла ошибка:
"---------------------------
Total Commander 9.0
---------------------------
Access violation at address 00401E17. Write of address 10F3A1AD.
Access violation at address 00401E17. Write of address 10F3A1AD
Windows XP SP3 5.1 (Build 2600), base: 00400000

Please report this error to the Author, with a description
of what you were doing when this error occurred!

Windows exception: C0000005
Stack trace:
00401E17
004026A0  00446F0C  0046409E  004026B8  004299F5  004497E6
00447829  004497E6  >00426A8C  00448D8B  00426A8C  0042C170
0042C20C  
Raw:
004020A2  00402226  00402226  004026A0  00407967  00407998
0044788E  00447829  0044776B  00446F0C  00446FB2  0046409E
00403414  004023C7  004023EF  004023C7  004023EF  00403414
0040236D  004026B8  00402D6E  00402FB7  00443574  00402DA9
00463F7C  004402F3  00440432  0044B987  00449E21  00449CBE
004299F5  0044A2BE  0044B418  00402E8E  00447829  00449AB5
00428790  00428790  00448E56  004497E6  00449809  00447829
00449AB5  00428790  00448E56  004497E6  00426A8C  00448D8B
00426A8C  0042C170  0042C20C  0042C3C6  
Press Ctrl+C to copy this report!
Continue execution?
---------------------------
Да   Нет   
---------------------------
"

**Comment by Corak667** [comment]
Пардон, стоп. Все решилось. В релизе была более ранняя версия, скачал с гита последнюю - все нормально. Можно закрывать. Прошу прощение за лишнее беспокойство.

**Comment by pozitronik** [comment]
В каком релизе была ошибка? В v31122016 всё должно быть пофикшено.

**Comment by Corak667** [comment]
В 31122016 пофикшено, все верно. Просто у меня там лежал рядом архив с 19122016, я его взял случайно.

**Comment by pozitronik** [comment]
ok
