### ISSUE TITLE
Доступ к публичным каталогам

### ISSUE THREAD

**Issue by pozitronik** [pozitronik/CloudMailRu#9]
Думается, что у доступных публично каталогах облака ровно те же правила доступа, что у публичных, только без авторизации. Сделать возможность добавлять такие аккаунты без авторизации.

**Comment by MARK2580** [comment]
Имеется ввиду каталоги которые кто-то тебе "расшарил" в пользование ?

**Comment by pozitronik** [comment]
Да.

**Comment by pozitronik** [comment]
Поверхностное исследование показало, что принцип работы публичных каталогов несколько отличается. Загруженная страница сразу содержит JSON с перечислением верхнего уровня шары и текущего открытого каталога, этот JSON отдаётся билдеру, который уже рисует страницу. Билдер проверяет доступы и запрашивает пароли, но это уже другая история.

Технически впилить поддержку в плагин несложно.

**Comment by pozitronik** [comment]
Оказалось сложнее, чем я думал, но, тем не менее, не настолько, чтобы бросать идею.
Ветка разработки: https://github.com/pozitronik/CloudMailRu/tree/task9

**Comment by pozitronik** [comment]
Слито в master

**Comment by pozitronik** [comment]
- [] Проверить реакцию на команды rmdir/clone в фс публичной ссылки.
