### ISSUE TITLE
Поддержка Linux

### ISSUE THREAD

**Issue by avently** [pozitronik/CloudMailRu#90]
Перешел на Линукс, а тут вместо Total Commander его функции выполняет Double Commander. Плагины поддерживаются (например, плагин Adb работает шикарно), но должны быть скомпилены для Линукса. Не знаю, много ли изменений нужно внести в код, но, думаю, для профи это будет реально. Можете внести это в свой todo?

**Comment by pozitronik** [comment]
Embarcadero Delphi обещает поддержку сборки под Linux уже в следующем релизе, но как это будет - неясно. Сейчас собирать Delphi-код под Linux умеет Lazarus, но в любом случае потребуются значительные доработки, на которые у меня нет времени. Я совершенно не хочу менять среду разработки, я не пользуюсь Linux в повседневной работе, я не пользуюсь Double Commander, и не смогу (да и не хочу) оказывать поддержку для случаев, не пересекающихся с моим опытом.

Код плагина открыт, и если кто-то возьмётся за переделку под DC - я буду только рад, но сам я этим заниматься пока что не намерен.

**Comment by avently** [comment]
Я правильно понимаю, что сейчас вы собираете с помощью Embarcadero Delphi? И если они в новой версии добавят поддержку Линукса, то менять код будет не нужно? Просто делфи я вижу первый раз в жизни и собрать сам точно не смогу.

**Comment by pozitronik** [comment]
>И если они в новой версии добавят поддержку Линукса, то менять код будет не нужно?

Поживём - увидим. Скорее всего, переписывать придётся в любом случае, но количество изменений можно будет оценить только после после появления этой поддержки.

**Comment by avently** [comment]
@pozitronik можете протестировать билд для линукса сейчас? Поддержка уже есть.

**Comment by pozitronik** [comment]
Интереса ради - попробую, без всяких обещаний.
Правда Total Commander под *nix нет, и, скорее всего, не будет, а с DC уж как получится.

**Comment by pozitronik** [comment]
Как и обещал, интереса ради посмотрел RAD Studio 10.2, в котором действительно есть Linux-компилятор. Писать, правда, пока можно только консольные приложения и библиотеки, но для плагина этого достаточно.
Но по моей оценке работа по портированию будет сложнее, чем написание всего кода заново. Весь winapi-related код надо переписывать на posix, начиная от переопределения типов данных и структур, заканчивая изменением функций, дёргающих winapi-вызовы. Winapi-кода много, потому что WFX API Total Commander создавалось с завязкой на него. Придётся выкинуть все диалоговые окна, и переписать логику, завязанную на них. Будут проблемы с отладкой (код пишется под Windows-машиной, хост-процесс c Double Commander крутится под linux-машиной). Будут проблемы, которые я пока не вижу.
Всё это, в принципе, решаемо и даже любопытно, но, во-первых, у меня не найдётся столько времени, во-вторых - под linux гораздо проще использовать, например, [WebDavMailRuCloud](https://github.com/yar229/WebDavMailRuCloud).

**Comment by avently** [comment]
@pozitronik понял, неоправданно много работы это требует. Спасибо, что хотя бы убедились в этом
