### ISSUE TITLE
Баг при первичном добавлении аккаунта

### ISSUE THREAD

**Issue by ElizTriad** [pozitronik/CloudMailRu#91]
- Версия плагина v31122016
- Windows 10 Pro x64
- Для чистоты эксперимента пробовал скачивать разные версии TC: **8.52**, **9.0а**, 32 битные и 64, чистые и с сторонними плагинами, результат всегда один и тот же
- При первичном добавлении аккаунта в **MailRuCloud.ini** образуются параметры которые препятствуют добавлению и отображению последующих аккаунтов/ссылок

Нашел так же временное решение:
Достаточно удалить лишние скобки и всё начинает работать как положено, непонятно только почему происходит создание лишних скобок 
![11111111111](https://cloud.githubusercontent.com/assets/25110550/21947357/d7d5761a-d9f5-11e6-9e04-037c0389e85a.gif)

**Comment by pozitronik** [comment]
Странно, я обходил эту ситуацию. Проверю.
