### ISSUE TITLE
Exception in MailRuCloud.wfx:FsFindFirstW

### ISSUE THREAD

**Issue by 23rd** [pozitronik/CloudMailRu#92]
---------------------------
Total Commander 8.52a
---------------------------
Exception in MailRuCloud.wfx:FsFindFirstW!
External exception EEDFADE
Windows 10 10.0 (Build 14393)

Please report this error to the Author, with a description
of what you were doing when this error occurred!

Windows exception: 0EEDFADE
Stack trace:
04E35A68
675424  >675E28  610848  4EB45C  4EC300  657452
44930F  446865  447E42  4487D2  425BC0  425BC0
447D77  425BC0  42B2A4  42B340  706B0B  
Raw:
675424  6FC88C  6FC88C  703B2B  672BEE  67433B
703D43  6FC88C  402249  4033D0  4021C8  417968
4175F5  4179C8  675E28  703D43  6FC88C  703B2B
41E875  704920  703C27  568BDB  704920  704B2F
703C27  568C22  568D00  704B2F  465FFC  703703
703AC5  466034  6DFD12  430051  610848  424102
423FFF  41EC01  41EC18  419B78  419B90  703C27
6FCDD4  6FCE21  6C3185  6C9580  5E2918  6C20FC
706309  6B7FC2  61A9FE  61AA21  447CE5  425BC0
448B4B  446865  448AA1  43614F  464755  447E42

Press Ctrl+C to copy this report!

Hope this helps.

**Comment by pozitronik** [comment]
It not helps at all. I need to know how to reproduce error step by step. Plugin version (master/release/etc) and plugin settings information also can be helpful.

**Comment by pozitronik** [comment]
I fix some issues, please check last build from master.

**Comment by 23rd** [comment]
Thanks for fix, but I dont know how to check last build.
Last release was v31122016.

**Comment by pozitronik** [comment]
Just download and replace wfx/wfx64 file from [this page](https://github.com/pozitronik/CloudMailRu).

**Comment by 23rd** [comment]
I found and downloaded updated binary files.
Downloaded release zip archive.
Unziped it, replaced binary files, made zip and installed.
Same here.
Windows 10 x64, TC 8.52a.
![default](https://cloud.githubusercontent.com/assets/4051126/22292775/ed6a9826-e31d-11e6-803a-a6891165c6e8.png)

**Comment by pozitronik** [comment]
1. Show me your MailRuCloud.global.ini file (it placed in plugin install dir).
2. How do you get an error? You just opened \CloudMailRu in Network Neighborhood, and get error message, right?
3. Can you reproduce that on TCx64?
4. Try to delete (or rename) x32 and x64 dirs from plugin install dir, and reproduce error after this.

**Comment by 23rd** [comment]
1.
`[Main]
LoadSSLDLLOnlyFromPluginDir=0
PreserveFileTime=0
DescriptionEnabled=0
OperationsViaPublicLinkEnabled=0
AskOnErrors=0
ChunkOverwriteMode=0
DeleteFailOnUploadMode=0
OverwriteLocalMode=0
DisableMultiThreading=0
DisableIcons=0
SocketTimeout=-1
ProxyType=0
ProxyServer=
ProxyPort=0
ProxyUser=
ProxyPassword=
ProxyTCPwdMngr=0`
2. Open folder-account inside CloudMailRu.
3. Have no Tc64.
4. Same here (And with LoadSSLDLLOnlyFromPluginDir=1).

**Comment by pozitronik** [comment]
Show me yours MailRuCloud.ini then (without stored passwords). Don't copy contents, attach it here.

**Comment by 23rd** [comment]
![default](https://cloud.githubusercontent.com/assets/4051126/22294176/50429318-e323-11e6-9324-510de0ae2485.png)

**Comment by pozitronik** [comment]
Sorry, i still can't reproduce this.
In general this kind of errors may emerge from ssl-libraries (therefore i asked about problem with x64 version).

**Comment by pozitronik** [comment]
Удалось воспроизвести нечто похожее на виртуалке с чистой XP. Вероятнее всего, проблема в openssl dll, если победить не удастся, то надо, хотя бы, поставить обработчики ошибок.

**Comment by LimeBeck** [comment]
Столкнулся с той же проблемой как в х86, так и в х64 версиях, помогло включение опции "Load SSL libraries only from plugin directory"

**Comment by pozitronik** [comment]
В лог что-то пишет, или сразу валится? ОС какая?

**Comment by LimeBeck** [comment]
---------------------------
Total Commander 9.0a
---------------------------
Exception in MailRuCloud.wfx:FsFindFirstW!
External exception EEDFADE
Windows 10 10.0 (Build 14393), base: 00400000

Please report this error to the Author, with a description
of what you were doing when this error occurred!

Windows exception: 0EEDFADE
Stack trace:
059F4A2C
>0055A7D5  0055A81A  0055A905  00402249  004026B8  0044983E
0044983E  00426AE0  00448DE3  00426AE0  00448D51  00426AE0
00447881  00448EAE  0044983E  00426AE0  00426AE0  004D98DA
004DA7B8  004479D4  00447881  00448EAE  004477B7  00449BF2
00447881  0044983E  00426AE0  00448DE3  00426AE0  00448EAE
0044983E  00448D51  00448D51  00426AE0  00448EAE  0044983E
00426AE0  00448DE3  00448DE3  00426AE0  0042C1C9  0042C264

Raw:
004020A2  00402249  00417ED8  00417B65  00417F38  0055A7D5
0055A81A  0055A905  004676E0  0053005A  00530047  005C0057
0053005A  00440047  0044005A  00490051  005C0063  0053005A
0053005A  00402249  00403414  004021C8  004026B8  00403707
00448D51  00448D51  00426AE0  00449BB7  00449BB7  00447881
00449B0D  00438B2A  00438B2A  00448E36  00448EAE  0044983E
00449861  00426AE0  00448DE3  00448DE3  00426AE0  004D8732
00449B9A  00447881  00449B0D  00438B2A  00448E36  00448EAE
0044983E  00449861  00426AE0  00448DE3  00426AE0  00402E8E
00447881  
Press Ctrl+C to copy this report!
Continue execution?
---------------------------
Yes   No   
---------------------------

**Comment by pozitronik** [comment]
В лог соединения, а не эту ошибку, которой TC плюётся в каждом непонятном ему случае.

**Comment by LimeBeck** [comment]
Если правильно понимаю, лог "wcftplog.txt"?
CONNECT ***
Login to *****
EIdOSSLCouldNotLoadSSLLibrary ошибка с сообщением: Could not load SSL library. при запросе данных с адреса https://cloud.mail.ru/api/v2/folder?sort={%22type%22%3A%22name%22%2C%22order%22%3A%22asc%22}&offset=0&limit=10000&home=/

**Comment by pozitronik** [comment]
Да, оно, спасибо.

**Comment by vonder2** [comment]
Мне так же помогло включение опции "Load SSL libraries only from plugin directory"

**Comment by pozitronik** [comment]
Да, проблема именно в SSL-библиотеках, пока предполагаю, что те или иные библиотеки могут сбоить в зависимости от системного окружения.  Для меня это всё немножко магия, и я не очень надеюсь в ней до конца разобраться. Потому моя задача в том, чтобы плагин корректно обрабатывал ошибки, возвращаемые SSL-частью, и хотя бы не падал.

**Comment by pozitronik** [comment]
Я добавил перехват исключения при ошибке загрузки SSL-библиотек. Это должно в какой-то мере решить проблему.
+ пофиксил проблему, из-за которой библиотеки из подкаталогов x32/x64 могли не подгружаться.
