### ISSUE TITLE
Exception in MailRuCloud.wfx:FsFindFirstW!

### ISSUE THREAD

**Issue by curious-man** [pozitronik/CloudMailRu#94]
Ошибка при подключении
Exception in MailRuCloud.wfx:FsFindFirstW!
External exception EEDFADE
Windows 10 10.0 (Build 14393)

Please report this error to the Author, with a description
of what you were doing when this error occurred!

Windows exception: 0EEDFADE
Stack trace:
05684A2C
675424  >675E28  610848  4EB45C  4EC300  656D25
4469B8  446865  447E42  44679B  448B86  446865
4487D2  425BC0  447D77  425BC0  4487D2  425BC0
447CE5  447CE5  425BC0  447E42  4487D2  425BC0
447D77  447D77  425BC0  42B2A4  42B340  706B0B

Raw:
675424  4023EF  6E6196  6E4954  6E49D6  6E49DE
703D43  6FC88C  703D43  6FC88C  4F80A4  67C460
448B4B  446865  448AA1  703B2B  672BEE  672BEE
43E130  44A41A  67433B  703D43  6FC88C  4F80A4
4020A2  402249  417968  4175F5  4179C8  6B8CEC
675E28  5E28BB  5E28D1  703D43  6FC88C  6FCB84
6B7FC2  61A9FE  61AA21  704920  703C27  568BDB
704920  704B2F  703C27  568C22  568D00  704B2F
465FFC  703703  703AC5  466034  6DFD12  430051
610848  703D43  6FC88C  4F90CD  5E28BB  5E28D1

**Comment by pozitronik** [comment]
Дупликат issue #92.
Укажите пожалуйста всю информацию, указанную [здесь](https://github.com/pozitronik/CloudMailRu#Часто-задаваемые-вопросы)
