### ISSUE TITLE
Не работает в 64 Битной версии.

### ISSUE THREAD

**Issue by Max000XAKeP** [pozitronik/CloudMailRu#97]
Мучился почти всю ночь, то устанавливал с++, то менял версии тотлкомандера и т.д.
до подключал по разному........  
А оказалось, что все версии тот командора работают с плагином только при запуски TOTALCMD.EXE
А при TOTALCMD64.EXE везде ошибка. 

Я давно использовал только 64 битную версию. Возможно я не один такой).
Может данную фишку,  может данную фишку указать в описании?  

Видео: https://cloud.mail.ru/public/7CGZ/63cdM6tPo

**Comment by pozitronik** [comment]
На видео видно следующее:
- TC, скорее всего, взломанный. Уже это позволяет не принимать тикет - неизвестно, что и как сломано в бинарнике.
- Не открывается сетевое окружение, что к работе плагина никакого отношения не имеет (а, скорее всего, связано с предыдущим пунктом).
