### ISSUE TITLE
public account

### ISSUE THREAD

**Issue by KDimon87** [pozitronik/CloudMailRu#98]
как работает данная функция? отмечаю галкой пункт public account, втавляю ссылку в поле link, прописываю имя, жму add\apply, но никакой реакции не происходит. TC 9.0a x64, плагин также последний. win 7 x64

**Comment by pozitronik** [comment]
Никакой видимой реакции и не должно быть. Аккаунт с именем из поля Account name становится публичным - при входе в него будет показано содержимое, доступное по этой ссылке.

**Comment by KDimon87** [comment]
проблема именно с добавлением аккаунта, при удалении всех заново добавить не получается ни публичный ни активный

**Comment by pozitronik** [comment]
Версия плагина? Что в файле MailRuCloud.ini после нажатия Apply?

**Comment by KDimon87** [comment]
разобрался в чем баг, не знаю почему но там первые две строки были 
[]
description=
если их удалить то все работает

**Comment by pozitronik** [comment]
Эта [ошибка](https://github.com/pozitronik/CloudMailRu/issues/91) была исправлена в текущей мастер-сборке.

**Comment by KDimon87** [comment]
перекачал и перепроверил еще раз на версии v31122016, баг повторяется

**Comment by pozitronik** [comment]
[Мастер-сборка.](https://github.com/pozitronik/CloudMailRu)

**Comment by KDimon87** [comment]
блин, не то качал... тысяча извинений
